/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.toml --include-runtime=false` (hash: 35028a84d8e3bffee8572638cdc54ce6)
interface __BaseEnv_Env {
	AI: Ai;
	KNOWGRPH_MCP_PUBLIC_BASE_URL: "https://airvio.co";
	KNOWGRPH_MCP_TOOL_LIST_NAME: "knowgrph-video-remix";
	KNOWGRPH_LIVE_CLIENTS: "0";
	MCP_AGENT: DurableObjectNamespace<import("./index").KnowgrphMcpAgent>;
	RUN_MANIFEST_STORE: DurableObjectNamespace<import("./index").RunManifestStore>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "KnowgrphMcpAgent" | "RunManifestStore";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "KNOWGRPH_MCP_PUBLIC_BASE_URL" | "KNOWGRPH_MCP_TOOL_LIST_NAME" | "KNOWGRPH_LIVE_CLIENTS">> {}
}
