export const buildRawKnowgrphVdeoxplnRegistry = ({
  KNOWGRPH_VDEOXPLN_IDS,
  KNOWGRPH_AGENT_READY_TOOL_IDS,
  KNOWGRPH_LOCAL_MCP_TOOL_NAMES,
  buildKnowgrphLocalMcpToolNameList,
  buildReadOnlyBrowserToolNames,
  buildKnowgrphApplicationCompositionVdeoxpln,
}) => Object.freeze([
  {
    id: KNOWGRPH_VDEOXPLN_IDS.sourceFiles,
    title: "Knowgrph Source Files",
    purpose: "Discover, read, inspect, and route published Source Files and shared documents through the canonical storage and document-structure owners.",
    scope: "read-only-published",
    mutation: "read-only",
    triggers: ["source files", "published documents", "shared document", "read markdown", "inspect document structure"],
    inputs: ["workspace document", "published markdown", "share token", "share URL", "canonical path"],
    outputs: ["source-files index", "published markdown", "document structure report"],
    owners: [
      "canvas/src/features/workspace-fs/workspaceFs.ts",
      "canvas/src/features/source-files/sourceFilesSignatures.ts",
      "canvas/src/features/agent-ready/publishedToolExecutors.mjs",
      "canvas/src/features/agent-ready/sharedDocumentStructureInspection.mjs",
      "cloudflare/pages/knowgrph-agent-ready.mjs",
    ],
    tools: {
      published: [
        KNOWGRPH_AGENT_READY_TOOL_IDS.listSourceFiles,
        KNOWGRPH_AGENT_READY_TOOL_IDS.readSourceFile,
        KNOWGRPH_AGENT_READY_TOOL_IDS.readSharedDocument,
        KNOWGRPH_AGENT_READY_TOOL_IDS.inspectSharedDocumentStructure,
      ],
      browserLocal: [KNOWGRPH_AGENT_READY_TOOL_IDS.inspectLocalSourceFilesSnapshot],
      local: [
        KNOWGRPH_LOCAL_MCP_TOOL_NAMES.search,
        KNOWGRPH_LOCAL_MCP_TOOL_NAMES.fetch,
        KNOWGRPH_LOCAL_MCP_TOOL_NAMES.vdeoxplnList,
      ],
    },
    workflow: [
      "Resolve source identity from storage, share token, or canonical path.",
      "Fetch through published storage/document executors.",
      "Inspect structure with the shared document-structure owner.",
      "Return read-only artifacts without graph mutation.",
    ],
    aiPolicy: {
      mode: "none",
      maxAttempts: 0,
      tokenBudget: 0,
      fallback: "Return source-read or structure errors without model calls.",
    },
    artifactPolicy: {
      persistence: "published-read-only",
      graphMaterialization: "none",
      semanticKeyInputs: ["workspaceId", "canonicalPath", "shareToken", "toolContract"],
    },
    validation: ["agent-ready:check", "pages:check-sync", "vdeoxpln:check"],
    publish: ["pages-agent-skills", "http-mcp", "webmcp-html-fallback"],
  },
  {
    id: KNOWGRPH_VDEOXPLN_IDS.agentReady,
    title: "Knowgrph Agent Ready",
    purpose: "Inspect Knowgrph health, MCP, WebMCP, A2A, OpenAPI, commerce, and browser-local readiness without claiming deployed mutation.",
    scope: "read-only-published-and-browser-local",
    mutation: "read-only",
    triggers: ["agent-ready", "webmcp", "mcp health", "openapi", "a2a", "discovery", "readiness"],
    inputs: ["agent-ready base URL", "browser runtime state", "published metadata"],
    outputs: ["agent surface inspection", "browser-local readiness snapshot", "metadata report"],
    owners: [
      "canvas/src/features/agent-ready/knowgrphAgentReadyToolContract.mjs",
      "canvas/src/features/agent-ready/webMcpRuntime.ts",
      "canvas/src/features/agent-ready/agentSurfaceInspection.mjs",
      "cloudflare/pages/knowgrph-agent-ready.mjs",
      "scripts/check-agent-ready.mjs",
    ],
    tools: {
      published: [KNOWGRPH_AGENT_READY_TOOL_IDS.inspectAgentSurface],
      browserLocal: buildReadOnlyBrowserToolNames(),
      local: [KNOWGRPH_LOCAL_MCP_TOOL_NAMES.vdeoxplnList],
    },
    workflow: [
      "Inspect published agent-ready metadata.",
      "Inspect browser-local state only when running inside the app runtime.",
      "Report scope boundaries between Pages read-only tools and browser-local inspectors.",
    ],
    aiPolicy: {
      mode: "none",
      maxAttempts: 0,
      tokenBudget: 0,
      fallback: "Return metadata inspection errors directly.",
    },
    artifactPolicy: {
      persistence: "inspection-only",
      graphMaterialization: "none",
      semanticKeyInputs: ["toolContracts", "metadataRoutes", "browserLocalToolNames"],
    },
    validation: ["agent-ready:check", "vdeoxpln:check"],
    publish: ["pages-agent-skills", "http-mcp", "browser-webmcp"],
  },
  {
    id: KNOWGRPH_VDEOXPLN_IDS.localMcp,
    title: "Knowgrph Local MCP",
    purpose: "Expose Knowgrph-owned local Source Files, Agentic Canvas OS docs invocation, managed implementation runs, UI, pipeline, SuperAgent, video-remix, browser bridge, SEA-LION, HTML video, visual annotation, memory, probe-tree, showrunner, OS status, and vdeoxpln tools through the stdio MCP server.",
    scope: "local-stdio",
    mutation: "local-confirmed",
    triggers: ["local mcp", "agentic canvas os docs", "managed implementation run", "/implementation.run", "#managed-implementation-run", "@work-item", "@implementation-run", "/", "#", "@", "launch canvas", "run pipeline", "graphrag", "superagent", "video remix", "browser api", "sealion sidecar", "html video", "visual annotation", "memory layer", "probe tree", "showrunner", "os status", "list vdeoxpln"],
    inputs: ["local root", "agentic canvas os invocation token", "workspace file", "graph data", "pipeline config", "reference URL", "source cards", "browser API runtime", "Southeast Asian language text", "render spec", "annotation asset", "memory scope", "probe branch", "creative brief"],
    outputs: ["local tool result", "Agentic Canvas OS docs invocation result", "durable implementation-run state", "review-ready pull-request handoff", "pipeline artifact", "superagent report", "video remix run manifest", "SEA-LION sidecar result", "render manifest", "annotation result", "memory result", "probe checkpoint", "showrunner artifact", "OS status snapshot", "vdeoxpln registry snapshot"],
    owners: [
      "mcp/local-tool-contract.js",
      "mcp/server.js",
      "mcp/agentic-canvas-os-docs-runtime.js",
      "mcp/director-lanes.js",
      "mcp/director-workflow.js",
      "mcp/video-remix-runtime.js",
      "mcp/README.md",
      "knowgrph_parser/superagent_harness.py",
      "canvas/src/features/agent-ready/knowgrphVdeoxplnContract.mjs",
    ],
    tools: {
      published: [],
      browserLocal: [],
      local: buildKnowgrphLocalMcpToolNameList(),
    },
    workflow: [
      "List local tools from the shared local MCP contract.",
      "Run only path-guarded local-root operations.",
      "Run video-remix orchestration as an approval-gated local manifest before any paid provider call.",
      "Resolve Agentic Canvas OS /, #, and @ docs invocations from the sibling docs SSOT.",
      "Forward SEA-LION regional language, localization, and safety calls to the hosted sidecar with server-owned auth.",
      "Summarize artifacts and registry metadata in the MCP result.",
    ],
    aiPolicy: {
      mode: "optional-via-local-tools",
      maxAttempts: 1,
      tokenBudget: "tool-owned",
      fallback: "Return local command failure and detected artifacts.",
    },
    artifactPolicy: {
      persistence: "local-workspace",
      graphMaterialization: "tool-owned",
      semanticKeyInputs: ["localToolNames", "rootScope", "artifactList"],
    },
    validation: ["vdeoxpln:check", "mcpLocalToolContract"],
    publish: ["local-mcp-docs"],
  },
  {
    id: KNOWGRPH_VDEOXPLN_IDS.chatToCanvas,
    title: "Knowgrph Chat To Canvas",
    purpose: "Route AI-assisted graph generation through FloatingPanel Chat, KGC validation, Workspace FS, Source Files, and Canvas apply owners.",
    scope: "browser-local-ai-assisted",
    mutation: "browser-local-user-mediated",
    triggers: ["chat to canvas", "generate graph", "kgc markdown", "flow.subgraphs", "apply to canvas"],
    inputs: ["chat request", "workspace context", "selection context", "source evidence", "model settings"],
    outputs: ["validated KGC Markdown", "workspace artifact", "GraphData", "canvas topology snapshot"],
    owners: [
      "canvas/src/features/chat/floatingPanelChat/floatingPanelChatSubmitCoordinator.ts",
      "canvas/src/features/chat/floatingPanelChat/floatingPanelChatSubmitRequest.ts",
      "canvas/src/features/chat/chatMarkdownValidation.ts",
      "canvas/src/features/chat/chatKgcCanvasApply.ts",
      "canvas/src/features/workspace-fs/workspaceFs.ts",
      "canvas/src/features/source-files/applyComposedGraphFromSourceFiles.ts",
      "canvas/src/lib/graph/semanticKey.ts",
    ],
    tools: {
      published: [],
      browserLocal: [
        KNOWGRPH_AGENT_READY_TOOL_IDS.inspectLocalChatPipelineState,
        KNOWGRPH_AGENT_READY_TOOL_IDS.inspectLocalMainPanelChatCanvasPipeline,
        KNOWGRPH_AGENT_READY_TOOL_IDS.inspectLocalWorkspaceDocument,
        KNOWGRPH_AGENT_READY_TOOL_IDS.inspectLocalCanvasTopology,
        KNOWGRPH_AGENT_READY_TOOL_IDS.inspectLocalCanvasSnapshot,
      ],
      local: [KNOWGRPH_LOCAL_MCP_TOOL_NAMES.vdeoxplnList],
    },
    workflow: [
      "Vdeoxpln context through the shared chat submit request owner.",
      "Call provider transport only after typed request construction.",
      "Validate KGC Markdown with bounded retries.",
      "Persist through Workspace FS and apply through the existing Canvas path.",
    ],
    aiPolicy: {
      mode: "required-for-generation",
      maxAttempts: 2,
      tokenBudget: "settings-owned",
      fallback: "Persist validation or provider failure as reviewable chat/workspace state.",
    },
    artifactPolicy: {
      persistence: "workspace-fs-and-source-files",
      graphMaterialization: "kgc-validation-to-canvas-apply",
      semanticKeyInputs: ["chatContextScope", "workspacePath", "graphSemanticKey", "sourceLayerHash"],
    },
    validation: ["chatResponseContract", "sourceFiles", "vdeoxpln:check"],
    publish: ["browser-webmcp", "mainpanel-mcp"],
  },
  {
    id: KNOWGRPH_VDEOXPLN_IDS.strybldr,
    title: "Knowgrph Strybldr",
    purpose: "Turn image or media source units into editable Storyboard cards and bounded media handoff artifacts through Strybldr and shared renderer owners.",
    scope: "browser-local-source-backed",
    mutation: "browser-local-user-mediated",
    triggers: ["strybldr", "storyboard", "image to storyboard", "media handoff", "visual brief"],
    inputs: ["image source unit", "media metadata", "workspace document", "storyboard graph"],
    outputs: ["Strybldr Markdown", "Storyboard graph cards", "camera-aware media handoff prompt", "canvas snapshot"],
    owners: [
      "canvas/src/features/strybldr/strybldrStoryboard.ts",
      "canvas/src/features/strybldr",
      "canvas/src/features/workspace-fs/workspaceFs.ts",
      "canvas/src/features/source-files/applyComposedGraphFromSourceFiles.ts",
      "canvas/src/components/StoryboardCanvas/storyboardModel.ts",
      "canvas/src/lib/config.render.ts",
      "canvas/src/lib/graph/semanticKey.ts",
      "docs/documents/knowgrph-strybldr-prd-tad.md",
    ],
    tools: {
      published: [],
      browserLocal: [
        KNOWGRPH_AGENT_READY_TOOL_IDS.inspectLocalSourceFilesSnapshot,
        KNOWGRPH_AGENT_READY_TOOL_IDS.inspectLocalCanvasTopology,
        KNOWGRPH_AGENT_READY_TOOL_IDS.inspectLocalCanvasSnapshot,
      ],
      local: [KNOWGRPH_LOCAL_MCP_TOOL_NAMES.vdeoxplnList],
    },
    workflow: [
      "Import media through existing workspace/source owners.",
      "Build Strybldr cards with source-unit provenance.",
      "Persist Camera reframe settings on selected graph cards.",
      "Render through the shared Storyboard surface.",
      "Compile bounded media handoff only after user approval.",
    ],
    aiPolicy: {
      mode: "optional-for-refinement",
      maxAttempts: 1,
      tokenBudget: "user-approved-provider-step",
      fallback: "Keep editable storyboard and structured handoff error.",
    },
    artifactPolicy: {
      persistence: "workspace-fs-and-source-files",
      graphMaterialization: "storyboard-graph",
      semanticKeyInputs: ["sourceUnitId", "strybldrRunId", "graphSemanticKey", "strybldrCamera"],
    },
    validation: ["strybldr", "rendererPipelineNeutrality", "vdeoxpln:check"],
    publish: ["mainpanel-mcp", "browser-webmcp"],
  },
  {
    id: KNOWGRPH_VDEOXPLN_IDS.researchVisual,
    title: "Knowgrph Research Visual",
    purpose: "Create file-backed research visual workflows from source material using Knowgrph parsing, Source Files, Storyboard, renderer, and chat owners.",
    scope: "browser-local-ai-assisted",
    mutation: "browser-local-user-mediated",
    triggers: ["research visual", "explainer", "formula", "algorithm", "proof", "dynamic scene", "storyboard"],
    inputs: ["paper excerpt", "formula", "algorithm", "figure", "workspace document", "source evidence"],
    outputs: ["mechanism brief", "storyboard", "renderer-neutral scene plan", "validated KGC Markdown"],
    owners: [
      "canvas/src/features/parsers/default.ts",
      "canvas/src/features/source-files/applyComposedGraphFromSourceFiles.ts",
      "canvas/src/features/chat/floatingPanelChat/floatingPanelChatSubmitCoordinator.ts",
      "canvas/src/components/StoryboardCanvas/storyboardModel.ts",
      "canvas/src/lib/config.render.ts",
      "canvas/src/lib/graph/semanticKey.ts",
      "docs/documents/knowgrph-vdeoxpln-prd-tad.md",
    ],
    tools: {
      published: [],
      browserLocal: [
        KNOWGRPH_AGENT_READY_TOOL_IDS.inspectLocalChatPipelineState,
        KNOWGRPH_AGENT_READY_TOOL_IDS.inspectLocalSourceFilesSnapshot,
        KNOWGRPH_AGENT_READY_TOOL_IDS.inspectLocalCanvasTopology,
      ],
      local: [KNOWGRPH_LOCAL_MCP_TOOL_NAMES.vdeoxplnList],
    },
    workflow: [
      "Extract source-backed semantic units into workspace artifacts.",
      "Plan exact deterministic graph/storyboard layers before optional AI support.",
      "Persist artifacts through Workspace FS and Source Files.",
      "Use Canvas/Storyboard renderers as projections of graph state.",
    ],
    aiPolicy: {
      mode: "optional-for-drafting",
      maxAttempts: 2,
      tokenBudget: "settings-owned",
      fallback: "Return deterministic source brief with unresolved questions.",
    },
    artifactPolicy: {
      persistence: "workspace-fs-and-source-files",
      graphMaterialization: "kgc-validation-to-canvas-apply",
      semanticKeyInputs: ["sourceSignature", "graphSemanticKey", "rendererId"],
    },
    validation: ["sourceFiles", "chatResponseContract", "vdeoxpln:check"],
    publish: ["mainpanel-mcp", "browser-webmcp"],
  },
  { id: KNOWGRPH_VDEOXPLN_IDS.memoryLayer, title: "Knowgrph Memory Layer", purpose: "Persist, retrieve, inject, extract, and materialize explicitly scoped agent memories through a provider-neutral local harness with source-owned Markdown outputs.", scope: "local-stdio-and-browser-local", mutation: "local-scoped-memory", triggers: ["memory layer", "long-term memory", "cross-session context", "mem0", "personalization", "prompt memory", "procedural memory", "harness replay", "user model", "profile markdown"], inputs: ["user or agent message", "runtime scope", "memory query", "harness output dir"], outputs: ["memory write result", "ranked memory results", "bounded prompt context", "memory cost log", "procedural KGC markdown", "USER_MODEL markdown"], owners: ["canvas/src/features/memory/aiAgentsMemoryLayerContract.mjs", "mcp/memory-layer-runtime.js", "mcp/local-tool-contract.js", "mcp/server.js", "docs/documents/knowgrph-ai-agents-memory-layer-prd-tad.md"], tools: { published: [], browserLocal: [], local: [KNOWGRPH_LOCAL_MCP_TOOL_NAMES.memoryAdd, KNOWGRPH_LOCAL_MCP_TOOL_NAMES.memorySearch, KNOWGRPH_LOCAL_MCP_TOOL_NAMES.memoryAssemblePrompt, KNOWGRPH_LOCAL_MCP_TOOL_NAMES.memoryExtractProcedural, KNOWGRPH_LOCAL_MCP_TOOL_NAMES.memoryMaterializeUserModel, KNOWGRPH_LOCAL_MCP_TOOL_NAMES.vdeoxplnList] }, workflow: ["Require explicit runtime scope.", "Add/search through the configured harness.", "Inject only top-ranked memories within token budget.", "Extract completed harness runs into reusable KGC procedural-memory documents.", "Materialize scoped memories into deterministic USER_MODEL markdown when a source-owned profile is needed."], aiPolicy: { mode: "optional-via-local-tools", maxAttempts: 1, tokenBudget: "memory-harness-owned", fallback: "Return empty memory results or skip write while preserving the agent turn." }, artifactPolicy: { persistence: "operator-configured-local-memory-store", graphMaterialization: "none", semanticKeyInputs: ["memoryScope", "operation", "topK", "providerMode"] }, validation: ["vdeoxpln:check", "mcpLocalToolContract", "aiAgentsMemoryLayer"], publish: ["local-mcp-docs", "mainpanel-mcp"] },
  { id: KNOWGRPH_VDEOXPLN_IDS.aiShowrunner, title: "Knowgrph AI Showrunner", purpose: "Run provider-neutral multi-agent creative pipelines for podcasts, narrative games, and writers rooms through existing Source Files, memory, MCP, KGC, and Storyboard Widget owners.", scope: "local-stdio-and-browser-local", mutation: "local-approval-gated", triggers: ["ai showrunner", "podcast pipeline", "narrative game", "writers room", "creative state", "multi-agent orchestration"], inputs: ["creative brief markdown", "run id", "choice signal", "critique text", "operator approval"], outputs: ["pipeline run state", "creative state entries", "script", "choice graph", "revision history", "artifact manifest"], owners: ["canvas/src/features/ai-showrunner", "canvas/src/features/chat/chatKgcCanvasApply.ts", "canvas/src/features/source-files", "canvas/src/features/memory/aiAgentsMemoryLayerContract.mjs", "canvas/src/lib/graph/semanticKey.ts", "mcp/local-tool-contract.js"], tools: { published: [], browserLocal: [], local: [KNOWGRPH_LOCAL_MCP_TOOL_NAMES.showrunnerStartRun, KNOWGRPH_LOCAL_MCP_TOOL_NAMES.showrunnerRunStatus, KNOWGRPH_LOCAL_MCP_TOOL_NAMES.showrunnerPostChoice, KNOWGRPH_LOCAL_MCP_TOOL_NAMES.showrunnerSubmitCritique, KNOWGRPH_LOCAL_MCP_TOOL_NAMES.showrunnerApproveStage, KNOWGRPH_LOCAL_MCP_TOOL_NAMES.showrunnerGetArtifact, KNOWGRPH_LOCAL_MCP_TOOL_NAMES.vdeoxplnList] }, workflow: ["Validate the frontmatter-first Creative_Brief before any agent turn.", "Run bounded role turns through dry-run or injected provider-neutral dispatch.", "Persist append-only state, token logs, and manifests through Source Files."], aiPolicy: { mode: "optional-via-local-tools", maxAttempts: 1, tokenBudget: "pipeline-run-owned", fallback: "Halt at approval or structured error while preserving committed Creative_State." }, artifactPolicy: { persistence: "source-files", graphMaterialization: "kgc-validation-to-canvas-apply", semanticKeyInputs: ["run_id", "agent_role", "turn_index", "content_hash"] }, validation: ["vdeoxpln:check", "mcpLocalToolContract", "showrunnerDryRun"], publish: ["local-mcp-docs", "mainpanel-mcp"] },
  { id: KNOWGRPH_VDEOXPLN_IDS.htmlVideoRenderer, title: "Knowgrph HTML Video Renderer", purpose: "Render HTML, CSS, and data documents to MP4 video artifacts through a runtime-selected pluggable engine and the existing rich media output owner.", scope: "local-stdio-and-browser-local", mutation: "local-approval-gated", triggers: ["html video render", "html to video", "programmatic video", "render html mp4", "coding agent video"], inputs: ["html document", "css", "data json", "render spec", "engine hint"], outputs: ["mp4 video blob", "render manifest", "artifact path", "render job id"], owners: ["canvas/src/features/html-video-renderer/htmlVideoRendererSsot.ts", "canvas/src/features/html-video-renderer/htmlVideoRenderJob.ts", "canvas/src/features/html-video-renderer/htmlVideoEngineRegistry.ts", "canvas/src/features/html-video-renderer/htmlVideoRendererSpec.ts", "canvas/src/features/html-video-renderer/htmlVideoFlowNode.ts", "canvas/src/features/html-video-renderer/htmlVideoWidget.ts", "canvas/src/features/chat/richMediaRun.ts", "canvas/src/features/source-files", "canvas/src/lib/config.storyboard-widget.ts", "canvas/src/lib/graph/semanticKey.ts", "mcp/local-tool-contract.js", "mcp/server.js", "canvas/src/features/agent-ready/knowgrphVdeoxplnContract.mjs"], tools: { published: [], browserLocal: [], local: [KNOWGRPH_LOCAL_MCP_TOOL_NAMES.htmlVideoRender, KNOWGRPH_LOCAL_MCP_TOOL_NAMES.vdeoxplnList] }, workflow: ["Validate the Render_Spec before any engine call.", "Resolve active engine from KNOWGRPH_HTML_VIDEO_ENGINE or engineHint at invocation time.", "Execute the render engine and capture the video/mp4 blob.", "Route the blob through writeRichMediaWidgetRunOutputArtifact exactly once.", "Return renderJobId, outputPath, outputManifestPath, and outputStorageUrl."], aiPolicy: { mode: "none", maxAttempts: 0, tokenBudget: 0, fallback: "Return structured error without model call." }, artifactPolicy: { persistence: "local-workspace", graphMaterialization: "rich-media-panel", semanticKeyInputs: ["renderJobId", "engineId", "renderSpecHash", "outputPath"] }, validation: ["vdeoxpln:check", "mcpLocalToolContract", "htmlVideoRenderer"], publish: ["local-mcp-docs", "mainpanel-mcp"] },
  { id: KNOWGRPH_VDEOXPLN_IDS.videoAgent, title: "Knowgrph Video Agent", purpose: "Reason over operator-supplied video sources through native knowgrph ingestion, parsing, annotation, dataset operations, zone counting, search planning, edit planning, timeline compilation, generation placeholders, and streamable rich-media output.", scope: "browser-local-and-local-stdio", mutation: "local-approval-gated", triggers: ["video agent", "video reasoning", "video search", "video editing", "video compilation", "video generation", "stream video result", "visual dataset", "zone counting"], inputs: ["operator-supplied video url", "source manifest", "annotation tasks", "search intent", "edit constraints", "render spec"], outputs: ["source manifest", "visual annotation dataset", "zone counting timeline", "moment search index", "edit plan", "timeline manifest", "render spec", "reasoning artifact manifest", "video/mp4 artifact", "inline stream preview"], owners: ["canvas/src/features/video-agent", "canvas/src/features/video-agent/videoAgentDatasetRuntime.ts", "canvas/src/features/html-video-renderer/htmlVideoRendererSsot.ts", "canvas/src/features/html-video-renderer/htmlVideoFlowNode.ts", "canvas/src/features/visual-annotation-engine/annotationDataset.ts", "canvas/src/features/visual-annotation-engine/annotationFlowNode.ts", "canvas/src/features/visual-annotation-engine/annotationSerializers.ts", "canvas/src/features/chat/richMediaRun.ts", "canvas/src/features/source-files", "canvas/src/lib/graph/semanticKey.ts", "canvas/src/features/agent-ready/knowgrphVdeoxplnContract.mjs"], tools: { published: [], browserLocal: [], local: [KNOWGRPH_LOCAL_MCP_TOOL_NAMES.htmlVideoRender, KNOWGRPH_LOCAL_MCP_TOOL_NAMES.annotateImage, KNOWGRPH_LOCAL_MCP_TOOL_NAMES.annotateVideoFrame, KNOWGRPH_LOCAL_MCP_TOOL_NAMES.vdeoxplnList] }, workflow: ["Ingest an operator-supplied video source without embedding a provider runtime dependency.", "Parse source metadata, frame annotations, transcript windows, and searchable moments through existing source and annotation owners.", "Load frame annotations into native visual dataset operators for deterministic split, merge, save, and frame-ordered zone counting.", "Plan search, edit, compilation, and generation stages as typed reasoning artifacts rather than copied external code.", "Compile a source-owned HTML/CSS/data Render_Spec for the selected timeline.", "Stream a video/mp4 artifact or outputSrcDoc preview through the shared Rich Media Panel output owner."], aiPolicy: { mode: "optional-via-local-tools", maxAttempts: 1, tokenBudget: "operator-configured", fallback: "Return structured source, annotation, dataset, zone counting, or render errors without invoking external video-agent services." }, artifactPolicy: { persistence: "local-workspace", graphMaterialization: "rich-media-panel", semanticKeyInputs: ["sourceUrl", "capabilities", "reasoningArtifacts", "visualDataset", "zoneCounting", "renderSpecHash", "streamOutput"] }, validation: ["vdeoxpln:check", "mcpLocalToolContract", "htmlVideoRenderer", "visualAnnotationEngine", "visualAnnotationDataset", "videoAgentPipeline"], publish: ["local-mcp-docs", "mainpanel-mcp"] },
{ id: KNOWGRPH_VDEOXPLN_IDS.visualAnnotationEngine, title: "Knowgrph Visual Annotation Engine", purpose: "Run browser-local image and video-frame annotation into LLM-ready structured JSON plus native visual datasets materialised through existing artifact owners.", scope: "browser-local", mutation: "local-approval-gated", triggers: ["annotate image", "annotate video", "visual annotation", "object detection", "image caption", "florence2", "semantic labels", "llm-ready annotation", "annotation dataset", "zone counting"], inputs: ["image url", "video asset url", "annotation tasks", "model hint", "frame timestamp"], outputs: ["annotation result json", "visual annotation dataset", "zone counting timeline", "llm-ready payload", "annotation canvas node", "markdown summary"], owners: ["canvas/src/features/visual-annotation-engine/annotationEngineSsot.ts", "canvas/src/features/visual-annotation-engine/annotationDataset.ts", "canvas/src/features/visual-annotation-engine/annotationWorker.ts", "canvas/src/features/visual-annotation-engine/annotationOrchestrator.ts", "canvas/src/features/visual-annotation-engine/annotationSerializers.ts", "canvas/src/features/visual-annotation-engine/annotationFlowNode.ts", "canvas/src/features/visual-annotation-engine/annotationMcpTools.ts", "canvas/src/features/visual-annotation-engine/annotationWidget.ts", "canvas/src/features/chat/richMediaRun.ts", "canvas/src/features/source-files", "canvas/src/lib/graph/semanticKey.ts", "canvas/src/lib/config.storyboard-widget.ts", "mcp/local-tool-contract.js", "canvas/src/features/agent-ready/knowgrphVdeoxplnContract.mjs"], tools: { published: [], browserLocal: [], local: [KNOWGRPH_LOCAL_MCP_TOOL_NAMES.annotateImage, KNOWGRPH_LOCAL_MCP_TOOL_NAMES.annotateVideoFrame, KNOWGRPH_LOCAL_MCP_TOOL_NAMES.vdeoxplnList] }, workflow: ["Validate the Annotation_Spec before model resolution or inference.", "Resolve model identifier from modelHint, KNOWGRPH_ANNOTATION_MODEL, or the registered default.", "Dispatch through the Annotation_Worker boundary; Dev emits dependency-free heuristic annotations while model adapters remain runtime-owned.", "Build annotationId with buildScopedGraphSemanticKey using assetUrl, modelId, and sorted tasks.", "Load Annotation_Result or frame-box arrays into the native dataset owner for split, merge, save, and frame-ordered zone counting.", "Route JSON output through writeRichMediaWidgetRunOutputArtifact exactly once.", "Return annotationId, assetUrl, modelId, tasks, outputPath, and outputManifestPath."], aiPolicy: { mode: "none", maxAttempts: 0, tokenBudget: 0, fallback: "Return runtime-local heuristic annotation JSON or a structured validation/runtime error without model call." }, artifactPolicy: { persistence: "browser-local", graphMaterialization: "annotation-canvas-node", semanticKeyInputs: ["annotationId", "assetUrl", "modelId", "sortedTasks", "visualDataset", "zoneCounting"] }, validation: ["vdeoxpln:check", "mcpLocalToolContract", "visualAnnotationEngine", "visualAnnotationDataset"], publish: ["local-mcp-docs", "mainpanel-mcp"] }, buildKnowgrphApplicationCompositionVdeoxpln({ ids: KNOWGRPH_VDEOXPLN_IDS, toolNames: KNOWGRPH_LOCAL_MCP_TOOL_NAMES }),
  {
    id: KNOWGRPH_VDEOXPLN_IDS.commerceReadiness,
    title: "Knowgrph Commerce Readiness",
    purpose: "Inspect Commerce, payment worker, x402, ACP, UCP, MPP, and readiness metadata without bypassing the shared payment SSOT.",
    scope: "read-only-published-and-browser-local",
    mutation: "read-only",
    triggers: ["commerce", "payment", "x402", "acp", "ucp", "mpp", "stripe", "readiness"],
    inputs: ["agent-ready metadata", "commerce route health", "browser readiness snapshot"],
    outputs: ["commerce readiness report", "payment route summary", "agent-ready commerce metadata"],
    owners: [
      "canvas/src/features/panels/views/CommerceHubView.tsx",
      "canvas/src/features/agent-ready/browserLocalSurfaceSnapshots.ts",
      "cloudflare/pages/knowgrph-agent-ready-commerce.mjs",
      "cloudflare/workers/knowgrph-payment/agenticCommerce.ts",
      "grph-shared/src/payments/agenticCommerceSsot.ts",
    ],
    tools: {
      published: [KNOWGRPH_AGENT_READY_TOOL_IDS.inspectAgentSurface],
      browserLocal: [
        KNOWGRPH_AGENT_READY_TOOL_IDS.inspectLocalSettingsChatReadiness,
        KNOWGRPH_AGENT_READY_TOOL_IDS.inspectLocalMainPanelState,
      ],
      local: [KNOWGRPH_LOCAL_MCP_TOOL_NAMES.vdeoxplnList],
    },
    workflow: [
      "Inspect published commerce discovery metadata.",
      "Read browser-local readiness snapshots when available.",
      "Report payment capability boundaries without initiating checkout.",
    ],
    aiPolicy: {
      mode: "none",
      maxAttempts: 0,
      tokenBudget: 0,
      fallback: "Return route or metadata errors directly.",
    },
    artifactPolicy: {
      persistence: "inspection-only",
      graphMaterialization: "none",
      semanticKeyInputs: ["commerceSemanticKey", "routeHealth", "toolContract"],
    },
    validation: ["agent-ready:check", "mainPanelCommerce", "vdeoxpln:check"],
    publish: ["pages-agent-skills", "mainpanel-mcp", "browser-webmcp"],
  },
]);
