export const buildKnowgrphApplicationCompositionVdeoxpln = ({ ids, toolNames }) => ({
  id: ids.applicationComposition,
  title: "Knowgrph Application Composition",
  purpose: "Compose exact-version agents, prompts, typed values, and opaque third-party integration capabilities into immutable provider-neutral plans, then run them through existing bounded runtime owners.",
  scope: "local-stdio-owner-composed",
  mutation: "local-and-external-approval-gated",
  triggers: [
    "/application.compose",
    "#application-composition",
    "@application-manifest",
    "@component-catalog",
    "@integration-profile",
    "@runtime-proof",
    "build agent application",
    "compose llm application",
    "agent component catalog",
  ],
  inputs: ["source-backed application manifest", "exact execution mode", "component catalog digest", "adapter policy digest", "opaque integration profile reference"],
  outputs: ["sanitized application catalog", "immutable application-composition-plan/v1", "bounded application execution result", "migration diagnostics"],
  owners: [
    "contracts/agent-application.schema.js",
    "data/config/agents/agent-application-components.json",
    "mcp/agent-application-adapter-registry.js",
    "mcp/agent-application-runtime.js",
    "mcp/agent-application-tool-contract.js",
    "mcp/external-tool-gateway-runtime.js",
    "mcp/server.js",
  ],
  tools: { published: [], browserLocal: [], local: [toolNames.applicationCatalog, toolNames.applicationPlan, toolNames.applicationExecute, toolNames.vdeoxplnList] },
  workflow: [
    "Catalog exact component, interface, schema, capability, owner, adapter, and opaque integration revisions without model spend or egress.",
    "Validate the canonical /application.compose #application-composition invocation and verify the source-backed manifest digest.",
    "Compile a mode-bound typed dependency DAG and lock every exact revision into one deterministic plan digest.",
    "Replan at admission, compare the exact digest, and sequence only ready steps through their existing host-owned runtimes.",
    "Stop on failure, approval requirement, cancellation uncertainty, or bounds without retry, fallback, migration, provider selection, or deployment.",
  ],
  aiPolicy: { mode: "none", maxAttempts: 0, tokenBudget: 0, fallback: "Return deterministic plan or owner-block evidence; composed owners retain their own authority." },
  artifactPolicy: { persistence: "tool-owned", graphMaterialization: "none", semanticKeyInputs: ["manifestDigest", "mode", "catalogDigest", "adapterPolicyDigest", "planDigest"] },
  validation: ["vdeoxpln:check", "mcpLocalToolContract", "agentApplicationContract", "agentApplicationRuntime"],
  publish: ["local-mcp-docs"],
});
