export const WORKSPACE_SYNC_TASK_PER_DOCUMENT_UI = 'per-document-ui'
export const WORKSPACE_SYNC_SCOPE_PER_DOCUMENT_UI_RUNTIME_PERSISTENCE = 'per-document-ui:runtime-persistence'

export const WORKSPACE_SYNC_TASK_SOURCE_FILES_PERSIST = 'source-files:persist'
export const WORKSPACE_SYNC_TASK_SOURCE_FILES_WORKSPACE = 'source-files:workspace'
export const WORKSPACE_SYNC_SCOPE_SOURCE_FILES_RUNTIME_PERSISTENCE = 'source-files:runtime-persistence'

export const WORKSPACE_SYNC_TASK_MARKDOWN_WORKSPACE_PREFS = 'markdown-workspace:prefs'
export const WORKSPACE_SYNC_TASK_MARKDOWN_WORKSPACE_VIEWER_PREFS = 'markdown-workspace:viewer-prefs'
export const WORKSPACE_SYNC_SCOPE_MARKDOWN_WORKSPACE_PREFS_RUNTIME_PERSISTENCE = 'markdown-workspace:prefs:runtime-persistence'
export const WORKSPACE_SYNC_TASK_MARKDOWN_WORKSPACE_REFRESH = 'markdown-workspace:refresh'
export const WORKSPACE_SYNC_SCOPE_MARKDOWN_WORKSPACE_REFRESH_RUNTIME_PERSISTENCE = 'markdown-workspace:refresh:runtime-persistence'
export const WORKSPACE_SYNC_TASK_MARKDOWN_WORKSPACE_INLINE_EDIT_STATE = 'markdown-workspace:inline-edit-state'
export const WORKSPACE_SYNC_TASK_MARKDOWN_WORKSPACE_INDEX_START = 'markdown-workspace:index-start'
export const WORKSPACE_SYNC_TASK_MARKDOWN_WORKSPACE_AUTOSAVE = 'markdown-workspace:autosave'
export const WORKSPACE_SYNC_SCOPE_MARKDOWN_WORKSPACE_RUNTIME_PERSISTENCE_SHARED = 'markdown-workspace:runtime-persistence:shared'
export const WORKSPACE_SYNC_TASK_MARKDOWN_BLOCK_INLINE_EDIT_STATE = 'markdown-block:inline-edit-state'
export const WORKSPACE_SYNC_SCOPE_MARKDOWN_BLOCK_INLINE_EDIT_STATE_RUNTIME_PERSISTENCE = 'markdown-block:inline-edit-state:runtime-persistence'
export const WORKSPACE_SYNC_TASK_MARKDOWN_EDITOR_SSOT = 'markdown-editor:ssot'
export const WORKSPACE_SYNC_SCOPE_MARKDOWN_EDITOR_SSOT_RUNTIME_PERSISTENCE = 'markdown-editor:ssot:runtime-persistence'
export const WORKSPACE_SYNC_SCOPE_MARKDOWN_WORKSPACE_DATAVIEW_RUNTIME_PERSISTENCE = 'markdown-workspace:dataview:runtime-persistence'
export const WORKSPACE_SYNC_SCOPE_CHAT_HISTORY_RUNTIME_PERSISTENCE = 'chat:history:runtime-persistence'
export const WORKSPACE_SYNC_TASK_GRAPH_TABLE_VIEW_STATE = 'graph-table:view-state'
export const WORKSPACE_SYNC_SCOPE_GRAPH_TABLE_VIEW_STATE_RUNTIME_PERSISTENCE = 'graph-table:view-state:runtime-persistence'
export const WORKSPACE_SYNC_SCOPE_GRAPH_TABLE_RUNTIME_PERSISTENCE = 'graph-table:runtime-persistence'

export const WORKSPACE_SYNC_SCOPE_CANVAS_TAB_SYNC_RUNTIME_PERSISTENCE = 'canvas:tab-sync:runtime-persistence'
export const WORKSPACE_SYNC_SCOPE_CANVAS_PREVIEW_WRITEBACK_RUNTIME_PERSISTENCE = 'canvas:preview-writeback:runtime-persistence'
export const WORKSPACE_SYNC_TASK_FLOW_QUICK_EDITOR_VIEW_STATE = 'flow-quick-editor:view-state'
export const WORKSPACE_SYNC_SCOPE_FLOW_QUICK_EDITOR_RUNTIME_PERSISTENCE = 'flow-quick-editor:runtime-persistence'
export const WORKSPACE_SYNC_TASK_RENDERER_EDGE_TYPE_VIEW_STATE = 'renderer:edge-type:view-state'
export const WORKSPACE_SYNC_SCOPE_RENDERER_EDGE_TYPE_RUNTIME_PERSISTENCE = 'renderer:edge-type:runtime-persistence'

export const WORKSPACE_SYNC_TASK_WORKSPACE_TABLE_PREFS_NOTIFY = 'workspace-table:prefs:notify'
export const WORKSPACE_SYNC_SCOPE_WORKSPACE_TABLE_PREFS_RUNTIME_PERSISTENCE =
  'workspace-table:prefs:runtime-persistence'
