import { analyzeKgcRequest, sanitizeRequestIntent, sanitizeScalar } from './chatKgcRequestProfile'
import {
  buildNamedTermSummary,
  fallbackActor,
  fallbackArtifact,
  fallbackDomain,
  fallbackObjective,
  fallbackOwner,
  fallbackProduct,
  fallbackStatus,
} from './chatHistoryWorkspace.kgc.fallbackSections'
import {
  buildObjectiveSummary,
  buildRequestSummary,
  slugify,
  typedBlockScalarEnvelopeLines,
} from './chatHistoryWorkspace.kgc.fallbackCommon'
import { buildFlowDiagramsBlock } from './chatHistoryWorkspace.kgc.flowDiagramsFallback'
import {
  buildResponseMarkdownLines,
  buildResponseStatus,
  resolveFallbackCanvas2dRenderer,
} from './chatHistoryWorkspace.kgc.responseProjection'

const buildRequiredSectionLabels = (profile: ReturnType<typeof analyzeKgcRequest>): string[] => {
  return [
    profile.requestedSections.useCase ? 'Use Case' : '',
    profile.requestedSections.problem ? 'Problem' : '',
    profile.requestedSections.solution ? 'Solution' : '',
    profile.requestedSections.userFlow ? 'User Flow' : '',
    profile.requestedSections.workflow ? 'Work Flow' : '',
    profile.requestedSections.dataFlow ? 'Data Flow' : '',
    profile.requestedSections.monetization ? 'Monetization Surface' : '',
    profile.requestedSections.integrations ? 'Integration Boundaries' : '',
  ].filter(Boolean)
}

const buildFrontmatterContextSummary = (profile: ReturnType<typeof analyzeKgcRequest>): string => {
  return sanitizeScalar([
    buildNamedTermSummary(profile),
    profile.signals.mcp ? 'MCP distribution' : '',
    profile.signals.externalUsers ? 'external users' : '',
    profile.signals.openClaw ? 'OpenClaw marketplace' : (profile.signals.marketplace ? 'skills marketplace' : ''),
    profile.signals.subscriptions ? 'subscriptions' : '',
    profile.signals.payPerUse ? 'pay-per-use' : '',
    profile.signals.conversion ? 'conversion actions' : '',
    profile.signals.swipe ? 'Swipe checkout' : (profile.signals.payments ? 'checkout' : ''),
    profile.signals.rxdb ? 'RxDB' : '',
    profile.signals.maplibre ? 'MapLibre' : '',
  ].filter(Boolean).join(' + '), 220)
}

const buildFrontmatterValidationFocus = (profile: ReturnType<typeof analyzeKgcRequest>): string[] => {
  return [
    ...buildRequiredSectionLabels(profile),
    profile.namedTerms.length > 0 ? 'named request term coverage' : '',
    profile.signals.openClaw ? 'OpenClaw discovery path' : '',
    profile.signals.swipe ? 'Swipe payment trigger and fulfillment' : '',
    profile.signals.subscriptions ? 'subscription entitlement logic' : '',
    profile.signals.payPerUse ? 'usage-metered action logic' : '',
    profile.signals.conversion ? 'conversion event framing' : '',
    profile.signals.rxdb ? 'RxDB state assumptions' : '',
    profile.signals.maplibre ? 'MapLibre relevance' : '',
  ].filter(Boolean)
}

export const buildFrontmatter = (args: {
  fileName: string
  profile: ReturnType<typeof analyzeKgcRequest>
  assistantText: string
}): string => {
  const subject = fallbackActor(args.profile.subject)
  const product = fallbackProduct(args.profile.product)
  const artifact = fallbackArtifact(args.profile.artifact)
  const domain = fallbackDomain(args.profile.domain, args.profile.topics)
  const objective = fallbackObjective(args.profile.objective)
  const owner = fallbackOwner(args.profile.owner)
  const status = fallbackStatus(args.profile.status)
  const graphId = `md:${slugify(args.fileName)}-pipeline`
  const title = product === '{{product}}'
    ? '{{product}} · AI Pipeline — Chat Response'
    : `${product} · AI Pipeline — ${artifact}`
  const requestSummary = buildRequestSummary(args.profile)
  const contextSummary = buildFrontmatterContextSummary(args.profile)
  const requiredSections = buildRequiredSectionLabels(args.profile)
  const validationFocus = buildFrontmatterValidationFocus(args.profile)
  const renderer = resolveFallbackCanvas2dRenderer(args.profile)
  const responseMarkdownLines = buildResponseMarkdownLines({
    profile: args.profile,
    assistantText: args.assistantText,
  })
  return [
    `title: ${JSON.stringify(title)}`,
    `graphId: ${JSON.stringify(graphId)}`,
    `doc_type: ${JSON.stringify(artifact)}`,
    'date: "{{date}}"',
    'ai_model: "model-unknown"',
    'lang: "en-US"',
    'kgCanvasSurfaceMode: "2d"',
    'kgCanvasRenderMode: "2d"',
    `kgCanvas2dRenderer: ${JSON.stringify(renderer)}`,
    'kgDocumentSemanticMode: "document"',
    'kgFrontmatterModeEnabled: true',
    'kgMultiDimTableModeEnabled: false',
    'kgDocumentStructureBaselineLock: false',
    ...(renderer === 'strybldr' ? ['kgStrybldrStoryboard: true'] : []),
    '$schema: "kgc-pipeline/v1"',
    'spec:',
    '  format:        kgc-pipeline',
    '  version:       "1.0.0"',
    '  parser:        yaml-frontmatter',
    '  execution:     computing-flow',
    '  topology:      DAG-with-feedback',
    '  ssot_surfaces: [pipeline, flow.nodes, flow.edges, mermaid, runner]',
    'runner:',
    '  entry: R01',
    '  exit:  R06',
    '  steps:',
    '    - seq:    R01',
    '      action: ingest',
    '      input:  "raw file bytes"',
    '      output: "parsed YAML object"',
    '      description: >',
    '        Read file from disk (or network). Split on first pair of --- delimiters.',
    "        Parse the frontmatter block as YAML. Validate $schema == 'kgc-pipeline/v1';",
    '        halt with runner-error if schema mismatch. Expose parsed object as',
    '        __doc for downstream steps.',
    '    - seq:    R02',
    '      action: resolve',
    '      input:  "__doc (parsed YAML object)"',
    '      output: "__doc_resolved (vars substituted)"',
    '      description: >',
    '        Walk every string value in __doc. Replace {{key}} with the scalar value',
    '        at doc[key]. Replace {{key:value}} with value and register key→value.',
    '        Replace {{key|fallback}} with doc[key] if present, else fallback.',
    '        Tier B sentinel keys whose value is also a {{key}} pattern are exempt',
    '        from V-03 — render as visible placeholders. Expose __doc_resolved.',
    '    - seq:    R03',
    '      action: build-graph',
    '      input:  "__doc_resolved"',
    '      output: "graph { nodes[], edges[] }"',
    '      description: >',
    '        Instantiate each entry in flow.nodes[] as a graph node object. Instantiate',
    '        each entry in flow.edges[] as a directed edge. Cross-validate: every',
    '        flow.nodes[*].id.value MUST appear in pipeline[*].node AND in mermaid:',
    '        node IDs. Any mismatch halts with ssot-mismatch error naming the',
    '        divergent ID. Attach phase, actor, handles, applies_rules, db_writes,',
    '        retry_arc, confidence, status, kanban from each flow.nodes entry.',
    '    - seq:    R04',
    '      action: compile-compute',
    '      input:  "graph { nodes[], edges[] }"',
    '      output: "graph { nodes[] (compiled fns), edges[] }"',
    '      description: >',
    '        For each node, call parseMappingFn(node) — see TAD section. Before',
    "        new Function(), scan compute.value body for 'fetch', 'document',",
    "        'window'; any match halts compilation for that node and marks it",
    '        @flag:impure. Compiled function is stored on node as node._fn.',
    '        Async nodes (n-process) are flagged node._async = true.',
    '    - seq:    R05',
    '      action: traverse',
    '      input:  "graph (compiled)"',
    '      output: "graph (executed — handle values populated)"',
    '      description: >',
    '        Execute nodes in pipeline[*].seq order (S01 → S05). For each node,',
    '        assemble inputs map from all upstream edges whose targetHandle matches',
    '        a handle in node.handles.target[]. Call node._fn(inputs). Propagate',
    '        returned handle values to downstream edges. Honor feedback arc e5',
    '        (n-validate:correction → n-process:correction): re-execute n-process',
    '        up to runtime.maxRetry times on correction non-null. After maxRetry,',
    '        set both valid_md and correction to null and surface @flag:validation-failed',
    '        on n-validate. TBD inputs are treated as null; node shows @flag:waiting.',
    '    - seq:    R06',
    '      action: render',
    '      input:  "graph (executed) + mermaid: block + body Markdown"',
    '      output: "rendered Knowledge Graph Canvas"',
    '      description: >',
    '        Resolve {{mermaid}} in body with the mermaid: block scalar. Apply',
    '        canvas settings (auto_layout dagre-LR, snap_to_grid, minimap, controls).',
    '        Render pipeline: as the Pipeline table. Apply parseSigil() to all table',
    '        cells. Render flow graph with node cards showing phase, actor, confidence',
    '        badge, kanban status, and @flag annotations. Clicking a node card anchors',
    '        to its seq row in the Pipeline table (links.body_anchor → #pipeline).',
    '        Clicking the Flow Graph heading anchors back to this frontmatter\'s',
    '        documented entry point (links.yaml_anchor → #computing-flow-definition).',
    'links:',
    '  yaml_anchor: "#computing-flow-definition"',
    '  body_anchor: "#flow-graph"',
    `  self_ref: ${JSON.stringify(args.fileName)}`,
    'canvas:',
    '  auto_layout:  true',
    '  layout_algo:  dagre-LR',
    '  snap_to_grid: true',
    '  grid_size:    20',
    '  minimap:      true',
    '  controls:     true',
    '  node_defaults:',
    '    width:  220',
    '    height: 80',
    '  edge_defaults:',
    '    type:     smoothstep',
    '    animated: true',
    'graph_meta:',
    '  node_count: 5',
    '  edge_count: 5',
    '  phase_count: 3',
    '  entry_node:  n-trigger',
    '  exit_node:   n-deliver',
    '  phases:',
    '    - id: P1',
    '      label: "Context Packaging"',
    '      seq_range: "S01–S02"',
    '      nodes: [n-trigger, n-pack]',
    '    - id: P2',
    '      label: "Generate + Validate"',
    '      seq_range: "S03–S04"',
    '      nodes: [n-process, n-validate]',
    '    - id: P3',
    '      label: "Deliver + Persist"',
    '      seq_range: "S05"',
    '      nodes: [n-deliver]',
    '  feedback_arcs:',
    '    - edge:           e5',
    '      from:           n-validate',
    '      from_handle:    correction',
    '      to:             n-process',
    '      to_handle:      correction',
    '      max_iterations: "{{runtime.maxRetry}}"',
    '      on_exhausted:   "@flag:validation-failed"',
    '  forward_edges:',
    '    - {edge: e1, from: n-trigger,  to: n-pack,     handle: signal}',
    '    - {edge: e2, from: n-pack,     to: n-process,  handle: context}',
    '    - {edge: e3, from: n-process,  to: n-validate, handle: md}',
    '    - {edge: e4, from: n-validate, to: n-deliver,  handle: valid_md}',
    'product: ' + JSON.stringify(product),
    'domain: ' + JSON.stringify(domain),
    'subject: ' + JSON.stringify(subject),
    'objective: ' + JSON.stringify(objective),
    'artifact: ' + JSON.stringify(artifact),
    'owner: ' + JSON.stringify(owner),
    'version: "{{version}}"',
    'status: ' + JSON.stringify(status),
    'runtime:',
    '  entry:    {key: entry,    type: string,  value: "n-trigger"}',
    '  exit:     {key: exit,     type: string,  value: "n-deliver"}',
    '  sandbox:  {key: sandbox,  type: string,  value: "quickjs-emscripten"}',
    '  trace:    {key: trace,    type: boolean, value: true}',
    '  maxRetry: {key: maxRetry, type: number,  value: 3}',
    'pipeline:',
    '  - seq: S01',
    '    node: n-trigger',
    '    label: "trigger / input"',
    '    actor: ["{{subject}}", "system"]',
    '    edge_in: "—"',
    '    edge_out: signal',
    '    user_action: "{{subject}} selects scope; states the active request objective and constraints"',
    `    sys_event: ${JSON.stringify(`Runtime injects __selected_scope, __frontmatter, __context_summary globals; compute assembles signal for ${requestSummary || artifact}`)}`,
    '    data_in: "—"',
    `    data_out: ${JSON.stringify(`signal {scope, fm, summary, request_scope: ${contextSummary || domain}}`)}`,
    '    trigger: scope-select event',
    '    on_fail: "@flag:waiting — node blocked until scope selection"',
    '    kanban: TBD',
    '    confidence: high',
    '    status: TBD',
    '  - seq: S02',
    '    node: n-pack',
    '    label: "context pack"',
    '    actor: ["system"]',
    '    edge_in: signal',
    '    edge_out: context',
    '    user_action: "—"',
    `    sys_event: ${JSON.stringify(`packContext() shapes signal into context bundle; includes ${contextSummary || domain}; prepends guideline_digest ≤ 800 tokens as system-prompt prefix`)}`,
    '    data_in: "signal {scope, fm, summary, request_scope}"',
    `    data_out: ${JSON.stringify(`context {selected_scope, frontmatter, context_summary, request_scope, required_sections: ${requiredSections.join(' | ') || 'none'}}`)}`,
    '    trigger: signal non-null',
    '    on_fail: "null emitted on context — all downstream nodes short-circuit"',
    '    kanban: TBD',
    '    confidence: high',
    '    status: TBD',
    '  - seq: S03',
    '    node: n-process',
    '    label: "generate / process"',
    '    actor: ["{{subject}}", "AI"]',
    '    edge_in: "context + correction|null"',
    '    edge_out: md',
    '    user_action: "Request injected as user turn; {{subject}} reviews streamed output for fit and clarity"',
    `    sys_event: ${JSON.stringify(`generateArtifact() calls /v1/messages model {{ai_model}} temp 0.3 max 1000 tokens; output must cover ${objective}`)}`,
    '    data_in: "context {selected_scope, frontmatter, context_summary, request_scope} + correction string[]|null"',
    '    data_out: "md string (raw streamed Markdown)"',
    '    trigger: context received',
    '    on_fail: "null emitted on md — validate short-circuits"',
    '    kanban: TBD',
    '    confidence: high',
    '    status: TBD',
    '  - seq: S04',
    '    node: n-validate',
    '    label: "review / validate"',
    '    actor: ["system"]',
    '    edge_in: md',
    '    edge_out: "valid_md | correction (feedback arc)"',
    '    user_action: "Validation badge appears on node card (high / low / @flag:failed)"',
    `    sys_event: ${JSON.stringify(`validateArtifact() runs V-01–V-07 plus coverage checks for ${validationFocus.join(', ') || 'request-specific requirements'}; first failure emits correction back to n-process via feedback arc e5; pass emits valid_md to n-deliver`)}`,
    '    data_in: "md"',
    '    data_out: "valid_md string (pass) OR correction string[] (fail — feedback arc)"',
    '    trigger: md received',
    '    on_fail: "retry ≤ {{runtime.maxRetry}}× via @edge:n-validate:correction→n-process:correction; then @flag:validation-failed on originating node"',
    '    kanban: TBD',
    '    confidence: high',
    '    status: TBD',
    '  - seq: S05',
    '    node: n-deliver',
    '    label: "deliver / persist"',
    '    actor: ["system"]',
    '    edge_in: valid_md',
    '    edge_out: "—"',
    '    user_action: "Validated artifact is delivered; {{subject}} can publish, iterate, or route to the next workflow step"',
    '    sys_event: "deliverArtifact() calls resolveVars() → parseMappingFn() per node → parseSigil() per cell → upsert flow_nodes + flow_edges → output re-render"',
    '    data_in: "valid_md string"',
    '    data_out: "rendered object + JSONB rows in flow_nodes, flow_edges"',
    '    trigger: valid_md non-null',
    '    on_fail: "short-circuits — output unchanged"',
    '    kanban: TBD',
    '    confidence: high',
    '    status: TBD',
    'mermaid: |',
    '  %%{init: {"theme": "base", "themeVariables": {"primaryColor":"#E1F5EE","primaryTextColor":"#085041","primaryBorderColor":"#1D9E75","lineColor":"#5F5E5A","secondaryColor":"#E6F1FB","tertiaryColor":"#FAEEDA"}}}%%',
    '  flowchart LR',
    '    classDef persona  fill:#E1F5EE,stroke:#1D9E75,color:#085041,stroke-width:1.5px',
    '    classDef input    fill:#E1F5EE,stroke:#1D9E75,color:#085041,stroke-width:1.5px',
    '    classDef default  fill:#E6F1FB,stroke:#378ADD,color:#0C447C,stroke-width:1.5px',
    '    classDef output   fill:#EAF3DE,stroke:#639922,color:#27500A,stroke-width:1.5px',
    '    classDef store    fill:#F1EFE8,stroke:#888780,color:#444441,stroke-width:1px',
    '    Actor(["{{subject}}"])',
    '    DB[("flow_nodes\\nflow_edges\\nJSONB")]',
    '    subgraph P1["S01–S02 · Context Packaging"]',
    '      n-trigger["S01 · n-trigger\\nTrigger / Input"]',
    '      n-pack["S02 · n-pack\\npackContext()"]',
    '      n-trigger -->|signal| n-pack',
    '    end',
    '    subgraph P2["S03–S04 · Generate + Validate"]',
    '      n-process["S03 · n-process\\ngenerateArtifact()"]',
    '      n-validate["S04 · n-validate\\nvalidateArtifact()"]',
    '      n-process -->|md| n-validate',
    '      n-validate -.->|"@flag:correction\\n≤ 3×"| n-process',
    '    end',
    '    subgraph P3["S05 · Deliver + Persist"]',
    '      n-deliver["S05 · n-deliver\\ndeliverArtifact()"]',
    '    end',
    '    Actor      -->|selects scope · types request| n-trigger',
    '    n-pack     -->|context|                       n-process',
    '    n-validate -->|valid_md|                      n-deliver',
    '    n-deliver  -->|upsert|                        DB',
    '    DB         -.->|reload · rehydrate|           n-trigger',
    '    class Actor persona',
    '    class n-trigger input',
    '    class n-pack,n-process,n-validate default',
    '    class n-deliver output',
    '    class DB store',
    '    click n-trigger  "#pipeline" "S01 · trigger / input"',
    '    click n-pack     "#pipeline" "S02 · context pack"',
    '    click n-process  "#pipeline" "S03 · generate / process"',
    '    click n-validate "#pipeline" "S04 · review / validate"',
    '    click n-deliver  "#pipeline" "S05 · deliver / persist"',
    ...buildFlowDiagramsBlock(args.profile, product, artifact),
    'response:',
    '  key: response',
    '  type: object',
    '  value:',
    `    status: ${JSON.stringify(buildResponseStatus(args.assistantText))}`,
    `    renderer: ${JSON.stringify(renderer)}`,
    `    intent: ${JSON.stringify(sanitizeRequestIntent(args.profile.intent, 320) || 'Prompt unavailable.')}`,
    `    named_terms: ${JSON.stringify(args.profile.namedTerms)}`,
    `    requested_sections: ${JSON.stringify(requiredSections)}`,
    ...typedBlockScalarEnvelopeLines('    ', 'markdown_body', 'markdown', responseMarkdownLines),
    'flow:',
    '  direction:  {key: direction,  type: string,  value: LR}',
    '  edgeType:   {key: edgeType,   type: string,  value: smoothstep}',
    '  snapToGrid: {key: snapToGrid, type: boolean, value: true}',
    '  computed:   {key: computed,   type: boolean, value: true}',
    '  nodes:',
    '    - id:            {key: id,            type: string,   value: "n-trigger"}',
    '      type:          {key: type,          type: string,   value: "input"}',
    '      label:         {key: label,         type: string,   value: "S01 · Trigger / Input"}',
    '      phase:         {key: phase,         type: string,   value: "emit"}',
    '      actor:         {key: actor,         type: array,    value: ["{{subject}}","system"]}',
    '      handles:       {key: handles,       type: object,   value: {source: [signal]}}',
    `      data:          {key: data,          type: object,   value: {objective: "{{objective}}", artifact: "{{artifact}}", request_scope: ${JSON.stringify(contextSummary || domain)}}}`,
    '      applies_rules: {key: applies_rules, type: array,    value: []}',
    '      db_writes:     {key: db_writes,     type: string,   value: "flow_nodes"}',
    '      retry_arc:     {key: retry_arc,     type: string,   value: "—"}',
    '      confidence:    {key: confidence,    type: string,   value: "high"}',
    '      status:        {key: status,        type: string,   value: "TBD"}',
    '      kanban:        {key: kanban,        type: string,   value: "TBD"}',
    ...typedBlockScalarEnvelopeLines('      ', 'compute', 'function', [
      '(inputs) => ({',
      '  signal: {',
      '    scope:   inputs.__selected_scope  ?? null,',
      '    fm:      inputs.__frontmatter     ?? {},',
      '    summary: inputs.__context_summary ?? ""',
      '  }',
      '})',
    ]),
    '    - id:            {key: id,            type: string,   value: "n-pack"}',
    '      type:          {key: type,          type: string,   value: "default"}',
    '      label:         {key: label,         type: string,   value: "S02 · packContext()"}',
    '      phase:         {key: phase,         type: string,   value: "pack"}',
    '      actor:         {key: actor,         type: array,    value: ["system"]}',
    '      handles:       {key: handles,       type: object,   value: {target: [signal], source: [context]}}',
    `      data:          {key: data,          type: object,   value: {required_sections: ${JSON.stringify(requiredSections)}, named_terms: ${JSON.stringify(args.profile.namedTerms)}, request_scope: ${JSON.stringify(contextSummary || domain)}}}`,
    '      applies_rules: {key: applies_rules, type: array,    value: []}',
    '      db_writes:     {key: db_writes,     type: string,   value: "flow_nodes"}',
    '      retry_arc:     {key: retry_arc,     type: string,   value: "—"}',
    '      confidence:    {key: confidence,    type: string,   value: "high"}',
    '      status:        {key: status,        type: string,   value: "TBD"}',
    '      kanban:        {key: kanban,        type: string,   value: "TBD"}',
    ...typedBlockScalarEnvelopeLines('      ', 'compute', 'function', [
      '(inputs) => ({',
      '  context: inputs.signal ? {',
      '    selected_scope:  inputs.signal.scope,',
      '    frontmatter:     inputs.signal.fm,',
      '    context_summary: inputs.signal.summary',
      '  } : null',
      '})',
    ]),
    '    - id:            {key: id,            type: string,   value: "n-process"}',
    '      type:          {key: type,          type: string,   value: "default"}',
    '      label:         {key: label,         type: string,   value: "S03 · generateArtifact()"}',
    '      phase:         {key: phase,         type: string,   value: "generate"}',
    '      actor:         {key: actor,         type: array,    value: ["{{subject}}","AI"]}',
    '      handles:       {key: handles,       type: object,   value: {target: [context, correction], source: [md]}}',
    `      data:          {key: data,          type: object,   value: {model: "{{ai_model}}", temperature: 0.3, max_tokens: 1000, request_scope: ${JSON.stringify(contextSummary || domain)}, objective_focus: ${JSON.stringify(buildObjectiveSummary(args.profile) || objective)}}}`,
    '      applies_rules: {key: applies_rules, type: array,    value: ["V-05"]}',
    '      db_writes:     {key: db_writes,     type: string,   value: "flow_nodes"}',
    '      retry_arc:     {key: retry_arc,     type: string,   value: "source"}',
    '      confidence:    {key: confidence,    type: string,   value: "high"}',
    '      status:        {key: status,        type: string,   value: "TBD"}',
    '      kanban:        {key: kanban,        type: string,   value: "TBD"}',
    ...typedBlockScalarEnvelopeLines('      ', 'compute', 'function', [
      'async (inputs) => ({',
      '  md: inputs.context',
      '    ? await callAnthropicAPI({',
      '        ...inputs.context,',
      '        correction: inputs.correction ?? null',
      '      })',
      '    : null',
      '})',
    ]),
    '    - id:            {key: id,            type: string,   value: "n-validate"}',
    '      type:          {key: type,          type: string,   value: "default"}',
    '      label:         {key: label,         type: string,   value: "S04 · validateArtifact()"}',
    '      phase:         {key: phase,         type: string,   value: "validate"}',
    '      actor:         {key: actor,         type: array,    value: ["system"]}',
    '      handles:       {key: handles,       type: object,   value: {target: [md], source: [valid_md, correction]}}',
    `      data:          {key: data,          type: object,   value: {rules: ["V-01","V-02","V-03","V-04","V-05","V-06","V-07"], max_retry: 3, required_sections: ${JSON.stringify(requiredSections)}, coverage_terms: ${JSON.stringify(validationFocus)}}}`,
    '      applies_rules: {key: applies_rules, type: array,    value: ["V-01","V-02","V-03","V-04","V-05","V-06","V-07"]}',
    '      db_writes:     {key: db_writes,     type: string,   value: "flow_nodes"}',
    '      retry_arc:     {key: retry_arc,     type: string,   value: "target"}',
    '      confidence:    {key: confidence,    type: string,   value: "high"}',
    '      status:        {key: status,        type: string,   value: "TBD"}',
    '      kanban:        {key: kanban,        type: string,   value: "TBD"}',
    ...typedBlockScalarEnvelopeLines('      ', 'compute', 'function', [
      '(inputs) => {',
      '  const result = runValidation(inputs.md);',
      '  return {',
      '    valid_md:   result.ok ? inputs.md    : null,',
      '    correction: result.ok ? null : result.errors',
      '  };',
      '}',
    ]),
    '    - id:            {key: id,            type: string,   value: "n-deliver"}',
    '      type:          {key: type,          type: string,   value: "output"}',
    '      label:         {key: label,         type: string,   value: "S05 · deliverArtifact()"}',
    '      phase:         {key: phase,         type: string,   value: "deliver"}',
    '      actor:         {key: actor,         type: array,    value: ["system"]}',
    '      handles:       {key: handles,       type: object,   value: {target: [valid_md]}}',
    '      data:          {key: data,          type: object,   value: {stores: ["flow_nodes","flow_edges"], triggers: "output re-render"}}',
    '      applies_rules: {key: applies_rules, type: array,    value: []}',
    '      db_writes:     {key: db_writes,     type: array,    value: ["flow_nodes","flow_edges"]}',
    '      retry_arc:     {key: retry_arc,     type: string,   value: "—"}',
    '      confidence:    {key: confidence,    type: string,   value: "high"}',
    '      status:        {key: status,        type: string,   value: "TBD"}',
    '      kanban:        {key: kanban,        type: string,   value: "TBD"}',
    ...typedBlockScalarEnvelopeLines('      ', 'compute', 'function', [
      '(inputs) => ({',
      '  rendered: inputs.valid_md',
      '    ? deliverArtifact(inputs.valid_md)',
      '    : null',
      '})',
    ]),
    '  subgraphs:',
    '    - {id: sg-p1, kind: subgraph, label: "Context Packaging", memberNodeIds: [n-trigger, n-pack], parentId: null}',
    '    - {id: sg-p2, kind: subgraph, label: "Generate + Validate", memberNodeIds: [n-process, n-validate], parentId: null}',
    '    - {id: sg-p3, kind: subgraph, label: "Deliver + Persist", memberNodeIds: [n-deliver], parentId: null}',
    '  edges:',
    '    - {id: e1, source: n-trigger,  sourceHandle: signal,     target: n-pack,     targetHandle: signal,     label: "signal",             animated: true}',
    '    - {id: e2, source: n-pack,     sourceHandle: context,    target: n-process,  targetHandle: context,    label: "context",            animated: true}',
    '    - {id: e3, source: n-process,  sourceHandle: md,         target: n-validate, targetHandle: md,         label: "md",                 animated: true}',
    '    - {id: e4, source: n-validate, sourceHandle: valid_md,   target: n-deliver,  targetHandle: valid_md,   label: "validated artifact", animated: true}',
    '    - {id: e5, source: n-validate, sourceHandle: correction, target: n-process,  targetHandle: correction, label: "@flag:correction",   animated: true}',
  ].join('\n')
}
