type BaseFallbackArgs = {
  timestampMs: number
  fileName: string
  requestText: string
}

const pad2 = (n: number): string => String(n).padStart(2, '0')

const formatIsoDateOnly = (timestampMs: number): string => {
  const d = new Date(Number.isFinite(timestampMs) ? timestampMs : Date.now())
  const yyyy = String(d.getFullYear())
  const mm = pad2(d.getMonth() + 1)
  const dd = pad2(d.getDate())
  return `${yyyy}-${mm}-${dd}`
}

const toGraphSlugFromFilename = (fileName: string): string => {
  const base = String(fileName || '').replace(/\.md$/i, '').trim()
  const normalized = base
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
  return normalized || 'kgc-pipeline'
}

const json = (value: string): string => JSON.stringify(String(value || ''))

const sanitizeOneLine = (raw: string, maxChars = 220): string => {
  const cleaned = String(raw || '').replace(/\r\n/g, '\n').replace(/\s+/g, ' ').trim()
  if (!cleaned) return 'Regenerate assistant output using strict base-template KGC contract.'
  return cleaned.slice(0, maxChars)
}

export const buildDeterministicBaseTemplateKgcTurn = (args: BaseFallbackArgs): string => {
  const date = formatIsoDateOnly(args.timestampMs)
  const graphId = `md:${toGraphSlugFromFilename(args.fileName)}-pipeline`
  const request = sanitizeOneLine(args.requestText)
  return [
    '---',
    `title: ${json('Knowledge Graph Canvas · AI Pipeline — Chat Response')}`,
    `graphId: ${json(graphId)}`,
    `doc_type: ${json('Chat Response')}`,
    `date: ${json(date)}`,
    `ai_model: ${json('claude-sonnet-4-20250514')}`,
    'lang: en-US',
    '$schema: "kgc-pipeline/v1"',
    'spec:',
    '  format: kgc-pipeline',
    '  version: "1.0.0"',
    '  parser: yaml-frontmatter',
    '  execution: computing-flow',
    '  topology: DAG-with-feedback',
    '  ssot_surfaces: [pipeline, flow.nodes, flow.edges, mermaid, runner]',
    'runner:',
    '  entry: R01',
    '  exit: R06',
    '  steps:',
    '    - seq: R01',
    '      action: ingest',
    '      input: "raw file bytes"',
    '      output: "parsed YAML object"',
    '      description: "Parse frontmatter and validate schema."',
    '    - seq: R02',
    '      action: resolve',
    '      input: "parsed YAML object"',
    '      output: "resolved variables"',
    '      description: "Resolve variables with Tier B sentinel exception."',
    '    - seq: R03',
    '      action: build-graph',
    '      input: "resolved YAML"',
    '      output: "graph nodes and edges"',
    '      description: "Cross-validate SSOT surfaces."',
    '    - seq: R04',
    '      action: compile-compute',
    '      input: "graph"',
    '      output: "compiled graph"',
    '      description: "Compile typed compute mappings with purity guard."',
    '    - seq: R05',
    '      action: traverse',
    '      input: "compiled graph"',
    '      output: "executed graph"',
    '      description: "Execute S01-S05 with bounded feedback."',
    '    - seq: R06',
    '      action: render',
    '      input: "executed graph and body"',
    '      output: "rendered knowledge graph canvas"',
    '      description: "Render diagram and pipeline tables."',
    'links:',
    '  yaml_anchor: "#computing-flow-definition"',
    '  body_anchor: "#flow-graph"',
    `  self_ref: ${json(args.fileName)}`,
    'canvas:',
    '  auto_layout: true',
    '  layout_algo: dagre-LR',
    '  snap_to_grid: true',
    '  grid_size: 20',
    '  minimap: true',
    '  controls: true',
    '  node_defaults:',
    '    width: 220',
    '    height: 80',
    '  edge_defaults:',
    '    type: smoothstep',
    '    animated: true',
    'graph_meta:',
    '  node_count: 5',
    '  edge_count: 5',
    '  phase_count: 3',
    '  entry_node: n-trigger',
    '  exit_node: n-deliver',
    '  phases:',
    '    - {id: P1, label: "Context Packaging", seq_range: "S01-S02", nodes: [n-trigger, n-pack]}',
    '    - {id: P2, label: "Generate + Validate", seq_range: "S03-S04", nodes: [n-process, n-validate]}',
    '    - {id: P3, label: "Deliver + Persist", seq_range: "S05", nodes: [n-deliver]}',
    '  feedback_arcs:',
    '    - {edge: e5, from: n-validate, from_handle: correction, to: n-process, to_handle: correction, max_iterations: "{{runtime.maxRetry}}", on_exhausted: "@flag:validation-failed"}',
    '  forward_edges:',
    '    - {edge: e1, from: n-trigger, to: n-pack, handle: signal}',
    '    - {edge: e2, from: n-pack, to: n-process, handle: context}',
    '    - {edge: e3, from: n-process, to: n-validate, handle: md}',
    '    - {edge: e4, from: n-validate, to: n-deliver, handle: valid_md}',
    'product: "{{product}}"',
    'domain: "{{domain}}"',
    'subject: "{{subject}}"',
    'objective: "{{objective}}"',
    'artifact: "{{artifact}}"',
    'owner: "{{owner}}"',
    'version: "{{version}}"',
    'status: "{{status}}"',
    'runtime:',
    '  entry: {key: entry, type: string, value: "n-trigger"}',
    '  exit: {key: exit, type: string, value: "n-deliver"}',
    '  sandbox: {key: sandbox, type: string, value: "quickjs-emscripten"}',
    '  trace: {key: trace, type: boolean, value: true}',
    '  maxRetry: {key: maxRetry, type: number, value: 3}',
    'pipeline:',
    '  - {seq: S01, node: n-trigger, label: "trigger", actor: ["{{subject}}","system"], edge_in: "—", edge_out: signal, user_action: "scope input", sys_event: "emit signal", data_in: "—", data_out: "signal", trigger: "scope", on_fail: "@flag:waiting", kanban: TBD, confidence: high, status: TBD}',
    '  - {seq: S02, node: n-pack, label: "pack", actor: ["system"], edge_in: signal, edge_out: context, user_action: "—", sys_event: "pack context", data_in: "signal", data_out: "context", trigger: "signal", on_fail: "null context", kanban: TBD, confidence: high, status: TBD}',
    '  - {seq: S03, node: n-process, label: "process", actor: ["{{subject}}","AI"], edge_in: "context + correction|null", edge_out: md, user_action: "observe stream", sys_event: "generate artifact", data_in: "context", data_out: "md", trigger: "context", on_fail: "null md", kanban: TBD, confidence: high, status: TBD}',
    '  - {seq: S04, node: n-validate, label: "validate", actor: ["system"], edge_in: md, edge_out: "valid_md | correction", user_action: "observe validation", sys_event: "run V-01..V-07", data_in: "md", data_out: "valid_md or correction", trigger: "md", on_fail: "retry <= {{runtime.maxRetry}}", kanban: TBD, confidence: high, status: TBD}',
    '  - {seq: S05, node: n-deliver, label: "deliver", actor: ["system"], edge_in: valid_md, edge_out: "—", user_action: "consume output", sys_event: "persist and render", data_in: "valid_md", data_out: "rendered + persisted", trigger: "valid_md", on_fail: "short-circuit", kanban: TBD, confidence: high, status: TBD}',
    'mermaid: |',
    '  flowchart LR',
    '    Actor(["{{subject}}"])',
    '    DB[("flow_nodes\\nflow_edges\\nJSONB")]',
    '    subgraph P1["S01-S02 · Context Packaging"]',
    '      n-trigger["S01 · n-trigger"]',
    '      n-pack["S02 · n-pack"]',
    '      n-trigger -->|signal| n-pack',
    '    end',
    '    subgraph P2["S03-S04 · Generate + Validate"]',
    '      n-process["S03 · n-process"]',
    '      n-validate["S04 · n-validate"]',
    '      n-process -->|md| n-validate',
    '      n-validate -.->|"@flag:correction\\n≤ 3×"| n-process',
    '    end',
    '    subgraph P3["S05 · Deliver + Persist"]',
    '      n-deliver["S05 · n-deliver"]',
    '    end',
    '    Actor -->|request| n-trigger',
    '    n-pack -->|context| n-process',
    '    n-validate -->|valid_md| n-deliver',
    '    n-deliver -->|upsert| DB',
    '    DB -.->|reload · rehydrate| n-trigger',
    'flow:',
    '  direction: {key: direction, type: string, value: LR}',
    '  edgeType: {key: edgeType, type: string, value: smoothstep}',
    '  snapToGrid: {key: snapToGrid, type: boolean, value: true}',
    '  computed: {key: computed, type: boolean, value: true}',
    '  nodes:',
    '    - id: {key: id, type: string, value: "n-trigger"}',
    '      type: {key: type, type: string, value: "input"}',
    '      label: {key: label, type: string, value: "S01 · Trigger"}',
    '      phase: {key: phase, type: string, value: "emit"}',
    '      actor: {key: actor, type: array, value: ["{{subject}}","system"]}',
    '      handles: {key: handles, type: object, value: {source: [signal]}}',
    '      data: {key: data, type: object, value: {objective: "{{objective}}", artifact: "{{artifact}}"}}',
    '    - id: {key: id, type: string, value: "n-pack"}',
    '      type: {key: type, type: string, value: "default"}',
    '      label: {key: label, type: string, value: "S02 · packContext()"}',
    '      phase: {key: phase, type: string, value: "pack"}',
    '      actor: {key: actor, type: array, value: ["system"]}',
    '      handles: {key: handles, type: object, value: {target: [signal], source: [context]}}',
    '      data: {key: data, type: object, value: {}}',
    '    - id: {key: id, type: string, value: "n-process"}',
    '      type: {key: type, type: string, value: "default"}',
    '      label: {key: label, type: string, value: "S03 · generateArtifact()"}',
    '      phase: {key: phase, type: string, value: "generate"}',
    '      actor: {key: actor, type: array, value: ["{{subject}}","AI"]}',
    '      handles: {key: handles, type: object, value: {target: [context, correction], source: [md]}}',
    '      data: {key: data, type: object, value: {model: "claude-sonnet-4-20250514"}}',
    '    - id: {key: id, type: string, value: "n-validate"}',
    '      type: {key: type, type: string, value: "default"}',
    '      label: {key: label, type: string, value: "S04 · validateArtifact()"}',
    '      phase: {key: phase, type: string, value: "validate"}',
    '      actor: {key: actor, type: array, value: ["system"]}',
    '      handles: {key: handles, type: object, value: {target: [md], source: [valid_md, correction]}}',
    '      data: {key: data, type: object, value: {rules: ["V-01","V-02","V-03","V-04","V-05","V-06","V-07"], max_retry: 3}}',
    '    - id: {key: id, type: string, value: "n-deliver"}',
    '      type: {key: type, type: string, value: "output"}',
    '      label: {key: label, type: string, value: "S05 · deliverArtifact()"}',
    '      phase: {key: phase, type: string, value: "deliver"}',
    '      actor: {key: actor, type: array, value: ["system"]}',
    '      handles: {key: handles, type: object, value: {target: [valid_md]}}',
    '      data: {key: data, type: object, value: {stores: ["flow_nodes","flow_edges"]}}',
    '  edges:',
    '    - {id: e1, source: n-trigger, sourceHandle: signal, target: n-pack, targetHandle: signal, label: "signal", animated: true}',
    '    - {id: e2, source: n-pack, sourceHandle: context, target: n-process, targetHandle: context, label: "context", animated: true}',
    '    - {id: e3, source: n-process, sourceHandle: md, target: n-validate, targetHandle: md, label: "md", animated: true}',
    '    - {id: e4, source: n-validate, sourceHandle: valid_md, target: n-deliver, targetHandle: valid_md, label: "validated artifact", animated: true}',
    '    - {id: e5, source: n-validate, sourceHandle: correction, target: n-process, targetHandle: correction, label: "@flag:correction", animated: true}',
    '---',
    '',
    '# Knowledge Graph Canvas · AI Pipeline',
    '',
    '## Chat Response',
    '',
    `\`bg#E1F5EE:version {{version}}\` · \`bg#FAEEDA:status {{status}}\` · owner \`{{owner}}\` · ${date}`,
    '',
    '## Computing Flow Definition',
    'This section documents the machine-readable YAML contract used to run the chat pipeline. The document stays self-runnable and graph-complete, and all SSOT surfaces remain synchronized to avoid mismatch at runtime execution.',
    '',
    '## Flow Graph',
    'The flow graph is declared in frontmatter `mermaid:` and rendered as a directed graph with one bounded feedback arc. It keeps canonical generic node ids and stable edge handles for deterministic traversal and persistence.',
    '',
    '## Pipeline',
    `The request scope is: ${request}. The ordered pipeline follows S01 through S05 with strict validation and bounded correction retries so malformed markdown does not persist into workspace storage.`,
    '',
    '## PRD — Product Requirements',
    'The pipeline must package context, generate markdown, validate against V-01 through V-07, and persist only accepted outputs. Non-goals include undefined placeholders, weak schema linkage, and any renderer-local fallback contracts.',
    '',
    '## TAD — Technical Architecture',
    'Architecture uses one frontmatter SSOT with typed mappings for runtime, pipeline, flow nodes, and edges. The parser resolves variables, validates linkage, compiles compute safely, traverses graph order, and renders consistent canvas/table projections.',
    '',
    '## Open Questions',
    '- Should retry counts stay global or allow node-level overrides?',
    '- Should compute compilation cache by node id across reloads?',
    '- Should additional domain-specific rules extend from V-08 onward?',
    '',
    '## Customization Guide',
    'Replace Tier B placeholders in frontmatter (`product`, `domain`, `subject`, `objective`, `artifact`, `owner`, `version`, `status`), then extend goals, stories, rules, and compute behavior while preserving SSOT consistency and canonical ids.',
    '',
  ].join('\n')
}
