import { mkdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { SG_POSTAL_DISTRICT_RANGES, SG_SPECIAL_POSTCODE_ZONES } from 'grph-shared/geospatial/sgpAdministrativeAreas'

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = path.resolve(SCRIPT_DIR, '../../..')
const OUTPUT_PATH = path.join(
  REPO_ROOT,
  'docs',
  'documents',
  'knowgrph-grabmaps-sgp-administrative-areas-reference.md',
)

function escapeMarkdownCell(value: unknown): string {
  return String(value ?? '')
    .replace(/\r?\n/g, ' ')
    .replace(/\|/g, '\\|')
    .trim()
}

function buildDistrictRow(row: { district: string; sectorMin: number; sectorMax: number; label: string }): string {
  const range = row.sectorMin === row.sectorMax
    ? `${String(row.sectorMin).padStart(2, '0')}xxxx`
    : `${String(row.sectorMin).padStart(2, '0')}xxxx–${String(row.sectorMax).padStart(2, '0')}xxxx`
  const cells = [row.district, range, row.label].map(escapeMarkdownCell)
  return `| ${cells.join(' | ')} |`
}

function buildZoneRow(row: { prefix3: string; label: string }): string {
  const cells = [row.prefix3, row.label].map(escapeMarkdownCell)
  return `| ${cells.join(' | ')} |`
}

function buildMarkdown(): string {
  const districts = [...SG_POSTAL_DISTRICT_RANGES].sort((a, b) => a.district.localeCompare(b.district))
  const zones = [...SG_SPECIAL_POSTCODE_ZONES].sort((a, b) => a.prefix3.localeCompare(b.prefix3))
  return [
    '# knowgrph - GrabMaps (SGP) Administrative Areas Reference',
    '',
    'Generated by `npm --prefix canvas run doc:generate-grabmaps-sgp-admin-areas-reference`.',
    '',
    'SSOT:',
    '- `grph-shared/src/geospatial/sgpAdministrativeAreas.ts`',
    '',
    'Scope:',
    '- This reference encodes the Singapore postal-sector → postal-district mapping used to derive administrative layers from GrabMaps POI address fields.',
    '- GrabMaps `/poi/v1/search` often returns flat address fields (for example `street`, `postcode`, `formatted_address`) instead of `administrative_areas[]`.',
    '',
    '## 1. Postal District Mapping (by postal sector prefix)',
    '',
    '| district | postcode range | planning areas (hint) |',
    '| --- | --- | --- |',
    ...districts.map(buildDistrictRow),
    '',
    '## 2. Special Postcode Zones (prefix-3)',
    '',
    '| prefix3 | area |',
    '| --- | --- |',
    ...zones.map(buildZoneRow),
    '',
  ].join('\n')
}

function main(): void {
  mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true })
  writeFileSync(OUTPUT_PATH, buildMarkdown(), 'utf8')
  process.stdout.write(`${OUTPUT_PATH}\n`)
}

main()

