import { mkdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  OPENAI_RESPONSES_API_DOC_ROWS,
  OPENAI_VALUE_TOOLTIP_BY_ROW_KEY,
  type OpenAiApiDocRow,
} from '../features/integrations/openaiResponsesSsot'

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = path.resolve(SCRIPT_DIR, '../../..')
const OUTPUT_PATH = path.join(
  REPO_ROOT,
  'docs',
  'documents',
  'knowgrph-openai-responses-api-reference.md',
)
const OPENAI_RESPONSES_DOC_URL = 'https://developers.openai.com/api/reference/resources/responses/index.md'

const OPENAI_EXTERNAL_PARAM_PATH_BY_KEY: Readonly<Record<string, string>> = {
  model: 'post /responses :: Body Parameters > model',
  input: 'post /responses :: Body Parameters > input',
  response_format: 'post /responses :: Body Parameters > text',
  temperature: 'post /responses :: Body Parameters > temperature',
  top_p: 'post /responses :: Body Parameters > top_p',
  max_output_tokens: 'post /responses :: Body Parameters > max_output_tokens',
  reasoning_effort: 'post /responses :: Body Parameters > reasoning',
  stream: 'post /responses :: Body Parameters > stream',
  frequency_penalty: 'post /responses :: Body Parameters > frequency_penalty',
  presence_penalty: 'post /responses :: Body Parameters > presence_penalty',
  logprobs: 'post /responses :: Body Parameters > logprobs',
  top_logprobs: 'post /responses :: Body Parameters > top_logprobs',
  tools: 'post /responses :: Body Parameters > tools',
  tool_choice: 'post /responses :: Body Parameters > tool_choice',
  parallel_tool_calls: 'post /responses :: Body Parameters > parallel_tool_calls',
}

function normalizeScalar(value: string | number | boolean | null | undefined): string {
  if (typeof value === 'undefined') return ''
  if (value === null) return 'null'
  const text = String(value).trim()
  if (!text) return ''
  return text === '—' ? '-' : text
}

function escapeMarkdownCell(value: string): string {
  return String(value || '')
    .replace(/\r?\n/g, ' ')
    .replace(/\|/g, '\\|')
    .trim()
}

function trimTrailingSentencePunctuation(value: string): string {
  return String(value || '').trim().replace(/[.;\s]+$/g, '')
}

function formatList(values: string[] | undefined): string {
  return (values || []).map(value => `\`${value}\``).join('; ')
}

function buildValueDescription(row: OpenAiApiDocRow): string {
  const tooltip = OPENAI_VALUE_TOOLTIP_BY_ROW_KEY[row.key] || {}
  const parts: string[] = []
  const defaultValue = typeof row.tooltipDefaultValue !== 'undefined'
    ? row.tooltipDefaultValue
    : tooltip.defaultValue
  const min = typeof row.tooltipMin !== 'undefined' ? row.tooltipMin : tooltip.min
  const max = typeof row.tooltipMax !== 'undefined' ? row.tooltipMax : tooltip.max
  const interval = typeof row.tooltipInterval !== 'undefined' ? row.tooltipInterval : tooltip.interval
  const expansionNote = row.tooltipExpansionNote || tooltip.expansionNote
  const contractionNote = row.tooltipContractionNote || tooltip.contractionNote
  const impact = row.tooltipImpact || tooltip.impact

  if (typeof defaultValue !== 'undefined') parts.push(`Default: ${normalizeScalar(defaultValue)}`)
  if (typeof min !== 'undefined') parts.push(`Min: ${normalizeScalar(min)}`)
  if (typeof max !== 'undefined') parts.push(`Max: ${normalizeScalar(max)}`)
  if (typeof interval !== 'undefined') parts.push(`Interval: ${normalizeScalar(interval)}`)
  if (expansionNote) parts.push(trimTrailingSentencePunctuation(expansionNote))
  if (contractionNote) parts.push(trimTrailingSentencePunctuation(contractionNote))
  if (impact) parts.push(`Impact: ${trimTrailingSentencePunctuation(impact)}`)
  return parts.join('; ')
}

function buildSsotCell(row: OpenAiApiDocRow): string {
  const rowKey = `openaiApi.${row.key}`
  const refs = [
    `\`canvas/src/features/integrations/openaiResponsesSsot.ts :: OPENAI_RESPONSES_API_DOC_ROWS['${rowKey}']\``,
  ]
  const externalPath = OPENAI_EXTERNAL_PARAM_PATH_BY_KEY[row.key]
  if (externalPath) refs.push(`\`${OPENAI_RESPONSES_DOC_URL} :: ${externalPath}\``)
  return refs.join('; ')
}

function buildRow(row: OpenAiApiDocRow): string {
  const cells = [
    row.key,
    row.typeLabel,
    row.value,
    row.responsibility,
    buildValueDescription(row),
    buildSsotCell(row),
    formatList(row.modules),
    formatList(row.classes),
    formatList(row.functions),
  ].map(escapeMarkdownCell)
  return `| ${cells.join(' | ')} |`
}

function buildMarkdown(): string {
  const lines = [
    '# knowgrph - OpenAI Responses API Reference (SSOT + Codebase Map)',
    '',
    'Generated by `npm run docs:openai-reference`.',
    '',
    'SSOT:',
    '- `canvas/src/features/integrations/openaiResponsesSsot.ts`',
    `- \`${OPENAI_RESPONSES_DOC_URL}\``,
    '',
    'Scope:',
    '- This static reference is intentionally limited to the OpenAI request-surface rows that knowgrph exposes in `MainPanel Integrations`, `Workflow Manager`, and the `OpenAI Text Widget`.',
    '- `provider`, `auth_mode`, `endpoint_url`, and `api_key` are knowgrph integration transport settings aligned to OpenAI Responses execution, not raw OpenAI body fields.',
    '',
    'Table columns:',
    '- `key | type | value | key-description | value-description`: curated OpenAI request-surface SSOT',
    '- `module | class | function`: where the row is anchored in the knowgrph codebase',
    '',
    '| key | type | value | key-description | value-description | ssot | module | class | function |',
    '| --- | --- | --- | --- | --- | --- | --- | --- | --- |',
    ...OPENAI_RESPONSES_API_DOC_ROWS.map(buildRow),
    '',
  ]
  return lines.join('\n')
}

function main(): void {
  mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true })
  writeFileSync(OUTPUT_PATH, buildMarkdown(), 'utf8')
  process.stdout.write(`${OUTPUT_PATH}\n`)
}

main()
