import { mkdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  BYTEPLUS_SHARED_TEXT_API_DOC_ROWS,
  BYTEPLUS_VALUE_TOOLTIP_BY_ROW_KEY,
  type BytePlusSharedTextApiDocRow,
} from '../features/integrations/byteplusChatApiSsot'

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = path.resolve(SCRIPT_DIR, '../../..')
const OUTPUT_PATH = path.join(
  REPO_ROOT,
  'docs',
  'documents',
  'knowgrph-byteplus-openark-chat-api-reference.md',
)
const RAW_SSOT_PATH = 'docs/documents/knowgrph-byteplus-openark-chat-api-reference-raw.md'

function normalizeScalar(value: string | number | boolean | null | undefined): string {
  if (typeof value === 'undefined') return ''
  if (value === null) return 'null'
  const text = String(value).trim()
  return text === '—' ? '-' : text
}

function escapeMarkdownCell(value: string): string {
  return String(value || '')
    .replace(/\r?\n/g, ' ')
    .replace(/\|/g, '\\|')
    .trim()
}

function trimTrailingSentencePunctuation(value: string): string {
  return String(value || '').trim().replace(/[.;\s]+$/g, '')
}

function formatList(values: string[] | undefined): string {
  return (values || []).map(value => `\`${value}\``).join('; ')
}

function buildValueDescription(row: BytePlusSharedTextApiDocRow): string {
  const tooltip = BYTEPLUS_VALUE_TOOLTIP_BY_ROW_KEY[row.key] || {}
  const parts: string[] = []
  const defaultValue = typeof row.tooltipDefaultValue !== 'undefined' ? row.tooltipDefaultValue : tooltip.defaultValue
  const min = typeof row.tooltipMin !== 'undefined' ? row.tooltipMin : tooltip.min
  const max = typeof row.tooltipMax !== 'undefined' ? row.tooltipMax : tooltip.max
  const interval = typeof row.tooltipInterval !== 'undefined' ? row.tooltipInterval : tooltip.interval
  const expansionNote = row.tooltipExpansionNote || tooltip.expansionNote
  const contractionNote = row.tooltipContractionNote || tooltip.contractionNote
  const impact = row.tooltipImpact || tooltip.impact

  if (typeof defaultValue !== 'undefined') parts.push(`Default: ${normalizeScalar(defaultValue)}`)
  if (typeof min !== 'undefined') parts.push(`Min: ${normalizeScalar(min)}`)
  if (typeof max !== 'undefined') parts.push(`Max: ${normalizeScalar(max)}`)
  if (typeof interval !== 'undefined') parts.push(`Interval: ${normalizeScalar(interval)}`)
  if (expansionNote) parts.push(trimTrailingSentencePunctuation(expansionNote))
  if (contractionNote) parts.push(trimTrailingSentencePunctuation(contractionNote))
  if (impact) parts.push(`Impact: ${trimTrailingSentencePunctuation(impact)}`)
  return parts.join('; ')
}

function buildSsotCell(row: BytePlusSharedTextApiDocRow): string {
  const refs = [`\`canvas/src/features/integrations/byteplusChatApiSsot.rows.ts :: byteplusApi.${row.key}\``]
  if (row.key === 'endpoint_url') refs.push(`\`${RAW_SSOT_PATH} :: Base URL by region\``)
  else if (!['provider', 'auth_mode', 'api_key'].includes(row.key)) refs.push(`\`${RAW_SSOT_PATH} :: Request parameters > Request body\``)
  return refs.join('; ')
}

function buildRow(row: BytePlusSharedTextApiDocRow): string {
  const cells = [
    row.key,
    row.typeLabel,
    row.value,
    row.responsibility,
    buildValueDescription(row),
    buildSsotCell(row),
    formatList(row.modules),
    formatList(row.classes),
    formatList(row.functions),
  ].map(escapeMarkdownCell)
  return `| ${cells.join(' | ')} |`
}

function getSortedRows(): BytePlusSharedTextApiDocRow[] {
  return [...BYTEPLUS_SHARED_TEXT_API_DOC_ROWS].sort((left, right) => left.key.localeCompare(right.key))
}

function buildMarkdown(): string {
  return [
    '# knowgrph - BytePlus OpenArk Chat API Reference (SSOT + Codebase Map)',
    '',
    'Generated by `npm run docs:byteplus-chat-reference`.',
    '',
    'SSOT:',
    '- `canvas/src/features/integrations/byteplusChatApiSsot.rows.ts`',
    `- \`${RAW_SSOT_PATH}\``,
    '',
    'Scope:',
    '- This static reference is intentionally limited to the BytePlus request-surface rows that knowgrph exposes in `MainPanel Integrations`, `Workflow Manager`, and the `BytePlus Text Widget`.',
    '- `provider`, `auth_mode`, `endpoint_url`, and `api_key` are knowgrph integration transport settings aligned to BytePlus ModelArk execution, not raw OpenArk body fields.',
    '',
    'Table columns:',
    '- `key | type | value | key-description | value-description`: curated BytePlus request-surface SSOT',
    '- `module | class | function`: where the row is anchored in the knowgrph codebase',
    '- Rows are sorted by `key` in ascending `a-z` order for static-reference scanability.',
    '',
    '| key | type | value | key-description | value-description | ssot | module | class | function |',
    '| --- | --- | --- | --- | --- | --- | --- | --- | --- |',
    ...getSortedRows().map(buildRow),
    '',
  ].join('\n')
}

function main(): void {
  mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true })
  writeFileSync(OUTPUT_PATH, buildMarkdown(), 'utf8')
  process.stdout.write(`${OUTPUT_PATH}\n`)
}

main()
