import { mkdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import {
  GRABMAPS_DOC_ROWS,
  type GrabMapsApiDocRow,
} from '../features/integrations/grabMapsSsot.rows'

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = path.resolve(SCRIPT_DIR, '../../..')
const OUTPUT_PATH = path.join(
  REPO_ROOT,
  'docs',
  'documents',
  'knowgrph-grabmaps-api-reference.md',
)
const GRABMAPS_DOCS_URL = 'https://maps.grab.com/developer/documentation'

function escapeMarkdownCell(value: unknown): string {
  return String(value ?? '')
    .replace(/\r?\n/g, ' ')
    .replace(/\|/g, '\\|')
    .trim()
}

function formatList(values: readonly string[] | undefined): string {
  return (values || []).map(value => `\`${value}\``).join('; ')
}

function buildRow(row: GrabMapsApiDocRow): string {
  const cells = [
    row.key,
    row.typeLabel,
    row.value,
    row.keyDescription,
    row.valueDescription,
    row.ssot,
    formatList(row.module),
    formatList(row.className),
    formatList(row.functionName),
  ].map(escapeMarkdownCell)
  return `| ${cells.join(' | ')} |`
}

function getSortedRows(): GrabMapsApiDocRow[] {
  return [...GRABMAPS_DOC_ROWS].sort((left, right) => left.key.localeCompare(right.key))
}

function buildMarkdown(): string {
  return [
    '# knowgrph - GrabMaps API Reference (SSOT + Codebase Map)',
    '',
    'Generated by `npm run docs:grabmaps-reference`.',
    '',
    'SSOT:',
    '- `canvas/src/features/integrations/grabMapsSsot.rows.ts`',
    `- \`${GRABMAPS_DOCS_URL}\``,
    '',
    'Scope:',
    '- This static reference is intentionally limited to the GrabMaps, Geo, and MapLibre rows that knowgrph exposes in `MainPanel Maps`, `Workflow Manager`, and the `GrabMaps Chat Discovery Widget`.',
    '- Rows are emitted from the same shared TS SSOT used by the runtime Maps panel so the static reference and app surface stay synchronized.',
    '',
    'Table columns:',
    '- `key | type | value | key-description | value-description`: curated GrabMaps request/configuration SSOT',
    '- `module | class | function`: where the row is anchored in the knowgrph codebase',
    '- Rows are sorted by `key` in ascending `a-z` order for static-reference scanability.',
    '',
    '| key | type | value | key-description | value-description | ssot | module | class | function |',
    '| --- | --- | --- | --- | --- | --- | --- | --- | --- |',
    ...getSortedRows().map(buildRow),
    '',
  ].join('\n')
}

function main(): void {
  mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true })
  writeFileSync(OUTPUT_PATH, buildMarkdown(), 'utf8')
  process.stdout.write(`${OUTPUT_PATH}\n`)
}

main()
