export const MAPS_GEO_DOC_AREA = 'Geo'
export const MAPS_MAPLIBRE_DOC_AREA = 'MapLibre'
export const MAPS_GRABMAPS_DOC_AREA = 'GrabMaps'

export type GrabMapsApiDocRow = {
  area: string
  key: string
  typeLabel: string
  value: string
  keyDescription: string
  valueDescription: string
  ssot: string
  module: string[]
  className: string[]
  functionName: string[]
  valueKey?: string
  responsibility: string
  notes?: string
  searchHints?: string[]
  tooltipDefaultValue?: string | number | boolean | null
  tooltipMin?: string | number
  tooltipMax?: string | number
  tooltipInterval?: string | number
  tooltipExpansionNote?: string
  tooltipContractionNote?: string
  tooltipImpact?: string
}

export const GRABMAPS_DOC_ROWS: ReadonlyArray<GrabMapsApiDocRow> = [
  {
    area: MAPS_GRABMAPS_DOC_AREA,
    key: 'grabmaps.docs_url',
    typeLabel: 'url',
    value: 'https://maps.grab.com/developer/documentation',
    keyDescription: 'Reference locator -> point operators to the official GrabMaps developer portal -> keep builder, search, routing, and MCP interpretation anchored to the vendor source.',
    valueDescription: 'Default: https://maps.grab.com/developer/documentation; Opening the vendor docs expands API context; staying in knowgrph narrows focus to the curated Maps surface.',
    ssot: 'https://maps.grab.com/developer/documentation',
    module: ['docs/documents/knowgrph-grabmaps-api-reference.md', 'canvas/src/features/panels/views/SettingsView.tsx'],
    className: ['SettingsView'],
    functionName: ['SettingsView'],
    responsibility: 'Official GrabMaps developer reference URL used as the upstream API/documentation SSOT.',
    searchHints: ['grabmaps docs developer portal reference'],
  },
  {
    area: MAPS_GRABMAPS_DOC_AREA,
    key: 'grabmaps.auth_mode',
    typeLabel: 'enum',
    value: 'Integration setting. byok | serverManaged.',
    keyDescription: 'Auth router -> choose whether knowgrph or the caller supplies credentials -> keep proxy-backed style, search, and directions requests on one credential policy.',
    valueDescription: 'Default: byok; Options: byok | serverManaged; BYOK expands caller-owned authorization; server-managed narrows auth handling to the shared backend path.',
    ssot: 'https://maps.grab.com/developer/documentation/ui-library-config',
    module: ['canvas/src/features/settings/registry-ui.grabmaps.ts', 'canvas/src/features/panels/views/useSettingsView.ts'],
    className: ['SettingsRegistryItem', 'SettingsView'],
    functionName: ['setGrabMapsAuthMode', 'checkGrabMapsHealth'],
    valueKey: 'maps.grabmaps.authMode',
    responsibility: 'Selects the credential flow used for GrabMaps proxy-backed requests.',
    searchHints: ['grabmaps auth mode byok server managed'],
    tooltipDefaultValue: 'byok',
    tooltipExpansionNote: 'BYOK expands per-user credential control.',
    tooltipContractionNote: 'Server-managed narrows credential handling to the shared backend path.',
  },
  {
    area: MAPS_GRABMAPS_DOC_AREA,
    key: 'grabmaps.api_key',
    typeLabel: 'string',
    value: 'Integration setting. Required when auth_mode=byok.',
    keyDescription: 'Credential holder -> attach the caller-managed GrabMaps secret -> authorize proxied style, places, and routes requests without hardcoding tokens in feature-local code.',
    valueDescription: 'Default: empty; Supplying a valid BYOK key expands direct caller-managed access; leaving it empty narrows execution to server-managed auth only.',
    ssot: 'https://maps.grab.com/developer/documentation/ui-library-config',
    module: ['canvas/src/features/settings/registry-ui.grabmaps.ts', 'canvas/src/features/toolbar/GrabMapsDiscoveryWidgetSection.tsx'],
    className: ['SettingsRegistryItem', 'GrabMapsDiscoveryWidgetSection'],
    functionName: ['setGrabMapsApiKey', 'buildGrabMapsAuthHeader'],
    valueKey: 'maps.grabmaps.apiKey',
    responsibility: 'Stores the sanitized GrabMaps API key used for BYOK proxy-backed requests.',
    searchHints: ['grabmaps api key bearer byok authorization'],
    tooltipDefaultValue: '',
    tooltipExpansionNote: 'A valid key expands direct caller-managed GrabMaps execution.',
    tooltipContractionNote: 'No key narrows execution to server-managed credentials.',
    notes: 'Bearer prefixes are normalized before proxy use.',
  },
  {
    area: MAPS_GRABMAPS_DOC_AREA,
    key: 'grabmaps.basemap.style_url',
    typeLabel: 'string',
    value: 'Integration setting. Default https://maps.grab.com/api/style.json.',
    keyDescription: 'Basemap resolver -> pin the shared GrabMaps style.json URL -> keep the Geo panel, health checks, and preset bootstrap on one style endpoint SSOT.',
    valueDescription: 'Default: https://maps.grab.com/api/style.json; Pinning a style URL expands reproducible basemap output; changing it narrows compatibility with the shared GrabMaps preset and proxy pipeline.',
    ssot: 'https://maps.grab.com/developer/documentation/initializing-map',
    module: ['canvas/src/features/settings/registry-ui.grabmaps.ts', 'canvas/src/features/panels/views/useSettingsView.ts', 'gympgrph/src/features/geospatial/basemapStyle.ts'],
    className: ['SettingsRegistryItem', 'SettingsView'],
    functionName: ['setGrabMapsBasemapStyleUrl', 'checkGrabMapsHealth', 'readPreferredGrabMapsStyleUrl'],
    valueKey: 'maps.grabmaps.basemap.styleUrl',
    responsibility: 'Stores the preferred GrabMaps style.json URL used by the shared basemap preset.',
    searchHints: ['style json basemap maplibre preset health'],
    tooltipDefaultValue: 'https://maps.grab.com/api/style.json',
    tooltipExpansionNote: 'A pinned style expands reproducible visual output across sessions.',
    tooltipContractionNote: 'An invalid style narrows compatibility with the shared GrabMaps preset.',
  },
  {
    area: MAPS_GRABMAPS_DOC_AREA,
    key: 'grabmaps.attribution',
    typeLabel: 'string',
    value: '© Grab | © OpenStreetMap contributors',
    keyDescription: 'Renderer attribution -> surface the required provider credits -> keep GrabMaps tiles compliant when rendered inside knowgrph maps.',
    valueDescription: 'Default: © Grab | © OpenStreetMap contributors; Showing attribution expands compliance; omitting it narrows correctness for production map rendering.',
    ssot: 'https://maps.grab.com/developer/documentation/ui-library-config',
    module: ['grph-shared/src/geospatial/grabMapsSsot.ts', 'canvas/src/features/panels/views/mapsApiDocs.ts'],
    className: ['GrabMapsSsot'],
    functionName: ['decodeGrabMapsTileTemplatePlaceholders'],
    responsibility: 'Required attribution copy for GrabMaps-backed map rendering.',
    searchHints: ['grabmaps attribution osm openstreetmap'],
  },
  {
    area: MAPS_GRABMAPS_DOC_AREA,
    key: 'grabmaps.endpoint.style_json',
    typeLabel: 'endpoint',
    value: 'GET /api/style.json',
    keyDescription: 'Style endpoint -> fetch the GrabMaps style document -> initialize MapLibre with the shared basemap stylesheet and asset references.',
    valueDescription: 'Default: GET /api/style.json; Using the style endpoint expands live GrabMaps basemap rendering; bypassing it narrows compatibility with the shared proxy/bootstrap path.',
    ssot: 'https://maps.grab.com/developer/documentation/initializing-map',
    module: ['gympgrph/src/features/geospatial/useMapLibreBasemap.ts', 'canvas/src/features/panels/views/SettingsView.tsx'],
    className: ['GeospatialHost', 'SettingsView'],
    functionName: ['normalizeGrabMapsStyleDocument', 'checkGrabMapsHealth'],
    responsibility: 'Primary style.json endpoint used by the GrabMaps preset and health checks.',
    searchHints: ['style endpoint api style json'],
  },
  {
    area: MAPS_GRABMAPS_DOC_AREA,
    key: 'grabmaps.endpoint.places.keyword_search',
    typeLabel: 'endpoint',
    value: 'GET /api/v1/maps/poi/v1/search',
    keyDescription: 'Places resolver -> run keyword-biased POI lookup -> translate natural-language place queries into candidate map results.',
    valueDescription: 'Default: GET /api/v1/maps/poi/v1/search; Calling keyword search expands place-discovery coverage; skipping it narrows discovery to nearby or reverse-geo flows only.',
    ssot: 'https://maps.grab.com/developer/documentation/searching',
    module: ['canvas/src/features/toolbar/GrabMapsDiscoveryWidgetSection.tsx', 'docs/documents/knowgrph-grabmaps-api-reference.md'],
    className: ['GrabMapsDiscoveryWidgetSection'],
    functionName: ['callGrabMapsJson', 'buildPlannerPrompt'],
    responsibility: 'Keyword place-search endpoint used by the discovery widget planner/runtime.',
    searchHints: ['places keyword search poi search'],
  },
  {
    area: MAPS_GRABMAPS_DOC_AREA,
    key: 'grabmaps.endpoint.places.nearby',
    typeLabel: 'endpoint',
    value: 'GET /api/v1/maps/place/v2/nearby',
    keyDescription: 'Nearby search runner -> query POIs around a coordinate -> support radius-based place exploration around the active anchor.',
    valueDescription: 'Default: GET /api/v1/maps/place/v2/nearby; Calling nearby search expands local POI coverage; skipping it narrows discovery to keyword-only matching.',
    ssot: 'https://maps.grab.com/developer/documentation/searching',
    module: ['canvas/src/features/toolbar/GrabMapsDiscoveryWidgetSection.tsx', 'canvas/src/features/panels/views/grabmapsMcpApiDocs.ts'],
    className: ['GrabMapsDiscoveryWidgetSection'],
    functionName: ['callGrabMapsJson', 'buildPlannerPrompt'],
    responsibility: 'Nearby places endpoint used by the discovery widget runtime and Maps docs.',
    searchHints: ['places nearby search radius poi'],
  },
  {
    area: MAPS_GRABMAPS_DOC_AREA,
    key: 'grabmaps.endpoint.places.reverse_geo',
    typeLabel: 'endpoint',
    value: 'GET /api/v1/maps/poi/v1/reverse-geo',
    keyDescription: 'Reverse geocoder -> resolve a place candidate from coordinates -> support pickup/dropoff-style location interpretation from map points.',
    valueDescription: 'Default: GET /api/v1/maps/poi/v1/reverse-geo; Reverse geo expands coordinate-to-place flows; omitting it narrows discovery to text or nearby searches.',
    ssot: 'https://maps.grab.com/developer/documentation/searching',
    module: ['canvas/src/features/toolbar/GrabMapsDiscoveryWidgetSection.tsx', 'docs/documents/knowgrph-grabmaps-api-reference.md'],
    className: ['GrabMapsDiscoveryWidgetSection'],
    functionName: ['callGrabMapsJson', 'buildPlannerPrompt'],
    responsibility: 'Reverse-geocoding endpoint used when discovery plans resolve coordinate-first lookups.',
    searchHints: ['reverse geo pickup dropoff coordinates'],
  },
  {
    area: MAPS_GRABMAPS_DOC_AREA,
    key: 'grabmaps.mcp.url',
    typeLabel: 'url',
    value: 'https://maps.grab.com/api/v1/mcp',
    keyDescription: 'MCP transport locator -> point assistants to the GrabMaps MCP server -> keep remote tool execution on the documented upstream endpoint.',
    valueDescription: 'Default: https://maps.grab.com/api/v1/mcp; Using the official MCP URL expands tool-backed assistant operations; changing it narrows compatibility with the shared remote launcher shape.',
    ssot: 'https://maps.grab.com/developer/documentation/mcp',
    module: ['canvas/src/features/settings/registry-ui.grabmaps.ts', 'canvas/src/features/panels/views/grabmapsMcpApiDocs.ts'],
    className: ['SettingsRegistryItem'],
    functionName: ['localJsonSetting'],
    responsibility: 'Official GrabMaps MCP transport URL referenced by the shared remote launcher defaults.',
    searchHints: ['grabmaps mcp url remote server'],
  },
  {
    area: MAPS_GRABMAPS_DOC_AREA,
    key: 'grabmaps.mcp.discovery.chat_model',
    typeLabel: 'string',
    value: 'Integration setting. Discovery planner model.',
    keyDescription: 'Planner-model selector -> choose the LLM that translates user travel intent into GrabMaps operations -> keep the Props Panel discovery widget and MainPanel Maps defaults on one planning model SSOT.',
    valueDescription: 'Default: gpt-5.4-nano; Options: gpt-5.4-nano; Switching models expands planning behavior only when the curated list grows; keeping one model narrows drift across widget and Maps surfaces.',
    ssot: 'https://maps.grab.com/developer/documentation/mcp',
    module: ['canvas/src/features/settings/registry-ui.grabmaps.ts', 'canvas/src/features/toolbar/GrabMapsDiscoveryWidgetSection.tsx', 'canvas/src/features/flow-editor-manager/grabMapsDiscoveryWidget.ts'],
    className: ['SettingsRegistryItem', 'GrabMapsDiscoveryWidgetSection'],
    functionName: ['readGrabMapsDiscoverySettingsValues', 'planOperations', 'buildGrabMapsDiscoveryRegistryDraft'],
    valueKey: 'maps.grabmaps.mcp.discovery.chatModel',
    responsibility: 'Selects the chat-planner model used by the GrabMaps discovery widget.',
    searchHints: ['discovery planner model chat model'],
    tooltipDefaultValue: 'gpt-5.4-nano',
    tooltipExpansionNote: 'A shared planner model expands consistent discovery output across Maps and Props Panel flows.',
    tooltipContractionNote: 'One pinned model narrows planner drift across sessions.',
  },
  {
    area: MAPS_GRABMAPS_DOC_AREA,
    key: 'grabmaps.mcp.search_places.query',
    typeLabel: 'string',
    value: 'Integration setting. Keyword query text.',
    keyDescription: 'Keyword-search seed -> capture the default natural-language place query -> let the discovery widget reuse the same starter intent in Props Panel and MainPanel Maps.',
    valueDescription: 'Default: restaurants Marina Bay; A richer query expands place-match specificity; a shorter query narrows search intent and broadens result ambiguity.',
    ssot: 'https://maps.grab.com/developer/documentation/searching',
    module: ['canvas/src/features/settings/registry-ui.grabmaps.ts', 'canvas/src/features/toolbar/GrabMapsDiscoveryWidgetSection.tsx'],
    className: ['SettingsRegistryItem', 'GrabMapsDiscoveryWidgetSection'],
    functionName: ['buildPlannerPrompt', 'runDiscovery'],
    valueKey: 'maps.grabmaps.mcp.searchPlaces.query',
    responsibility: 'Stores the default keyword-search text reused by the discovery widget.',
    searchHints: ['search places query keyword discovery'],
    tooltipDefaultValue: 'restaurants Marina Bay',
    tooltipExpansionNote: 'More specific text expands result precision.',
    tooltipContractionNote: 'Shorter text narrows specificity and can broaden ambiguity.',
  },
  {
    area: MAPS_GRABMAPS_DOC_AREA,
    key: 'grabmaps.mcp.search_places.country',
    typeLabel: 'string',
    value: 'Integration setting. ISO alpha-3 country bias.',
    keyDescription: 'Country bias selector -> constrain keyword search to one market -> improve place relevance when the query is ambiguous across regions.',
    valueDescription: 'Default: SGP; Supplying a country expands relevance control; leaving it empty narrows geographic biasing and broadens candidate spread.',
    ssot: 'https://maps.grab.com/developer/documentation/searching',
    module: ['canvas/src/features/settings/registry-ui.grabmaps.ts', 'canvas/src/features/toolbar/GrabMapsDiscoveryWidgetSection.tsx'],
    className: ['SettingsRegistryItem', 'GrabMapsDiscoveryWidgetSection'],
    functionName: ['buildPlannerPrompt', 'runDiscovery'],
    valueKey: 'maps.grabmaps.mcp.searchPlaces.country',
    responsibility: 'Stores the optional ISO alpha-3 country bias for keyword search.',
    searchHints: ['search places country sgp'],
    tooltipDefaultValue: 'SGP',
    tooltipExpansionNote: 'A country bias expands relevance for ambiguous place names.',
    tooltipContractionNote: 'No country narrows biasing and broadens the candidate region.',
  },
  {
    area: MAPS_GRABMAPS_DOC_AREA,
    key: 'grabmaps.mcp.search_places.location',
    typeLabel: 'string',
    value: 'Integration setting. Derived from lat/lon pair.',
    keyDescription: 'Keyword-search bias point -> convert the configured lat/lon pair into a `location` hint -> keep text queries anchored near the operator’s target geography.',
    valueDescription: 'Default: 1.3521,103.8198; Moving the bias point expands relevance around a new anchor; clearing it narrows keyword search to text-only matching.',
    ssot: 'https://maps.grab.com/developer/documentation/searching',
    module: ['canvas/src/features/settings/registry-ui.grabmaps.ts', 'canvas/src/features/toolbar/GrabMapsDiscoveryWidgetSection.tsx'],
    className: ['SettingsRegistryItem', 'GrabMapsDiscoveryWidgetSection'],
    functionName: ['readLocation', 'buildPlannerPrompt', 'runDiscovery'],
    responsibility: 'Derived keyword-search location bias composed from the configured latitude and longitude.',
    searchHints: ['search places location lat lon bias'],
    tooltipDefaultValue: '1.3521,103.8198',
    tooltipExpansionNote: 'A location bias expands local relevance around the chosen anchor.',
    tooltipContractionNote: 'No location narrows keyword search to pure text interpretation.',
    notes: 'Backed by `maps.grabmaps.mcp.searchPlaces.lat` and `maps.grabmaps.mcp.searchPlaces.lon` in the settings registry.',
  },
  {
    area: MAPS_GRABMAPS_DOC_AREA,
    key: 'grabmaps.mcp.search_places.limit',
    typeLabel: 'integer',
    value: 'Integration setting. Result cap.',
    keyDescription: 'Keyword-search result cap -> bound how many places the discovery workflow keeps -> keep results inspectable in Props Panel and MainPanel Maps.',
    valueDescription: 'Default: 10; Min: 1; Max: 50; Interval: 1; Higher limits expand candidate breadth; lower limits narrow list size and reduce noise.',
    ssot: 'https://maps.grab.com/developer/documentation/searching',
    module: ['canvas/src/features/settings/registry-ui.grabmaps.ts', 'canvas/src/features/toolbar/GrabMapsDiscoveryWidgetSection.tsx'],
    className: ['SettingsRegistryItem', 'GrabMapsDiscoveryWidgetSection'],
    functionName: ['buildPlannerPrompt', 'runDiscovery'],
    valueKey: 'maps.grabmaps.mcp.searchPlaces.limit',
    responsibility: 'Caps the number of keyword-search results returned by the discovery flow.',
    searchHints: ['search places limit result cap'],
    tooltipDefaultValue: 10,
    tooltipMin: 1,
    tooltipMax: 50,
    tooltipInterval: 1,
    tooltipExpansionNote: 'A higher cap expands candidate breadth.',
    tooltipContractionNote: 'A lower cap narrows list size and reduces noise.',
  },
  {
    area: MAPS_GRABMAPS_DOC_AREA,
    key: 'grabmaps.mcp.nearby_search.location',
    typeLabel: 'string',
    value: 'Integration setting. Derived from lat/lon pair.',
    keyDescription: 'Nearby-search anchor -> convert the configured nearby lat/lon pair into the required `location` parameter -> keep radius-based discovery centered on one explicit point.',
    valueDescription: 'Default: 1.3521,103.8198; Moving the anchor expands nearby coverage around a new point; clearing it narrows nearby search until no runnable center remains.',
    ssot: 'https://maps.grab.com/developer/documentation/searching',
    module: ['canvas/src/features/settings/registry-ui.grabmaps.ts', 'canvas/src/features/toolbar/GrabMapsDiscoveryWidgetSection.tsx'],
    className: ['SettingsRegistryItem', 'GrabMapsDiscoveryWidgetSection'],
    functionName: ['readLocation', 'buildPlannerPrompt', 'runDiscovery'],
    responsibility: 'Derived nearby-search location composed from the configured nearby latitude and longitude.',
    searchHints: ['nearby search location lat lon anchor'],
    tooltipDefaultValue: '1.3521,103.8198',
    tooltipExpansionNote: 'A valid anchor expands runnable nearby-search coverage.',
    tooltipContractionNote: 'No anchor narrows nearby search until the request cannot run.',
    notes: 'Backed by `maps.grabmaps.mcp.nearbySearch.lat` and `maps.grabmaps.mcp.nearbySearch.lon` in the settings registry.',
  },
  {
    area: MAPS_GRABMAPS_DOC_AREA,
    key: 'grabmaps.mcp.nearby_search.radius',
    typeLabel: 'number',
    value: 'Integration setting. Radius in kilometres.',
    keyDescription: 'Nearby-search radius -> widen or tighten the search circle around the anchor point -> control how broad the nearby POI sweep becomes.',
    valueDescription: 'Default: 1; Min: 0; Max: 50; Interval: 1; Larger radii expand geographic coverage; smaller radii narrow results to the immediate vicinity.',
    ssot: 'https://maps.grab.com/developer/documentation/searching',
    module: ['canvas/src/features/settings/registry-ui.grabmaps.ts', 'canvas/src/features/toolbar/GrabMapsDiscoveryWidgetSection.tsx'],
    className: ['SettingsRegistryItem', 'GrabMapsDiscoveryWidgetSection'],
    functionName: ['buildPlannerPrompt', 'runDiscovery'],
    valueKey: 'maps.grabmaps.mcp.nearbySearch.radius',
    responsibility: 'Sets the nearby-search radius in kilometres.',
    searchHints: ['nearby radius km'],
    tooltipDefaultValue: 1,
    tooltipMin: 0,
    tooltipMax: 50,
    tooltipInterval: 1,
    tooltipExpansionNote: 'A larger radius expands geographic coverage.',
    tooltipContractionNote: 'A smaller radius narrows results to the immediate vicinity.',
  },
  {
    area: MAPS_GRABMAPS_DOC_AREA,
    key: 'grabmaps.mcp.nearby_search.limit',
    typeLabel: 'integer',
    value: 'Integration setting. Result cap.',
    keyDescription: 'Nearby-search result cap -> bound how many nearby POIs the workflow surfaces -> keep radius-driven results reviewable in the widget and Maps panel.',
    valueDescription: 'Default: 10; Min: 1; Max: 50; Interval: 1; Higher limits expand candidate breadth; lower limits narrow list size and reduce scan cost.',
    ssot: 'https://maps.grab.com/developer/documentation/searching',
    module: ['canvas/src/features/settings/registry-ui.grabmaps.ts', 'canvas/src/features/toolbar/GrabMapsDiscoveryWidgetSection.tsx'],
    className: ['SettingsRegistryItem', 'GrabMapsDiscoveryWidgetSection'],
    functionName: ['buildPlannerPrompt', 'runDiscovery'],
    valueKey: 'maps.grabmaps.mcp.nearbySearch.limit',
    responsibility: 'Caps the number of nearby-search results returned by the discovery flow.',
    searchHints: ['nearby limit result cap'],
    tooltipDefaultValue: 10,
    tooltipMin: 1,
    tooltipMax: 50,
    tooltipInterval: 1,
    tooltipExpansionNote: 'A higher cap expands candidate breadth.',
    tooltipContractionNote: 'A lower cap narrows list size and reduces scan cost.',
  },
  {
    area: MAPS_GRABMAPS_DOC_AREA,
    key: 'grabmaps.mcp.nearby_search.rank_by',
    typeLabel: 'enum',
    value: 'Integration setting. distance | popularity.',
    keyDescription: 'Nearby ranking selector -> choose how nearby POIs are ordered -> trade strict distance ordering against crowd/popularity bias.',
    valueDescription: 'Default: distance; Options: distance | popularity; Popularity expands crowd-weighted ranking; distance narrows sorting to physical proximity.',
    ssot: 'https://maps.grab.com/developer/documentation/searching',
    module: ['canvas/src/features/settings/registry-ui.grabmaps.ts', 'canvas/src/features/toolbar/GrabMapsDiscoveryWidgetSection.tsx'],
    className: ['SettingsRegistryItem', 'GrabMapsDiscoveryWidgetSection'],
    functionName: ['buildPlannerPrompt', 'runDiscovery'],
    valueKey: 'maps.grabmaps.mcp.nearbySearch.rankBy',
    responsibility: 'Selects whether nearby results are ranked by distance or popularity.',
    searchHints: ['nearby rank distance popularity'],
    tooltipDefaultValue: 'distance',
    tooltipExpansionNote: 'Popularity expands crowd-weighted ranking behavior.',
    tooltipContractionNote: 'Distance narrows sorting to physical proximity.',
  },
  {
    area: MAPS_GRABMAPS_DOC_AREA,
    key: 'grabmaps.mcp.nearby_search.language',
    typeLabel: 'string',
    value: 'Integration setting. Language code.',
    keyDescription: 'Localization selector -> request nearby place labels in one language -> keep nearby result text aligned with the intended operator locale.',
    valueDescription: 'Default: en; Supplying a language expands localization control; leaving it empty narrows output to the upstream default locale.',
    ssot: 'https://maps.grab.com/developer/documentation/searching',
    module: ['canvas/src/features/settings/registry-ui.grabmaps.ts', 'canvas/src/features/toolbar/GrabMapsDiscoveryWidgetSection.tsx'],
    className: ['SettingsRegistryItem', 'GrabMapsDiscoveryWidgetSection'],
    functionName: ['buildPlannerPrompt', 'runDiscovery'],
    valueKey: 'maps.grabmaps.mcp.nearbySearch.language',
    responsibility: 'Stores the language code used for nearby place names.',
    searchHints: ['nearby language locale'],
    tooltipDefaultValue: 'en',
    tooltipExpansionNote: 'A language code expands localization control.',
    tooltipContractionNote: 'No language narrows output to the upstream default locale.',
  },
  {
    area: MAPS_GRABMAPS_DOC_AREA,
    key: 'grabmaps.mcp.nearby_search.category',
    typeLabel: 'string',
    value: 'Integration setting. POI category.',
    keyDescription: 'Category filter -> constrain nearby search to one POI class -> keep nearby discovery focused on the operator’s target venue type.',
    valueDescription: 'Default: restaurant; A category expands intent precision for nearby runs; clearing it narrows filtering and broadens POI variety.',
    ssot: 'https://maps.grab.com/developer/documentation/searching',
    module: ['canvas/src/features/settings/registry-ui.grabmaps.ts', 'canvas/src/features/toolbar/GrabMapsDiscoveryWidgetSection.tsx'],
    className: ['SettingsRegistryItem', 'GrabMapsDiscoveryWidgetSection'],
    functionName: ['buildPlannerPrompt', 'runDiscovery'],
    valueKey: 'maps.grabmaps.mcp.nearbySearch.category',
    responsibility: 'Stores the category filter used for nearby-search discovery runs.',
    searchHints: ['nearby category poi class'],
    tooltipDefaultValue: 'restaurant',
    tooltipExpansionNote: 'A category filter expands intent precision for nearby runs.',
    tooltipContractionNote: 'No category narrows filtering and broadens POI variety.',
  },
  {
    area: MAPS_GEO_DOC_AREA,
    key: 'geo.panel',
    typeLabel: 'panel',
    value: 'FloatingPanel -> Geo',
    keyDescription: 'Geo-panel entrypoint -> open the floating geospatial workspace -> inspect datasets, basemaps, and route/search output on the map surface.',
    valueDescription: 'Default: FloatingPanel -> Geo; Opening Geo expands visual geospatial inspection; staying in table-only Maps view narrows interaction to config and documentation.',
    ssot: 'https://datatracker.ietf.org/doc/html/rfc7946',
    module: ['canvas/src/features/geospatial/geoIndex.ts', 'canvas/src/features/panels/views/SettingsView.tsx'],
    className: ['SettingsView'],
    functionName: ['emitSidePanelOpen'],
    responsibility: 'Floating Geo panel entrypoint for rendered map output and geospatial datasets.',
    searchHints: ['geo panel floating panel geospatial'],
  },
  {
    area: MAPS_GEO_DOC_AREA,
    key: 'geospatial.mode',
    typeLabel: 'toggle',
    value: 'Enable Geospatial Mode',
    keyDescription: 'Renderer switch -> enable the geospatial overlay host -> move the active canvas into map-oriented rendering and interaction mode.',
    valueDescription: 'Default: enabled on startup; Enabling expands map-based inspection and drops; disabling narrows the canvas back to non-geospatial rendering.',
    ssot: 'https://datatracker.ietf.org/doc/html/rfc7946',
    module: ['canvas/src/features/toolbar/hooks/useToolbarActions.ts', 'canvas/src/pages/Canvas.tsx'],
    className: ['Canvas'],
    functionName: ['setGeospatialModeEnabled'],
    responsibility: 'Primary geospatial-mode toggle that swaps the canvas into map-based rendering.',
    searchHints: ['geospatial mode toggle map renderer'],
  },
  {
    area: MAPS_GEO_DOC_AREA,
    key: 'geospatial.auto_enable_on_import',
    typeLabel: 'boolean',
    value: 'autoEnableGeospatialOnGeoImport',
    keyDescription: 'Import-mode helper -> auto-enable geospatial rendering after geo imports -> keep imported geodata visible without manual renderer switching.',
    valueDescription: 'Default: shared import setting; Turning it on expands zero-click geo import visibility; turning it off narrows import behavior to manual mode switching.',
    ssot: 'https://datatracker.ietf.org/doc/html/rfc7946',
    module: ['canvas/src/features/geospatial/autoEnable.ts', 'canvas/src/features/settings/registry-ui.import-geo.ts'],
    className: ['SettingsRegistryItem'],
    functionName: ['autoEnableGeospatialOnImport'],
    valueKey: 'autoEnableGeospatialOnGeoImport',
    responsibility: 'Auto-enables geospatial mode when GeoJSON/GeoData is imported.',
    searchHints: ['auto enable geospatial import geojson'],
    tooltipExpansionNote: 'Enabling expands zero-click visibility after geo imports.',
    tooltipContractionNote: 'Disabling narrows import behavior to manual mode switching.',
  },
  {
    area: MAPS_MAPLIBRE_DOC_AREA,
    key: 'maplibre.docs_url',
    typeLabel: 'url',
    value: 'https://maplibre.org/maplibre-gl-js/docs/',
    keyDescription: 'Renderer reference -> point operators to the MapLibre GL JS documentation -> keep style/source/event interpretation aligned with the shared MapLibre fallback path.',
    valueDescription: 'Default: https://maplibre.org/maplibre-gl-js/docs/; Opening MapLibre docs expands renderer context; staying in knowgrph narrows attention to the curated basemap pipeline.',
    ssot: 'https://maplibre.org/maplibre-gl-js/docs/',
    module: ['gympgrph/src/features/geospatial/useMapLibreBasemap.ts', 'canvas/src/features/panels/views/SettingsView.tsx'],
    className: ['SettingsView'],
    functionName: ['transformRequest'],
    responsibility: 'Reference URL for the MapLibre renderer used in standard geospatial modes.',
    searchHints: ['maplibre docs renderer reference'],
  },
  {
    area: MAPS_MAPLIBRE_DOC_AREA,
    key: 'maplibre.basemap.2d',
    typeLabel: 'map',
    value: 'MapLibre Modern 2D',
    keyDescription: 'Standard 2D basemap -> render geospatial data on the shared MapLibre mode -> provide a non-GrabMaps fallback that still uses the common viewport/runtime path.',
    valueDescription: 'Default: MapLibre Modern 2D; Selecting 2D expands neutral basemap rendering; leaving the GrabMaps preset narrows output to the GrabMaps-specific style stack.',
    ssot: 'https://maplibre.org/maplibre-gl-js/docs/',
    module: ['gympgrph/src/GeospatialHost.tsx', 'gympgrph/src/features/geospatial/basemapStyle.ts'],
    className: ['GeospatialHost'],
    functionName: ['resolveEffectiveGeospatialStyleUrl'],
    responsibility: 'Shared MapLibre 2D basemap mode for non-GrabMaps rendering.',
    searchHints: ['maplibre 2d modern basemap'],
  },
  {
    area: MAPS_MAPLIBRE_DOC_AREA,
    key: 'maplibre.basemap.3d',
    typeLabel: 'map',
    value: 'MapLibre Globe',
    keyDescription: 'Globe basemap -> render geospatial data with globe projection -> provide a shared 3D view mode when operators need planetary framing.',
    valueDescription: 'Default: MapLibre Globe; Selecting globe expands 3D framing; staying on 2D narrows projection to flat-map interaction.',
    ssot: 'https://maplibre.org/maplibre-gl-js/docs/',
    module: ['gympgrph/src/GeospatialHost.tsx', 'gympgrph/src/features/geospatial/basemapStyle.ts'],
    className: ['GeospatialHost'],
    functionName: ['resolveEffectiveGeospatialStyleUrl'],
    responsibility: 'Shared MapLibre globe mode for 3D geospatial rendering.',
    searchHints: ['maplibre globe 3d basemap'],
  },
]
