export const EXPORT_UI_LABELS = {
  copyGraphJsonLd: 'Copy Graph JSON-LD (AgenticRAG)',
  copyGraphJson: 'Copy Graph JSON',
  exportDocumentMarkdown: 'Export Document Markdown',
  exportDocumentHtml: 'Export Document HTML',
  exportDocumentPdf: 'Export Document PDF',
  exportGraphJsonLd: 'Export Graph JSON-LD (AgenticRAG)',
  exportGraphJson: 'Export Graph JSON',
  exportGraphCsvCombined: 'Export Graph CSV Combined',
  exportGraphFieldSettingsJsonLd: 'Export Graph Field Settings JSON-LD (AgenticRAG)',
  exportSettingsJsonLd: 'Export Settings JSON-LD (AgenticRAG)',
  exportHistoryJsonLd: 'Export History JSON-LD (AgenticRAG)',
  exportValidationJson: 'Export Validation JSON',
  exportValidationMarkdown: 'Export Validation Markdown',
  exportSelectionValidationJson: 'Export Selection Validation JSON',
  exportSelectionValidationMarkdown: 'Export Selection Validation Markdown',
} as const;

export const IMPORT_EXPORT_STATUS_COPY = {
  saveCancelled: 'Save cancelled',
  importCancelled: 'Import cancelled',
  invalidJsonFile: 'Invalid JSON file',
  schemaImportInvalidJson: 'Schema import failed: invalid schema JSON',
  schemaImportFailed: 'Schema import failed',
  schemaImported: (label: string | null | undefined) =>
    label && String(label).trim() ? `Schema imported from ${String(label).trim()}` : 'Schema imported',
  graphJsonLdExportNotAvailable: 'Graph JSON-LD (AgenticRAG) export not available',
  graphJsonLdExported: 'Graph JSON-LD (AgenticRAG) exported',
  graphJsonLdExportFailed: 'Graph JSON-LD (AgenticRAG) export failed',
  graphJsonExportNotAvailable: 'Graph JSON export not available',
  graphJsonExported: 'Graph JSON exported',
  graphJsonExportFailed: 'Graph JSON export failed',
  graphCsvExportNotAvailable: 'Graph CSV export not available',
  graphCsvExported: 'Graph CSV exported',
  graphCsvExportFailed: 'Graph CSV export failed',
  graphGraphMlExportNotAvailable: 'Graph GraphML export not available',
  graphGraphMlExported: 'Graph GraphML exported',
  graphGraphMlExportFailed: 'Graph GraphML export failed',
  graphCypherExportNotAvailable: 'Graph Cypher export not available',
  graphCypherExported: 'Graph Cypher exported',
  graphCypherExportFailed: 'Graph Cypher export failed',
  settingsJsonLdExported: 'Settings JSON-LD (AgenticRAG) exported',
  settingsJsonLdExportFailed: 'Settings JSON-LD (AgenticRAG) export failed',
  graphFieldSettingsJsonLdExported: 'Graph field settings JSON-LD (AgenticRAG) exported',
  graphFieldSettingsJsonLdExportFailed: 'Graph field settings JSON-LD (AgenticRAG) export failed',
  graphRagWorkflowJsonLdExported: 'GraphRAG workflow JSON-LD exported',
  graphRagWorkflowJsonLdExportFailed: 'GraphRAG workflow JSON-LD export failed',
  historyJsonLdExported: 'History JSON-LD (AgenticRAG) exported',
  historyJsonLdExportFailed: 'History JSON-LD (AgenticRAG) export failed',
  historyNoHistoryToExport: 'No history to export',
  historyImported: (length: number) => `History imported (${length})`,
  settingsImportUnrecognizedJsonLd: 'Unrecognized settings JSON-LD (AgenticRAG)',
  settingsImportNoWritableKeys: 'Settings import: no writable keys',
  settingsImportFailed: 'Settings import failed',
  settingsImportApplied: (wrote: number) => `Settings imported (${wrote} applied)`,
  settingsImportAppliedWithSkipped: (wrote: number, skipped: number) =>
    `Settings imported (${wrote} applied, ${skipped} skipped)`,
  graphFieldSettingsImportUnrecognizedJsonLd: 'Unrecognized graph field settings JSON-LD (AgenticRAG)',
  graphFieldSettingsImportNoFields: 'Graph field settings import: no fields',
  graphFieldSettingsImportFailed: 'Graph field settings import failed',
  graphFieldSettingsImported: (count: number) =>
    count > 0 ? `Graph field settings imported (${count})` : 'Graph field settings import: no fields',
  historyImportUnrecognizedJsonLd: 'Unrecognized history JSON-LD (AgenticRAG)',
  historyImportFailed: 'History import failed',
  exportAllOk: 'Exported',
  exportAllFailed: 'Export failed',
  selectionNoGraphData: 'No graph data to export',
  schemaNoSchemaToExport: 'No schema to export',
  validationNoGraphSchemaToValidate: 'No graph/schema to validate',
  copyNoGraphToCopy: 'No graph to copy',
  copyNoSchemaToCopy: 'No schema to copy',
  graphJsonLdCopiedToClipboard: 'Graph JSON-LD (AgenticRAG) copied to clipboard',
  graphJsonLdCopyFailed: 'Copy Graph JSON-LD (AgenticRAG) failed',
  graphJsonCopiedToClipboard: 'Graph JSON copied to clipboard',
  graphJsonCopyFailed: 'Copy Graph JSON failed',
  schemaJsonLdCopiedToClipboard: 'Schema JSON-LD copied to clipboard',
  schemaJsonLdCopyFailed: 'Copy Schema JSON-LD failed',
  schemaJsonCopiedToClipboard: 'Schema JSON copied to clipboard',
  schemaJsonCopyFailed: 'Copy Schema JSON failed',
  validationJsonExported: 'Validation JSON exported',
  validationJsonExportFailed: 'Validation JSON export failed',
  validationMarkdownExported: 'Validation Markdown exported',
  validationMarkdownExportFailed: 'Validation Markdown export failed',
  selectionJsonLdExported: 'Selection JSON-LD (AgenticRAG) exported',
  selectionJsonLdExportFailed: 'Selection JSON-LD (AgenticRAG) export failed',
  selectionJsonExported: 'Selection JSON exported',
  selectionJsonExportFailed: 'Selection JSON export failed',
  selectionCsvExported: 'Selection CSV exported',
  selectionCsvExportFailed: 'Selection CSV export failed',
  selectionGraphMlExported: 'Selection GraphML exported',
  selectionGraphMlExportFailed: 'Selection GraphML export failed',
  selectionCypherExported: 'Selection Cypher exported',
  selectionCypherExportFailed: 'Selection Cypher export failed',
  schemaJsonExported: 'Schema JSON exported',
  schemaJsonExportFailed: 'Schema JSON export failed',
  schemaJsonLdExportedGeneric: 'Schema JSON-LD exported',
  schemaJsonLdExportFailedGeneric: 'Schema JSON-LD export failed',
  schemaCsvExported: 'Schema CSV exported',
  schemaCsvExportFailed: 'Schema CSV export failed',
  selectionValidationJsonExported: 'Selection validation JSON exported',
  selectionValidationJsonExportFailed: 'Selection validation JSON export failed',
  selectionValidationMarkdownExported: 'Selection validation Markdown exported',
  selectionValidationMarkdownExportFailed: 'Selection validation Markdown export failed',
  svgSnapshotNoSnapshotAvailable: 'No SVG snapshot available',
  svgSnapshotExported: 'SVG snapshot exported',
  svgSnapshotExportFailed: 'SVG snapshot export failed',
  pngSnapshotNoSnapshotAvailable: 'No PNG snapshot available',
  pngSnapshotExported: 'PNG snapshot exported',
  pngSnapshotExportFailed: 'PNG snapshot export failed',
  graphRagWorkflowJsonLdInvalid: 'GraphRAG workflow JSON-LD invalid',
  graphRagWorkflowJsonLdInvalidJson: (message: string) => `GraphRAG workflow JSON-LD invalid JSON: ${message}`,
  graphRagWorkflowImportFailed: (message: string) => `GraphRAG workflow import failed: ${message}`,
  graphRagWorkflowImportEmpty: 'Import failed: file is empty',
  graphRagWorkflowImportUnrecognizedYaml: 'Unrecognized GraphRAG config YAML',
  graphRagWorkflowImported: (name: string | null | undefined) =>
    name && String(name).trim()
      ? `GraphRAG workflow config imported from ${String(name).trim()}`
      : 'GraphRAG workflow JSON-LD imported',
  graphRagWorkflowJsonInvalid: (message: string) => `GraphRAG workflow JSON invalid: ${message}`,
  importReadFileFailed: 'Import failed: unable to read file',
} as const;

export const SOURCE_FILES_FORMATS = {
  import: ['.md', '.markdown', '.mmd', '.txt', '.geojson', '.json', '.jsonld', '.csv', '.html', '.htm', '.svg', '.yaml', '.yml', '.pdf'] as const,
  importLocalText: ['.md', '.markdown', '.mmd', '.txt', '.geojson', '.json', '.jsonld', '.csv', '.html', '.htm', '.svg', '.yaml', '.yml'] as const,
  export: ['.md', '.mmd', '.txt', '.geojson', '.json', '.jsonld', '.csv', '.html', '.svg', '.yaml'] as const,
} as const

export const SOURCE_FILES_COPY = {
  supports:
    'Supports import/export: .md .markdown .mmd .txt .geojson .json .jsonld .csv .html .htm .svg .yaml .yml .pdf; URL sources: https://… (including YouTube).',
  importUrlPrompt: 'Enter a Source File URL (https://… or YouTube).',
  urlPlaceholder: 'https://… (or YouTube)',
  geoLayerEmbeddedGeojsonNotFound: 'Geo layer enable failed: no embedded GeoJSON FeatureCollection blocks found in the Markdown file',
  geoLayerEmbeddedGeojsonUploadFailed: 'Geo layer enable failed: unable to upload embedded GeoJSON to local dataset cache',
  geoLayerJsonNoPointsDerived:
    'Geo layer enable failed: no GeoJSON parsed and no record points derived (expected fields like lat/lng, latitude/longitude, geo.lat/geo.lng, location.lat/location.lng, or geometry.coordinates).',
  geoLayerMarkdownNoPoisResolved:
    'Geo layer enable failed: no itinerary POIs resolved. Enable a geospatial reference dataset (airports/cities) or add embedded GeoJSON blocks.',
  geoLayerLocalPathFetchFailed:
    'Geo layer enable failed: unable to read local file path via dev server. Use the file picker import instead.',
} as const
