import { UI_COPY } from './uiCopy'

export const MARKDOWN_DATA_VIEW_COPY = {
  titleDefault: UI_COPY.markdownDataViewTitleDefault,
  kanbanViewLabel: UI_COPY.markdownDataViewKanbanViewLabel,
  tableViewLabel: UI_COPY.markdownDataViewTableViewLabel,
  geospatialViewLabel: 'Geospatial View',
  toolbarAriaLabel: `${UI_COPY.markdownDataViewTitleDefault} toolbar`,
  headerAriaLabel: `${UI_COPY.markdownDataViewTitleDefault} header`,
  headerRowAriaLabel: `${UI_COPY.markdownDataViewTitleDefault} header row`,
  navigationAriaLabel: `${UI_COPY.markdownDataViewTitleDefault} navigation`,
  actionsAriaLabel: `${UI_COPY.markdownDataViewTitleDefault} actions`,
  workspaceAriaLabel: `${UI_COPY.markdownDataViewTitleDefault} workspace`,
  workspaceInspectorAriaLabel: `${UI_COPY.markdownDataViewTitleDefault} and inspector`,
  viewSelectAriaLabel: `${UI_COPY.markdownDataViewTitleDefault} view`,
  kanbanViewAriaLabel: `${UI_COPY.markdownDataViewTitleDefault} ${UI_COPY.markdownDataViewKanbanViewLabel}`,
  showInLabel: `Show in ${UI_COPY.markdownDataViewTitleDefault}`,
  hideInLabel: `Hide in ${UI_COPY.markdownDataViewTitleDefault}`,
  mappingLabel: `${UI_COPY.markdownDataViewTitleDefault} mapping`,
  graphRenderingToggleLabel: 'Enable graph rendering',
  newRecordLabel: UI_COPY.markdownDataViewNewRecordLabel,
  searchLabel: 'Search',
  searchPlaceholder: UI_COPY.markdownDataViewSearchPlaceholder,
  ungroupedLabel: 'Ungrouped',
  filterLabel: 'Filter',
  sortLabel: 'Sort',
  viewLabel: 'View',
  viewSettingsLabel: 'View settings',
  addViewAriaLabel: 'Add view',
  moreMenuAriaLabel: 'More menu',
  filterMenuAriaLabel: 'Filter menu',
  sortMenuAriaLabel: 'Sort menu',
  expandCardLabel: 'Expand Card',
  cardMenuLabel: 'Card menu',
  cardActionsLabel: 'Card actions',
  moveToLabel: 'Move To',
  multiTagTypeHerePlaceholder: 'Type here...',
  multiTagHelperText: 'Select tag or create one',
  multiTagCreateLabel: (name: string) => `Create "${String(name || '').trim()}"`,
} as const
