import { AGENTIC_RAG_SCHEMA_URL } from '@/lib/agenticrag'

const COLLAPSE_SECTION_TITLE = 'Collapse section'
const EXPAND_SECTION_TITLE = 'Expand section'
const CLIPBOARD_NOT_AVAILABLE = 'Clipboard not available'
const COPY_FAILED = 'Copy failed'
const MISSING_PATH = 'Missing path'
const FAILED_TO_LOAD_MARKDOWN = 'Failed to load markdown'
const EMPTY_RESPONSE = 'Empty response'
const BASELINE_LOCKED_TOAST = 'Mode switches are locked (baseline). Click the lock icon to unlock.'
const SELECTION_CLEARED_MODE_TOAST = 'Selection cleared: not available in the target mode.'

export const UI_COPY = {
  invalidJsonLabel: 'Invalid JSON',
  invalidYamlLabel: 'Invalid YAML',
  invalidJsonPrefix: 'Invalid JSON: ',
  invalidYamlPrefix: 'Invalid YAML: ',
  invalidSchemaPrefix: 'Invalid schema: ',
  invalidRulesJsonPrefix: 'Invalid rules JSON: ',
  autoPlaceholder: '(auto)',
  toolbarPrefix: 'Toolbar:',
  mainPanelPrefix: 'Main panel:',
  bottomPanelPrefix: 'Bottom panel:',
  baselineLockedToast: BASELINE_LOCKED_TOAST,
  selectionClearedOnModeSwitchToast: SELECTION_CLEARED_MODE_TOAST,
  openSettingsUiDensityIconsButton: 'Open Settings: UI Density icons',
  openSettingsUiDensityIconsButtonCompact: 'Open Settings · UI Density: Icons',
  floatingPanelMinimize: 'Minimize floating panel',
  floatingPanelRestore: 'Restore floating panel',
  floatingPanelClose: 'Close floating panel',
  floatingPanelPin: 'Pin floating panel',
  floatingPanelUnpin: 'Unpin floating panel',

  flowNodeQuickEditorPin: 'Pin (anchor to canvas/world).',
  flowNodeQuickEditorUnpin: 'Unpin (float in screen-space).',
  flowNodeQuickEditorMinimize: 'Minimize node editor',
  flowNodeQuickEditorRestore: 'Restore node editor',
  flowNodeQuickEditorHideFields: 'Hide fields in node editor',
  flowNodeQuickEditorShowFields: 'Show fields in node editor',
  flowNodeQuickEditorChangeName: 'Change node label',
  flowNodeQuickEditorDuplicate: 'Duplicate selected node',
  flowNodeQuickEditorClearOutput: 'Clear node output (if available)',
  flowNodeQuickEditorHelp: 'Help',
  flowNodeQuickEditorRemoveNode: 'Remove selected node',
  flowNodeQuickEditorMenu: 'More node actions',
  flowNodeQuickEditorOpenInSidepane: 'Open selected node in sidepane',
  flowNodeQuickEditorEnableHandles: 'Enable handles for all inputs',
  flowNodeQuickEditorConvertToLoop: 'Convert to loop node',
  flowNodeQuickEditorHelpToast: 'Node Quick Editor: unpin to float and drag, pin to anchor in canvas-space. Escape closes the menu.',
  flowNodeQuickEditorEnableHandlesToast: 'Port Handles enabled for all nodes.',
  flowNodeQuickEditorEnableHandlesAlreadyOnToast: 'Port Handles are already enabled for all inputs.',
  flowNodeQuickEditorEnableHandlesBaselineLockedToast: BASELINE_LOCKED_TOAST,
  flowNodeQuickEditorConvertToLoopToast: 'Converted node to Loop.',
  flowNodeQuickEditorConvertToLoopAlreadyLoopToast: 'Node is already a Loop.',
  flowNodeQuickEditorRegistryToast: (label: string) => `Node Quick Editor mapping set to ${label}.`,
  flowNodeQuickEditorRegistryClearedToast: 'Node Quick Editor mapping cleared.',
  flowNodeQuickEditorSelectPlaceholder: 'Search or select…',
  flowNodeQuickEditorReferenceImagePlaceholder: 'Enter URL to desired file',
  flowNodeQuickEditorConnectedValueLabel: 'Connected value',
  flowNodeQuickEditorConnectedValuePrefix: 'Connected: ',
  flowNodeQuickEditorApplyConnectedValueLabel: 'Apply connected value',
  flowNodeQuickEditorConnectedControlsLabel: 'Connected value controls',
  flowNodeQuickEditorAutoApplyConnectedValuesLabel: 'Auto-apply connected values to empty fields',
  flowNodeQuickEditorApplyConnectedValuesToEmptyFieldsLabel: 'Apply connected values to empty fields',
  flowNodeQuickEditorApplyAllSuffix: 'all',
  flowEditorNoDraftGraphToast: 'No draft graph loaded.',
  flowEditorNodeNotFoundToast: (nodeId: string) => `Node not found: ${nodeId}`,
  flowEditorRunExportedToast: 'Exported Node Quick Editor bundle.',
  flowEditorRunFailedToast: 'Run failed.',
  flowEditorExportBundleButton: 'Export bundle',
  shiftDragToConnect: 'Shift-drag to connect',
  propsPanelOpenInSidePanel: 'Open in Side Panel',
  propsPanelOpenInNodesTab: 'Open in Nodes Tab',
  propsPanelOpenInEdgesTab: 'Open in Edges Tab',
  propsPanelOpenInEditor: 'Open in Editor',
  propsPanelAddToChat: 'Add to chat',
  propsPanelStartEdgeFromNode: 'Start Edge From Node',
  propsPanelCreateNodeAndEdgeSelectToEdit: 'Create Node + Edge (select to edit)',
  propsPanelDeleteNode: 'Delete Node',
  propsPanelOpenSourceInSidePanel: 'Open Source in Side Panel',
  propsPanelOpenTargetInSidePanel: 'Open Target in Side Panel',
  propsPanelUpdateSource: 'Update Source',
  propsPanelUpdateTarget: 'Update Target',
  propsPanelAddNode: 'Add Node',
  propsPanelAddNodeAndEdgeFromSelected: 'Add Node + Edge from selected',
  propsPanelStartEdgeFromSelected: 'Start Edge from selected',
  propsPanelShowInMarkdown: 'Show in Markdown',
  searchFieldsPlaceholder: 'Search fields…',
  fieldNamePlaceholder: 'Field name…',
  searchSettingsPlaceholder: 'Search settings…',
  searchShortcutsPlaceholder: 'Search shortcuts',
  searchGraphPlaceholder: 'Search graph…',
  searchNodesPlaceholder: 'Search nodes…',
  searchEdgesPlaceholder: 'Search edges…',
  searchHistoryPlaceholder: 'Search history…',
  searchFlowEditorManagerRegistryPlaceholder: 'Search mappings…',
  flowEditorManagerHeaderTooltip: 'Manage Node Quick Editor mappings and neutral specifications.',
  flowEditorManagerImportRegistryTooltip: 'Import Node Quick Editor bundle (.json)',
  flowEditorManagerExportRegistryTooltip: 'Export selected mapping as JSON',
  flowEditorManagerExportRegistrySelectToExportTooltip: 'Export all mappings as JSON',
  flowEditorManagerAddFromQuickEditorTooltip: 'Create a registry mapping from the currently open Node Quick Editor',
  flowEditorManagerRegisterGenerateVideoTooltip: 'Register the selected node as a Generate Video node and create a matching mapping',
  flowEditorManagerRegisterSelectedNodeTypeTooltip: 'Register a mapping for the selected node type and enable it',
  flowEditorManagerApplySelectedMappingToNodeTooltip: 'Apply the selected mapping to the selected node (updates node type and quick editor selectors)',
  noFields: 'No fields',
  noFieldsMatch: 'No fields match.',
  graphDataTableNoFilters: 'No filters.',
  graphDataTableNoRowsMatch: 'No rows match.',
  graphDataTableRowsCountOne: 'row',
  graphDataTableRowsCountMany: 'rows',
  graphDataTableSum: 'sum',
  graphDataTableAvg: 'avg',
  graphDataTableMin: 'min',
  graphDataTableMax: 'max',
  graphDataTableGroupRowsByLabel: 'Group rows by',
  graphDataTableClearGroupingAriaLabel: 'Clear grouping',
  graphDataTableNoGroupingLabel: 'No grouping',
  graphDataTableAggregateNumericFieldsLabel: 'Aggregate numeric-like fields',
  graphDataTableAutoSortWhileEditingLabel: 'Auto-sort while editing',
  graphDataTableSortingByIdFallbackLabel: 'Sorting by ID.',
  graphDataTableRemoveSortRuleTitle: 'Remove sort rule',
  graphDataTableAddSortLabel: 'Add sort',
  graphDataTableAggregateChartsTitle: 'Aggregate charts',
  graphDataTableAggregateChartsStartOff: 'Start with charts off',
  graphDataTableAggregateChartsStartRadial: 'Start with radial charts',
  graphDataTableAggregateChartsStartBars: 'Start with bar charts',
  graphDataTableAggregateChartsStartSparkline: 'Start with sparkline charts',
  graphDataTableAggregateChartToggleOff: 'Chart: Off',
  graphDataTableAggregateChartToggleRadial: 'Chart: Radial',
  graphDataTableAggregateChartToggleBars: 'Chart: Bars',
  graphDataTableAggregateChartToggleSparkline: 'Chart: Sparkline',
  noGraphLoaded: 'No graph loaded',
  workflowShareNoGraphData: 'No graph data to share',
  workflowShareCopiedJsonNoBackend: 'Copied JSON snapshot (no share backend configured)',
  workflowShareCopyFailedNoBackend: 'Copy failed (no share backend configured)',
  workflowShareFailedStatus: (status: number) => `Share failed (${status})`,
  workflowShareBackendNoUrl: 'Share backend did not return a URL',
  workflowShareLinkCopied: 'Share link copied to clipboard',
  workflowShareClipboardWriteFailed: 'Share link created (clipboard write failed)',
  workflowShareFailedGeneric: 'Share failed',
  requestFailedStatus: (status: number) => `Request failed: ${status}`,
  chatMissingEndpointAndModelError: 'Chat endpoint and model must be configured in Settings.',
  chatRequestFailedStatus: (status: number) => `Chat request failed with status ${status}.`,
  chatRequestFailedGenericError: 'Chat request failed.',
  chatResponseMissingContentError: 'Chat response did not include content.',
  chatEndpointOkStatus: 'Chat endpoint responded successfully.',
  chatEndpointUnreachableStatus: 'Chat endpoint appears unreachable. Ensure the local DeepSeek server is running.',
  chatUnableToReachEndpointError: (endpoint: string) =>
    `Unable to reach chat endpoint at ${endpoint}. Ensure the DeepSeek server is running and accessible from the browser.`,
  chatUnableToReachEndpointGenericError:
    'Unable to reach chat endpoint. Configure a reachable URL in Settings and ensure the server is running.',
  chatInputPlaceholder: 'Ask a question about the current graph or selection.',
  chatHistoryCountStatus: (count: number) => `History: ${count} messages`,
  frontmatterModeTooltip: 'Frontmatter Mode: focus canvas and panels on Mermaid frontmatter graph',
  frontmatterModeToggleTooltip: 'Frontmatter Mode: toggle to focus canvas and panels on Mermaid frontmatter graph',
  mermaidLayoutTooltip: 'Mermaid Layout: toggle to use the dedicated Mermaid flowchart layout.',
  nodeShapeModeTooltip: 'Node Shape: cycle between circle (default), rect, diamond, and hex nodes.',
  groupShapeRectTooltip: 'Cluster Shape: switch to Polygon shape.',
  groupShapePolygonTooltip: 'Cluster Shape: switch to Rect shape.',
  documentStructureModeTooltip: 'Document Structure Mode (default): render document sections/blocks/links as graph.',
  keywordModeTooltip:
    'Keyword Mode: subject/object/entity keywords as nodes; verb/predicate/relationship keywords as edges.',
  statsKeywordNodesSectionTitle: 'Nodes (Subject/Object/Entity Keywords)',
  statsNoKeywordNodesLabel: 'No keyword nodes available for this dataset.',
  statsKeywordNodesTitle: 'Keyword nodes',
  statsKeywordNodesBarHeightHint: 'Bar height = keyword mention count',
  statsEdgesSectionTitle: 'Edges (co-occurrence + similarity)',
  statsEdgesKeywordSectionTitle: 'Edges (Verb/Predicate/Relationship Keywords)',
  portHandlesTooltip:
    'Port Handles: toggle to show node connection handles and route 2D edge endpoints to the nearest handle.',
  fitToViewTooltip: 'Fit to View: automatically scale and center the graph to fill the viewport.',
  fitToScreenTooltip:
    'Fit to Screen mode: toggle to center the viewport on the full graph and clear Zoom to Selection until you turn it off.',
  pinToViewTooltip:
    'Pin to View: toggle to keep the current camera transform across graph updates and turn off Fit to Screen / Zoom to Selection while pinned.',
  zoomToSelectionTooltip: 'Zoom to Selection mode: toggle to keep the camera centered on the active selection and turn off Fit to Screen while focused.',
  renderMediaAsNodesTooltip: 'Rich Media: shows or hides media overlays on media-capable nodes without reloading.',
  launchTooltip: 'Launch',
  threeDModeOnTitle: '3D Mode (On)',
  threeDModeOffTitle: '3D Mode (Off)',
  twoDRendererD3Title: '2D Renderer: D3 Graph',
  twoDRendererFlowTitle: '2D Renderer: Flow',
  twoDRendererFlowEditorTitle: '2D Renderer: Flow Editor',
  twoDRendererDesignTitle: '2D Renderer: Design',
  twoDRendererToggleTooltip: '2D Renderer: switch between D3, Flow, Design, and Flow Editor.',
  documentModeTitle: 'Document Mode',
  geospatialModeTitle: 'Geospatial Mode',
  geospatialModeOnTitle: 'Geospatial Mode (On)',
  geospatialModeOffTitle: 'Document Mode (Geospatial Mode Off)',
  themeTooltipPrefix: 'Theme: ',
  chatEmptyStateHelp:
    'Chat is context-aware of the active graph selection. Configure endpoint and model in Settings, then ask a question about the current node or dataset.',
  chatNoSelectionContextStatus: 'No node selected; chat uses only conversation history.',
  chatUsingSelectedNodeContextStatus: (label: string, type: string) => `Using selected node ${label} (${type}) as context.`,
  chatStopButtonLabel: 'Stop',
  chatSendButtonLabel: 'Send',
  chatSendingButtonLabel: 'Sending…',
  emptyResponseError: EMPTY_RESPONSE,
  missingPathError: MISSING_PATH,
  orchestratorNoGraphDataLoaded: 'No graph data loaded.',
  orchestratorNoGraphDataToUpdate: 'No graph data available to update.',
  orchestratorGraphRagFullLabel: 'GraphRAG full ≤',
  orchestratorGraphRagHeadLabel: 'GraphRAG head',
  orchestratorGenericFullLabel: 'Generic full ≤',
  orchestratorGenericHeadLabel: 'Generic head',
  orchestratorTailLabel: 'Tail',
  orchestratorMatchesSuffix: ' (matches)',
  orchestratorDiffersSuffix: ' (differs)',
  orchestratorJsonLdContextEdgesLabel: 'JSON-LD context edges',
  orchestratorApplyChangesLabel: 'Apply changes',
  orchestratorUiEditorTabLabel: 'UI Editor',
  orchestratorTextEditorTabLabel: 'Text Editor',
  orchestratorClipboardNotAvailable: CLIPBOARD_NOT_AVAILABLE,
  orchestratorCopyFailed: COPY_FAILED,
  orchestratorTextInvalidJson: 'Text is not valid JSON.',
  orchestratorTextExpectedTopLevelObject: 'Expected a JSON object at the top level.',
  orchestratorTextExpectedActivePathObject: 'Expected an activePath object with ownerNodeId and graphRAGPath.',
  orchestratorTextOwnerNodeIdRequired: 'activePath.ownerNodeId is required.',
  orchestratorTextGraphRagPathInvalid: 'activePath.graphRAGPath is missing or invalid.',
  orchestratorTraversalFlowLabel: 'Zero-to-one graph traversal flow',
  orchestratorTraversalLiveTogetherSentence: (
    graphRagWorkflowLabel: string,
    orchestratorLabel: string,
    graphTraversalLabel: string,
  ) =>
    `${graphRagWorkflowLabel} and ${orchestratorLabel} live together in the floating ${graphTraversalLabel} panel.`,
  orchestratorTraversalOpenFloatingPanelButtonLabel: 'Open Graph Traversal floating panel',
  orchestratorTraversalPresetsSectionTitle: 'Traversal presets and helpers',
  orchestratorTraversalPresetsIntro: (orchestratorLabel: string) =>
    `Use Orchestrator (${orchestratorLabel}) over AgenticRAG graphRAGPath presets and generic traversals → keep graphRAGPath IRI chains and multi-hop reasoning grounded in current GraphData, schema, and selection state.`,
  orchestratorTraversalAgenticReasoningLabelsTitle: 'Agentic reasoning labels',
  orchestratorTraversalEditorSectionTitle: 'Traversal editor and layers',
  orchestratorGraphRagPathTraverseHelperTitle: 'graphRAGPath.traverse helper',
  orchestratorControlsLabel: 'Controls',
  orchestratorPlayPathButtonLabel: 'Play path',
  orchestratorPlayGraphRagTraversalButtonLabel: 'Play GraphRAG traversal',
  orchestratorSequenceLabel: 'Sequence',
  orchestratorDuckDbQueryPresetsTitle: 'DuckDB query presets',
  orchestratorDuckDbPresetSelectTooltip:
    'Default: first preset; Impact: selects which duckdbQueries[].sql and description are active.',
  orchestratorDuckDbSeedTraversalButtonLabel: 'Seed traversal from preset owner',
  orchestratorDuckDbCopySqlButtonLabel: 'Copy SQL',
  orchestratorDuckDbDirectionLabel: 'Direction',
  orchestratorDuckDbDescriptionValueTooltip:
    'Default: preset description; Impact: clarifies traversal helper intent and result focus.',
  orchestratorDuckDbSqlValueTooltip: 'Default: preset SQL; Impact: customizes DuckDB traversal helper query.',
  orchestratorTraversalSequenceTitle: 'Traversal sequence',
  collapseSectionTitle: COLLAPSE_SECTION_TITLE,
  expandSectionTitle: EXPAND_SECTION_TITLE,
  markdownCodeBlockActionsLabel: 'Code block actions',
  markdownGeoJsonAddDatasetTitle: 'Add GeoJSON as dataset',
  markdownGeoJsonLoadGraphTitle: 'Load GeoJSON as graph',
  markdownBlockReorderLineLabel: 'Reorder line',
  markdownBlockInsertLineLabel: 'Add line',
  orchestratorTraversalSequenceCollapseTitle: COLLAPSE_SECTION_TITLE,
  orchestratorTraversalSequenceExpandTitle: EXPAND_SECTION_TITLE,
  orchestratorTraversalSequencePreviewingPrefix: 'Previewing',
  orchestratorTraversalSequencePreviewingSuffix: 'edges in current traversal.',
  orchestratorTraversalGenericStartNodeLabel: 'Start node',
  orchestratorTraversalGenericMaxDepthLabel: 'Max depth',
  orchestratorTraversalGenericEdgeLabelsLabel: 'Edge labels',
  orchestratorTraversalQueryLabel: 'Query:',
  orchestratorTraversalQueryEnterPlaceholder: 'Enter query…',
  orchestratorTraversalQueryAddPlaceholder: 'Add query…',
  orchestratorTraversalExampleLabel: 'Example:',
  orchestratorTraversalExampleEnterPlaceholder: 'Enter example…',
  orchestratorTraversalExampleAddPlaceholder: 'Add example…',
  orchestratorTraversalClearQueryAriaLabel: 'Clear traversal query',
  orchestratorTraversalClearExampleAriaLabel: 'Clear traversal example',
  orchestratorTraversalAddExampleHopPlaceholder: 'Add example hop…',
  orchestratorTraversalAddHopButtonLabel: 'Add hop',
  orchestratorTraversalAddMultiHopPlaceholder: 'Add multiHop step…',
  orchestratorTraversalAddMultiHopButtonLabel: 'Add multiHop',
  orchestratorTraversalTraverseNodesTitle: 'traverse (node ids):',
  orchestratorTraversalClearTraverseNodesAriaLabel: 'Clear traverse nodes',
  orchestratorTraversalRemoveTraverseNodeAriaLabel: 'Remove traverse node',
  orchestratorTraversalHopsTitle: 'hops (example narrative steps):',
  orchestratorTraversalClearHopsAriaLabel: 'Clear hops',
  orchestratorTraversalRemoveHopAriaLabel: 'Remove traversal hop',
  orchestratorTraversalMultiHopTitle: 'multiHop (node filters or anchor hops):',
  orchestratorTraversalClearMultiHopAriaLabel: 'Clear multiHop filters',
  orchestratorTraversalRemoveMultiHopAriaLabel: 'Remove multiHop filter',
  graphRagWorkflowRowLabel: 'GraphRAG workflow',
  graphRagWorkflowGraphIdLabel: 'graphId:',
  graphRagWorkflowRetrievalLabel: 'retrieval:',
  graphRagWorkflowSourceLoadedLabel: 'Workflow step',
  graphRagWorkflowSourceGeneratedLabel: 'Generated',
  graphRagWorkflowSourceInvalidLabel: 'Invalid (fallback)',
  graphRagWorkflowSourceParseErrorLabel: 'Parse error (fallback)',
  graphRagWorkflowTracingOptionsTitle: 'Tracing options',
  graphRagWorkflowLastTraversalLabel: 'Last traversal:',
  graphRagWorkflowNoTraversalYetLabel: 'none yet',
  graphRagWorkflowEdgesUnitLabel: 'edges',
  graphRagWorkflowTraverseNodesUnitLabel: 'traverse nodes',
  graphRagWorkflowHopsUnitLabel: 'hops',
  graphRagWorkflowMaxDepthLabel: 'max depth',
  graphRagOpenOrchestratorAgenticContextButtonLabel: 'Open Orchestrator · AgenticRAG context',
  graphRagWorkflowIndexingParametersTitle: 'Indexing parameters',
  graphRagWorkflowDatasetInputDirTooltip:
    'dataset.inputDir → folder for raw inputs on rag:DatasetConfig. Use a stable, versioned document root instead of hardcoded paths.',
  graphRagWorkflowDatasetOutputDirTooltip:
    'dataset.outputDir → folder for GraphRAG intermediate and output artifacts on rag:DatasetConfig. Keep graphs, tables, and traces for this workflow in one directory.',
  graphRagWorkflowChunkMethodTooltip:
    'chunking.method → splitter name on rag:ChunkingConfig in workflow JSON-LD. Controls how documents are broken into retrieval chunks.',
  graphRagWorkflowChunkSizeTooltip:
    'chunking.chunkSize → tokens-per-chunk field on rag:ChunkingConfig. Balance recall, precision, and traversal performance for embeddings.',
  graphRagWorkflowEmbeddingProviderTooltip:
    'embeddingModel.provider → provider id on rag:EmbeddingModel (for example, openai or ollama). Routes AgenticRAG pipelines to the correct embedding backend.',
  graphRagWorkflowEmbeddingProviderImpact: 'Sets embedding provider identifier for AgenticRAG runs.',
  graphRagWorkflowEmbeddingModelNameTooltip:
    'embeddingModel.modelName → concrete model identifier on rag:EmbeddingModel. Captures reproducible embedding configuration in GraphRAG workflow JSON-LD.',
  graphRagWorkflowEmbeddingModelNameImpact: 'Sets concrete embedding model identifier.',
  graphRagWorkflowMaxHopsTooltip:
    'Orchestrator → graphRagWorkflow.maxHops caps traversal hops per query. Higher values explore deeper paths; lower values keep runs focused.',
  graphRagWorkflowDatasetInputDirImpact: 'Sets folder path for raw input documents used in GraphRAG indexing.',
  graphRagWorkflowDatasetOutputDirImpact: 'Sets folder path for GraphRAG intermediate artifacts and outputs.',
  graphRagWorkflowChunkMethodImpact:
    'Sets splitter used for document chunking so retrieval chunks align with GraphRAG traversal expectations.',
  graphRagWorkflowChunkSizeImpact:
    'Higher values use larger token chunks for higher recall; lower values favor precision and smaller, faster traversals.',
  graphRagWorkflowMaxHopsImpact:
    'Higher values explore deeper multi-hop chains per query; lower values keep GraphRAG runs focused and quick to replay.',
  syncedFieldsStatus: (count: number) => `Synced ${count} fields`,
  syncedNoFieldsFoundStatus: 'Synced (no fields found)',
  graphFieldsRawNodesEdgesToastTitle: 'Raw JSON fields via rawToGraphData',
  graphFieldsRawNodesEdgesToastBody:
    'This graph was ingested as raw JSON (context: "raw-nodes-edges"). Node and edge properties shown here come from rawToGraphData → map important fields like chunk_text, media_url, graphRAGPath, and workflow phases to AgenticRAG roles in Field Settings so tables, schema, and JSON-LD exports stay aligned.',
  graphFieldsNewFieldMissingNameStatus: 'New field: missing name',
  graphFieldsNewFieldNameCannotContainColonStatus: 'New field: name cannot include ":"',
  graphFieldsNewFieldAlreadyExistsStatus: 'New field: already exists',
  graphFieldsCreatedFieldStatus: (id: string) => `Created field ${id}`,
  graphFieldsAgenticLegendPillLabel:
    'AgenticRAG fields: chunk_text, embedding, geo, media_url, graphRAGPath (table mapping to JSON-LD)',
  graphFieldsSelectFieldToEdit: 'Select a field to edit',
  graphFieldsSelectFieldToViewSamples: 'Select a field to view samples',
  graphFieldsScopeNodeLabel: 'Node',
  graphFieldsScopeEdgeLabel: 'Edge',
  graphFieldsFieldSettingsTitle: 'Field Settings',
  graphFieldsLocalSchemaSelectOwnerEmpty: 'Select an owner to edit local schema.',
  graphFieldsLocalSchemaFacetTemplateJsonLabel: 'Template (JSON)',
  graphFieldsLocalSchemaFacetPropertiesLabel: 'Properties',
  graphFieldsLocalSchemaFacetValidationLabel: 'Validation',
  graphFieldsLocalSchemaFacetLocalRulesLabel: 'Local rules',
  graphFieldsHiddenToggleOnLabel: 'Yes',
  graphFieldsHiddenToggleOffLabel: 'No',
  graphFieldsDescriptionLabel: 'Description',
  graphFieldsNoOptions: 'No options',
  graphFieldsAddOptionFromSamplesPlaceholder: 'Add option from graph data…',
  graphFieldsAddAllSuggestionsLabel: 'Add all',
  graphFieldsNoSamplesFound: 'No samples found',
  graphFieldsClipboardNotAvailable: CLIPBOARD_NOT_AVAILABLE,
  graphFieldsCopyFailed: COPY_FAILED,
  graphFieldsSamplesCopiedStatus: (count: number) =>
    `Copied ${count.toLocaleString()} sample ${count === 1 ? 'value' : 'values'}`,
  graphFieldsSamplesAddedToOptionsStatus: (count: number) =>
    `Added ${count.toLocaleString()} option ${count === 1 ? 'value' : 'values'} from samples`,
  graphFieldsJsonDefaultClearedStatus: 'Cleared JSON default',
  graphFieldsJsonDefaultInvalidStatus: 'Invalid JSON default',
  graphFieldsJsonDefaultAppliedStatus: 'Applied JSON default',
  graphFieldsJsonDefaultFormattedStatus: 'Formatted JSON default',
  graphFieldsNodeColorLabel: 'Node field color',
  graphFieldsEdgeColorLabel: 'Edge field color',
  graphFieldsColorSwatchTooltip: (scope: 'node' | 'edge') =>
    `Color swatch for ${scope === 'node' ? 'node' : 'edge'} fields → updates schema.${
      scope === 'node' ? 'nodeStyles' : 'edgeStyles'
    } color so Graph Data Table, Renderer, and AgenticRAG JSON-LD exports share the same visual encoding.`,
  graphFieldsStylesSectionTitle: 'Styles',
  graphFieldsSchemaExtrasSectionTitle: 'Schema extras',
  graphFieldsAdvancedSchemaSectionTitle: 'Advanced schema',
  graphFieldsSchemaUiEditorSectionTitle: 'Schema UI editor',
  graphFieldsResyncButtonLabel: 'Re-sync',
  graphFieldsVisibleTotalStatus: (visible: number, total: number) =>
    `Visible ${visible} · Total ${total}`,
  graphFieldsAgenticFieldSettingsDescription:
    `Field Settings → map node and edge properties to AgenticRAG JSON-LD roles (see ${AGENTIC_RAG_SCHEMA_URL}/node-schema.jsonld and ${AGENTIC_RAG_SCHEMA_URL}/edge-schema.jsonld) so Graph Data Table, schema docs, and workflows share a single field interpretation.`,
  graphFieldsAgenticLegendChipLabel: 'AgenticRAG node fields',
  graphFieldsIconLegendHeaderLabel: 'Graph Fields icon legend',
  validationRequiredFieldsTitle: 'Required fields',
  validationPropertyTypesTitle: 'Property types',
  validationAdditionalOptionsJsonTitle: 'Additional options (JSON)',
  validationSeverityLabel: 'Severity',
  validationSeverityErrorLabel: 'Error',
  validationSeverityWarnLabel: 'Warn',
  validationRequireAllButtonLabel: 'Require all',
  validationRequireNumericButtonLabel: 'Require numeric',
  validationClearRequiredButtonLabel: 'Clear required',
  validationSetAllTypesButtonLabel: 'Set all types',
  validationInferTypesButtonLabel: 'Infer types',
  graphRagIgnoreFiltersEmpty: 'No ignore filters defined.',
  graphRagIgnorePatternsTooltip: 'Comma-separated ignore patterns (dir:, glob:, path:)',
  graphRagIgnorePatternsPlaceholder: 'e.g. .git, .venv, dir:experiments, glob:**/*.ipynb',
  graphRagOpenOrchestratorIgnorePathsButtonLabel: 'Open Orchestrator · Ignore codebase paths',
  graphRagUnrecognizedIgnorePrefixesLabel: 'Unrecognized prefixes',
  graphRagUnrecognizedIgnorePrefixesSupportedSuffix: '(supported: dir, glob, path)',
  orchestratorTextGraphRagPathMissingParts:
    'activePath.graphRAGPath must include traverse, multiHop, hops, or example content.',
  orchestratorTextNoNodeWithId: (id: string) => `No node with id ${id} found in graphData.`,
  orchestratorTextTraverseIdsMissing: (ids: ReadonlyArray<string>) =>
    `traverse[] contains node ids not present in graph: ${ids.join(', ')}`,
  helpShortcutsCountStatus: (count: number) => `${count} shortcuts`,
  helpNoShortcutsMatched: 'No shortcuts matched.',
  historyNoHistoryYet: 'No history yet',
  parserDataLoadFailed: 'Data load failed',
  htmlImportUrlPrompt: 'Enter HTML URL',
  htmlImportUrlButtonLabel: 'URL',
  htmlImportUrlPlaceholder: 'Enter URL',
  htmlImportFetchFailedStatus: (url: string) => `Data load failed: Failed to fetch content from ${url}`,
  htmlImportEmptyMarkdown:
    '# Imported Content\n\n(No readable content found. The site might be a JavaScript-only application.)',
  pdfImportUrlPrompt: 'Enter PDF URL (.pdf)',
  toolbarPdfImportUrlButtonLabel: 'URL (.pdf)',
  pdfImportFetchFailedStatus: (url: string) => `Data load failed: Failed to fetch PDF from ${url}`,
  pdfImportConvertFailedStatus: 'Data load failed: Failed to convert PDF to Markdown',
  pdfImportConvertFailedStatusWithError: (error: string) =>
    `Data load failed: Failed to convert PDF to Markdown (${error})`,
  youtubeImportUrlPrompt: 'Enter YouTube URL or ID',
  youtubeImportLanguagePrompt: 'Enter transcript language code(s) (comma-separated, default: en)',
  toolbarYouTubeImportUrlButtonLabel: 'URL',
  youtubeImportFetchFailedStatus: (urlOrId: string) =>
    `YouTube import: transcript fetch failed for ${urlOrId}`,
  youtubeImportConvertFailedStatusWithError: (error: string) =>
    `YouTube import: transcript-to-Markdown failed (${error})`,
  jsonImportUrlPrompt: 'Enter JSON/JSON-LD URL',
  parserBackendUrlPrompt: 'Enter backend URL that returns GraphData JSON',
  jsonImportFetchFailedStatus: (url: string) => `Data load failed: Failed to fetch JSON from ${url}`,
  parserDataLoadSuccess: 'Success',
  parserDataLoadSyntaxErrorStatus: (warning: string) => `Syntax/format error — ${warning}`,
  parserPresetSchemaNotFoundStatus: (path: string) => `Preset schema not found: ${path}`,
  parserPresetSchemaInvalidStatus: (path: string) => `Preset schema invalid: ${path}`,
  parserPresetDatasetNotFoundStatus: (path: string) => `Preset dataset not found: ${path}`,
  parserValidateNoDataStatus: 'No data loaded to validate',
  parserValidateStructureCompletedStatus: 'Structure validation completed',
  parserValidateStructureCompletedWithErrorsStatus: 'Structure validation completed with errors',
  parserNoMatchMessage: 'No parser matched the input. Configure a Custom Parser below.',
  parserReturnedNoResultWarning: 'Parser returned no result',
  parserBackendMissingGraphDataWarning: 'Backend response did not contain GraphData or database payload',
  parserImportNoFileSelected: 'No file selected',
  parserImportInvalidItem: 'Invalid item',
  parserImportMissingFieldsStatus: (id: string) => `Missing fields for ${id}`,
  parserImportFailedStatus: (id: string) => `Failed to import ${id}`,
  graphragTextPipelineBadge: 'GraphRAG',
  graphragTextPipelineTitle: 'GraphRAG Text-to-Graph pipeline (demo)',
  graphragTextPipelineTooltip:
    'GraphRAG text pipeline → preprocess tokens, infer entities, extract triples, and construct GraphData → inspect each stage output and FOSS library attribution → keep processing domain-agnostic and configuration-friendly.',
  graphragTextPipelineLibraryLinkLabel: 'Repo',
  bottomPanelViewingGraphJsonLabel: 'Viewing graph JSON',
  statsFilterTokensPlaceholder: 'Filter tokens',
  statsSortByCountLabel: 'Sort by count',
  statsSortAzLabel: 'Sort A–Z',
  statsExcludeWordsLabel: 'Exclude words',
  statsIncludeWordsLabel: 'Include words',
  statsShowTokensLabel: 'Show tokens',
  statsHideTokensLabel: 'Hide tokens',
  statsShowChartLabel: 'Show chart',
  statsHideChartLabel: 'Hide chart',
  statsSelectAllLabel: 'Select all',
  statsNoNodesAvailableLabel: 'No nodes available.',
  statsNoTokensFoundForGraphLayerLabel: 'No tokens found for this cluster layer.',
  statsSelectNodesToSeeTokenFrequenciesLabel: 'Select one or more nodes to see token frequencies.',
  statsSelectEdgeToSeeValuesLabel: 'Select an edge to see similarity/co-occurrence values.',
  statsOpenRendererSettingsForGraphLayersTitle: 'Open renderer settings for cluster layers',
  statsOpenRendererSettingsForCommunitiesTitle: 'Open renderer settings for clusters',
  statsOpenRendererSettingsForSemanticEdgesTitle: 'Open renderer settings for semantic edges',
  statsBarHeightTotalTokensHint: 'Bar height: total tokens (hover/click to highlight cluster layer nodes)',
  statsBarHeightSimilarityWeightHint: (metricLabel: string) =>
    `Bar height: ${metricLabel} weight (click to highlight edges)`,
  bottomPanelExternalPreviewMissingCodebasePathLabel:
    'External File Preview: selected row has no metadata.codebasePath (nothing to load).',
  bottomPanelMarkdownLoadingLabel: 'Loading markdown…',
  bottomPanelMarkdownLoadFailedLabel: 'Failed to load markdown.',
  bottomPanelMarkdownNoMarkdownLabel: 'No imported markdown available.',
  bottomPanelMarkdownMissingPathError: MISSING_PATH,
  bottomPanelMarkdownLoadFailedError: FAILED_TO_LOAD_MARKDOWN,
  markdownPreviewPrevButtonLabel: 'Prev',
  markdownPreviewNextButtonLabel: 'Next',
  markdownPreviewContentsLabel: 'Contents',
  markdownExplorerLabel: 'Explorer',
  markdownExplorerOutlineLabel: 'Outline',
  markdownExplorerBacklinksLabel: 'Backlinks',
  markdownPreviewSourceFilesLabel: 'Source Files',
  markdownPreviewBacklinksLabel: 'Backlinks',
  markdownPreviewBacklinksNoneLabel: 'None',
  markdownPreviewBacklinksEmptyStateLabel: 'No backlinks found.',
  markdownPreviewBacklinksUnlinkedPrefix: 'Unlinked: ',
  bottomPanelMarkdownEditorTitle: 'Markdown Editor',
  bottomPanelMarkdownViewerTitle: 'Markdown Viewer',
  bottomPanelMarkdownWordWrapToggleTitle: 'Toggle word wrap',
  bottomPanelMarkdownWordWrapOnTooltip: 'Word wrap: On',
  bottomPanelMarkdownWordWrapOffTooltip: 'Word wrap: Off',
  bottomPanelMarkdownFullEditorViewToggleTitle: 'Toggle full editor view',
  bottomPanelMarkdownFullEditorViewOnTooltip: 'Full editor view: On',
  bottomPanelMarkdownFullEditorViewOffTooltip: 'Full editor view: Off',
  bottomPanelMarkdownFullViewerViewToggleTitle: 'Toggle full viewer view',
  bottomPanelMarkdownFullViewerViewOnTooltip: 'Full viewer view: On',
  bottomPanelMarkdownFullViewerViewOffTooltip: 'Full viewer view: Off',
  bottomPanelMarkdownSyncScrollToggleTitle: 'Toggle synchronize scrolling',
  bottomPanelMarkdownSyncScrollOnTooltip: 'Synchronize scrolling: On',
  bottomPanelMarkdownSyncScrollOffTooltip: 'Synchronize scrolling: Off',
  bottomPanelMarkdownSplitViewToggleTitle: 'Switch to split view',
  bottomPanelMarkdownSplitViewOnTooltip: 'Split view: On',
  bottomPanelMarkdownSplitViewOffTooltip: 'Split view: Off',
  bottomPanelMarkdownTextHighlightToggleTitle: 'Toggle text highlight',
  bottomPanelMarkdownTextHighlightOnTooltip: 'Text highlight: On',
  bottomPanelMarkdownTextHighlightOffTooltip: 'Text highlight: Off',
  bottomPanelMarkdownPresentationModeToggleTitle: 'Toggle presentation mode',
  bottomPanelMarkdownPresentationModeOnTooltip: 'Presentation mode: On',
  bottomPanelMarkdownPresentationModeOffTooltip: 'Presentation mode: Off',
  bottomPanelMarkdownFullscreenToggleTitle: 'Enter Full Screen',
  bottomPanelMarkdownFullscreenOnTooltip: 'Exit Full Screen',
  bottomPanelMarkdownFullscreenOffTooltip: 'Enter Full Screen',
  bottomPanelMarkdownEditToggleTitle: 'Toggle Markdown view/editor',
  bottomPanelMarkdownApplyButtonLabel: 'Apply changes',
  bottomPanelMarkdownApplyButtonTitle: 'Apply changes (Cmd/Ctrl+Enter toggles Editor/Viewer)',
  bottomPanelMarkdownStatusLoading: 'Loading',
  bottomPanelMarkdownStatusReady: 'Ready',
  bottomPanelMarkdownStatusError: 'Error',
  bottomPanelMarkdownApplyJsonBackedUnsupportedStatus:
    'Apply is not supported for JSON → Markdown preview. Edit graph via UI Editor instead.',
  markdownLargeSummaryHelperText:
    'Large markdown summary: long slide decks are summarized; original file stays unchanged.',
  markdownPreviewTruncatedHelperText:
    'Preview truncated for very large markdown; edit source for full text.',
  bottomPanelMarkdownJsonBackedPreviewBadgeLabel: 'JSON-backed preview',
  bottomPanelMarkdownJsonBackedPreviewBadgeTooltip:
    'Preview of the last JSON/JSON-LD import. Edit graph structure via UI Editor; Apply from Markdown is disabled.',
  bottomPanelJsonMarkdownModeLabel: 'JSON → Markdown mode',
  bottomPanelJsonMarkdownModeAutoLabel: 'Auto',
  bottomPanelJsonMarkdownModeTableLabel: 'Table',
  bottomPanelJsonMarkdownModeKeyValueLabel: 'Key–value',
  bottomPanelJsonMarkdownModeHierarchicalLabel: 'Hierarchical',
  bottomPanelJsonMarkdownModeSuggestedPrefix: 'Suggested:',
  jsonToMarkdownEmptyArrayLabel: '(empty array)',
  jsonToMarkdownEmptyListLabel: '(empty list)',
  jsonToMarkdownMoreRowsLabel: (remaining: number) => `... ${remaining} more rows`,
  jsonToMarkdownItemLabel: (index: number) => `item ${index}`,
  toolbarMarkdownImportLocalDeviceButtonLabel: 'Local Device',
  toolbarMarkdownImportUrlButtonLabel: 'URL (.md)',
  toolbarEditorToggleTitle: 'Toggle Editor workspace',
  toolbarEditorWorkspaceOnTooltip: 'Editor workspace: On',
  toolbarEditorWorkspaceOffTooltip: 'Editor workspace: Off',
  toolbarGraphDataTableToggleTitle: 'Open Graph Data Table',
  toolbarGraphDataTableWorkspaceOnTooltip: 'Graph Data Table: Open',
  toolbarGraphDataTableWorkspaceOffTooltip: 'Graph Data Table: Closed',
  markdownImportUrlPrompt: 'Enter Markdown URL (.md)',
  toolbarJsonImportUrlButtonLabel: 'URL',
  toolbarParserExportJsonButtonLabel: 'JSON',
  toolbarParserExportYamlButtonLabel: 'YAML',
  toolbarParserExportPythonButtonLabel: 'Python',
  bottomPanelMarkdownNoSelectionLabel: 'Imported markdown loaded.',
  bottomPanelMarkdownMissingDocumentPathLabel: 'Selected row has no metadata.documentPath.',
  bottomPanelImportHistoryJsonLdAgenticRagButtonLabel: 'Import History JSON-LD (AgenticRAG)',
  markdownPreviewShowOnCanvasLabel: 'Show on Canvas',
  markdownSlideIndexLabel: (index: number) => `Slide ${index}`,
  markdownSlidesSidebarViewTitle: 'View',
  markdownSlidesSidebarClearSelectionLabel: 'Clear selection',
  markdownSlidesSidebarSlidesSuffix: 'slides',
  markdownMediaErrorPrefix: 'Media failed to load',
  markdownMediaLoadEmbedLabel: 'Load embed',
  markdownMediaOpenInNewTabLabel: 'Open in new tab',
  markdownPresentationEmptyTitle: 'Presentation mode is ready.',
  markdownPresentationEmptyBody: 'Add markdown with --- separators to define slides.',
  
  // Field Endpoints & Cardinality
  endpointsAndCardinalityHeader: 'Endpoints & Cardinality',
  selectScopeToEditConstraints: (scope: 'node' | 'edge') => 
    `Select a ${scope === 'node' ? 'node type' : 'edge label'} to edit constraints`,
  endpointMatrixHeader: 'Endpoint matrix',
  edgesPerNodeTypeHeader: 'Edges per node type',
  edgesPerLabelPerNodeHeader: 'Edges per label (per node)',
  sourcesPlaceholder: 'Sources (comma)',
  targetsPlaceholder: 'Targets (comma)',
  minPlaceholder: 'min',
  maxPlaceholder: 'max',
  maxPerNodePlaceholder: 'max per node',
} as const;
