export const UI_LAYOUT = {
  toolbarOffsetPx: 36,
} as const;

export const UI_ANCHORS = {
  graphFields: 'graph-fields',
  graphFieldsIcons: 'graph-fields:icons',
  searchPanel: 'search-panel',
  schemaPanel: 'schema-panel',
  workflowPanel: 'workflow-panel',
  settingsPanel: 'settings-panel',
  settingsUiIconScale: 'settings:uiIconScale',
  ragEmbedding: 'rag:Embedding',
  ragGraphRAGWorkflow: 'rag:GraphRAGWorkflow',
  aiKgLayers: 'render:aiKgLayers',
  searchNode: 'search:node',
  searchEdge: 'search:edge',
  helpGraphLayers: 'help:graphLayers',
} as const;

export type UiAnchorId = (typeof UI_ANCHORS)[keyof typeof UI_ANCHORS];

export const UI_SELECTORS = {
  draggablePanelIgnorePointerDown: [
    'button',
    '[role="button"]',
    'input',
    'textarea',
    'select',
    'a',
    '[role="textbox"]',
    '[contenteditable="true"]',
    '[data-no-drag="true"]',
    '[data-floating-panel-no-drag="true"]',
    '[data-main-panel-no-drag="true"]',
  ].join(', '),
  canvasWheelIgnore: '[data-kg-canvas-wheel-ignore="true"]',
} as const;

export const UI_LABELS = {
  sourceFiles: 'Source Files',
  csv: 'CSV',
  graphFields: 'Graph Fields',
  previewPanel: 'Preview Panel',
  search: 'Graph Search',
  chat: 'Chat',
  inspector: 'Inspector',
  schema: 'Schema',
  settings: 'Settings',
  markdown: 'Markdown',
  html: 'HTML',
  pdf: 'PDF',
  youtube: 'YouTube',
  jsonLd: 'JSON-LD',
  json: 'JSON',
  openData: 'Open Data',
  loadStatus: 'Load Status',
  globalFields: 'Global Fields',
  baseFields: 'Base Fields',
  floatingPanel: 'Floating panel',
  workspaceActions: 'Workspace Actions',
  graphTraversal: 'Graph Traversal',
  dragToResize: 'Drag to resize',
  data: 'Data',
  parser: 'Parser',
  schemaConfigurator: 'Schema Configurator',
  orchestrator: 'Orchestrator',
  renderer: 'Renderer',
  aiKgLayers: 'AI KG Layers',
  history: 'History',
  log: 'Log',
  help: 'Help',
  workflowManager: 'Workflow Manager',
  flowEditorManager: 'Flow Editor Manager',
  flowEditorMapping: 'Flow Editor Mapping',
  flowEditorSpecification: 'Flow Editor Specification',
  node: 'Node',
  workflow: 'Workflow',
  sidebar: 'Sidebar',
  propsPanel: 'Props Panel',
  geo: 'Geo',
  samples: 'Samples',
  close: 'Close',
  save: 'Save',
  reset: 'Reset',
  restore: 'Restore',
  clear: 'Clear',
  cancel: 'Cancel',
  create: 'Create',
  add: 'Add',
  apply: 'Apply',
  format: 'Format',
  undo: 'Undo',
  redo: 'Redo',
  edit: 'Edit',
  delete: 'Delete',
  copy: 'Copy',
  import: 'Import',
  export: 'Export',
  addFromQuickEditor: 'Add from Quick Editor',
  registerGenerateVideo: 'Register Generate Video',
  selectAll: 'Select all',
  collapseAll: 'Collapse all',
  expandAll: 'Expand all',
  view: 'View',
  menu: 'Menu',
  documentStructureMode: 'Document Structure Mode',
  keywordMode: 'Keyword Mode',
  name: 'Name',
  scope: 'Scope',
  type: 'Type',
  hidden: 'Hidden',
  options: 'Options',
  defaultValue: 'Default value',
  newField: 'New Field',
  showAll: 'Show all',
  hideAll: 'Hide all',
  customFields: 'Custom Fields',
  derivedFields: 'Derived Fields',
  globalSchema: 'Global Schema',
  base: 'Base',
  moving: 'Moving…',
  zoomIn: 'Zoom In',
  zoomOut: 'Zoom Out',
  fitToView: 'Fit to View',
  fitToScreen: 'Fit to Screen',
  pinToView: 'Pin to View',
  zoomToSelection: 'Zoom to Selection',
  multiSelectMode: 'Multi-select Mode',
  layerMode: 'Layer Mode',
  graphLayersMode: 'Clusters',
  portHandles: 'Port Handles',
  radialLayoutMode: 'Radial Layout',
  dragToReorder: 'Drag to reorder',
  removeOption: 'Remove option',
  fieldSettings: 'Field Settings',
  ragEmbedding: 'Embedding (AgenticRAG)',
  ragGraphRAGWorkflow: 'GraphRAG Workflow (AgenticRAG)',
  createNode: 'Create Node',
  addToChat: 'Add to chat',
  localSchemaProperties: 'Local schema · Properties',
  localSchemaTemplate: 'Local schema · Template',
  localSchemaValidation: 'Local schema · Validation',
  localSchemaLocalRules: 'Local schema · Local rules',
  mermaidFocus: 'Mermaid Focus',
  status: 'Status',
  editor: 'Editor',
  graphDataTable: 'Graph Data Table',
  nodeShapeMode: 'Node Shape',
  groupShapeRect: 'Cluster Shape: Rect',
  groupShapePolygon: 'Cluster Shape: Polygon',
  frontmatterMode: 'Frontmatter Mode',
  frontmatterModeMermaidFocus: 'Frontmatter Mode (Mermaid focus)',
  mermaidLayout: 'Mermaid Layout',
  renderMediaAsNodes: 'Rich Media',
  renderMediaAsNodesOn: 'Rich Media (On)',
  renderMediaAsNodesOff: 'Rich Media (Off)',
  threeDMode: '3D Mode',
  threeDModeOn: '3D Mode (On)',
  threeDModeOff: '3D Mode (Off)',
  launch: 'Launch',
  theme: 'Theme',
  resizeBottomPanel: 'Resize bottom panel',
  layerModeDescriptorSchema: 'Schema (entities)',
  layerModeDescriptorDocument: 'Layered structure (document)',
  layerModeDescriptorSemantic: 'Similarity clusters (semantic)',
  themeSystem: 'System',
  themeLight: 'Light',
  themeDark: 'Dark',
  dataTableAriaLabel: 'Data Table',
  nodesLabel: 'Nodes:',
  edgesLabel: 'Edges:',
  selectedLabel: 'Selected:',
  noneLabel: 'None',
  perfButtonLabel: 'Perf',
  statusBarAriaLabel: 'Status Bar',

  flowNodeQuickEditor: 'Node Quick Editor',
  flowNodeQuickEditorForm: 'Quick edit form',
  flowNodeQuickEditorNodeLegend: 'Node',
  flowNodeQuickEditorSmartFieldsLegend: 'Smart fields',
  flowNodeQuickEditorModel: 'Model',
  flowNodeQuickEditorPrompt: 'Prompt',
  flowNodeQuickEditorAspectRatio: 'Aspect ratio',
  flowNodeQuickEditorDuration: 'Duration',
  flowNodeQuickEditorResolution: 'Resolution',
  flowNodeQuickEditorGenerateAudio: 'Generate audio',
  flowNodeQuickEditorFast: 'Fast',
  flowNodeQuickEditorReferenceImage: 'Reference image',
  flowNodeQuickEditorValidate: 'Validate',
  flowNodeQuickEditorActions: 'Quick edit actions',

  flowNodeQuickEditorSchemaLegend: 'Schema',
  flowNodeQuickEditorSchemaFieldsLegend: 'Fields',
  hideFields: 'Hide Fields',
  showFields: 'Show Fields',
  changeName: 'Change name',
  duplicate: 'Duplicate',
  clearOutput: 'Clear Output',
  removeNode: 'Remove Node',
  more: 'More',
  openInSidepane: 'Open in sidepane',
  enableHandlesForAllInputs: 'Enable Handles for All Inputs',
  convertToLoopNode: 'Convert to Loop Node',
  pinPanel: 'Pin panel',
  unpinPanel: 'Unpin panel',
  minimizePanel: 'Minimize panel',
  restorePanel: 'Restore panel',
} as const;

export const COPY_ZOOM_FIT_SCREEN = UI_LABELS.fitToScreen
export const COPY_ZOOM_FIT_VIEW = UI_LABELS.fitToView
export const COPY_ZOOM_TO_SELECTION = UI_LABELS.zoomToSelection
export const COPY_ZOOM_PIN = UI_LABELS.pinToView
export const COPY_ZOOM_RESET = UI_LABELS.reset

export type UiLabelId = (typeof UI_LABELS)[keyof typeof UI_LABELS];

export const SCHEMA_KEYS = {
  globalSchema: 'global:schema',
  localSchemaProperties: 'local:schema:properties',
  localSchemaTemplate: 'local:schema:template',
  localSchemaValidation: 'local:schema:validation',
  localSchemaLocalRules: 'local:schema:localRules',
} as const;

export const ZERO_TO_ONE_GRAPH_TRAVERSAL_LABEL = 'Zero-to-one graph traversal';

export const HTML_IMPORT_GUARDS = {
  viteDevIndexMarkers: [
    '<div id="root"></div>',
    'src="/src/main.tsx"',
    'src="/@vite/client"',
    '"/@react-refresh"',
  ],
  viteDevIndexMinMarkerMatches: 2,
} as const;

export function looksLikeViteDevIndexHtml(htmlText: string): boolean {
  const text = String(htmlText || '')
  const markers = HTML_IMPORT_GUARDS.viteDevIndexMarkers || []
  const threshold = HTML_IMPORT_GUARDS.viteDevIndexMinMarkerMatches || 0
  if (!text.trim() || markers.length === 0 || threshold <= 0) return false
  let matches = 0
  for (const m of markers) {
    if (m && text.includes(m)) matches += 1
    if (matches >= threshold) return true
  }
  return false
}
