name = "knowgrph-storage"
main = "index.ts"
compatibility_date = "2026-05-07"
workers_dev = true

[observability]
enabled = true

[[routes]]
pattern = "airvio.co/api/storage/*"
zone_name = "airvio.co"

[[d1_databases]]
binding = "DB"
database_name = "knowgrph-storage"
database_id = "633355bf-1a52-4085-bd3c-eba4220ff152"
migrations_dir = "../../d1/migrations"

[[r2_buckets]]
binding = "KNOWGRPH_STORAGE_BLOB_BUCKET"
bucket_name = "knowgrph-storage-blobs"
