import { useGraphStore } from '@/hooks/useGraphStore'
import { readPdfWorkspaceOutputDirRel, writePdfWorkspaceOutputDirRel } from '@/lib/pdf/pdfWorkspacePreferences'
import type { SettingMeta } from './types'

const s = () => useGraphStore.getState()

export const uiImportPdfSettingsRegistry: SettingMeta[] = [
  {
    key: 'pdfWorkspaceOutputDirRel',
    type: 'string',
    source: 'localStorage',
    read: () => readPdfWorkspaceOutputDirRel(),
    write: v => {
      writePdfWorkspaceOutputDirRel(String(v || ''))
    },
    docKey: 'pdfWorkspaceOutputDirRel',
    default: () => readPdfWorkspaceOutputDirRel(),
  },
  {
    key: 'pdfImportIncludeImages',
    type: 'boolean',
    source: 'store',
    read: () => s().pdfImportIncludeImages,
    write: v => s().setPdfImportIncludeImages(!!v),
    docKey: 'pdfImportIncludeImages',
    default: () => true,
  },
  {
    key: 'pdfImportConversionMode',
    type: 'string',
    source: 'store',
    read: () => s().pdfImportConversionMode,
    write: v => s().setPdfImportConversionMode(String(v) === 'image-heavy' ? 'image-heavy' : String(v) === 'scan-ocr' ? 'scan-ocr' : 'text-only'),
    docKey: 'pdfImportConversionMode',
    default: () => 'text-only',
    options: ['text-only', 'image-heavy', 'scan-ocr'],
  },
  {
    key: 'pdfImportEmbedImages',
    type: 'boolean',
    source: 'store',
    read: () => s().pdfImportEmbedImages,
    write: v => s().setPdfImportEmbedImages(!!v),
    docKey: 'pdfImportEmbedImages',
    default: () => false,
  },
  {
    key: 'pdfImportMaxExtractedImagesPerPage',
    type: 'number',
    source: 'store',
    read: () => s().pdfImportMaxExtractedImagesPerPage,
    write: v => s().setPdfImportMaxExtractedImagesPerPage(Number(v)),
    docKey: 'pdfImportMaxExtractedImagesPerPage',
    default: () => 12,
  },
  {
    key: 'pdfImportMaxEmbeddedImagesPerPage',
    type: 'number',
    source: 'store',
    read: () => s().pdfImportMaxEmbeddedImagesPerPage,
    write: v => s().setPdfImportMaxEmbeddedImagesPerPage(Number(v)),
    docKey: 'pdfImportMaxEmbeddedImagesPerPage',
    default: () => 6,
  },
  {
    key: 'pdfImportMaxEmbeddedTotalBytes',
    type: 'number',
    source: 'store',
    read: () => s().pdfImportMaxEmbeddedTotalBytes,
    write: v => s().setPdfImportMaxEmbeddedTotalBytes(Number(v)),
    docKey: 'pdfImportMaxEmbeddedTotalBytes',
    default: () => 4 * 1024 * 1024,
  },
  {
    key: 'pdfImportMaxEmbeddedAssetBytes',
    type: 'number',
    source: 'store',
    read: () => s().pdfImportMaxEmbeddedAssetBytes,
    write: v => s().setPdfImportMaxEmbeddedAssetBytes(Number(v)),
    docKey: 'pdfImportMaxEmbeddedAssetBytes',
    default: () => 2 * 1024 * 1024,
  },
  {
    key: 'pdfImportProvider',
    type: 'string',
    source: 'store',
    read: () => s().pdfImportProvider,
    write: v => s().setPdfImportProvider(String(v) === 'docling-remote' ? 'docling-remote' : 'native'),
    docKey: 'pdfImportProvider',
    default: () => 'native',
    options: ['native', 'docling-remote'],
  },
  {
    key: 'pdfImportDoclingEndpoint',
    type: 'string',
    source: 'store',
    read: () => s().pdfImportDoclingEndpoint,
    write: v => s().setPdfImportDoclingEndpoint(String(v || '').trim() || null),
    docKey: 'pdfImportDoclingEndpoint',
    default: () => null,
  },
  {
    key: 'pdfImportProviderFallbackToNative',
    type: 'boolean',
    source: 'store',
    read: () => s().pdfImportProviderFallbackToNative,
    write: v => s().setPdfImportProviderFallbackToNative(!!v),
    docKey: 'pdfImportProviderFallbackToNative',
    default: () => true,
  },
  {
    key: 'pdfImportDeepseekOcr2Enabled',
    type: 'boolean',
    source: 'store',
    read: () => s().pdfImportDeepseekOcr2Enabled,
    write: v => s().setPdfImportDeepseekOcr2Enabled(!!v),
    docKey: 'pdfImportDeepseekOcr2Enabled',
    default: () => false,
  },
  {
    key: 'pdfImportDeepseekOcr2Mode',
    type: 'string',
    source: 'store',
    read: () => s().pdfImportDeepseekOcr2Mode,
    write: v => s().setPdfImportDeepseekOcr2Mode(String(v) === 'always' ? 'always' : 'fallback'),
    docKey: 'pdfImportDeepseekOcr2Mode',
    default: () => 'fallback',
    options: ['fallback', 'always'],
  },
]
