import { useGraphStore } from '@/hooks/useGraphStore'
import type { SettingMeta } from './types'

const s = () => useGraphStore.getState()

export const uiImportPdfSettingsRegistry: SettingMeta[] = [
  {
    key: 'pdfImportIncludeImages',
    type: 'boolean',
    source: 'store',
    read: () => s().pdfImportIncludeImages,
    write: v => s().setPdfImportIncludeImages(!!v),
    docKey: 'pdfImportIncludeImages',
    default: () => true,
  },
  {
    key: 'pdfImportConversionMode',
    type: 'string',
    source: 'store',
    read: () => s().pdfImportConversionMode,
    write: v => s().setPdfImportConversionMode(String(v) === 'image-heavy' ? 'image-heavy' : String(v) === 'scan-ocr' ? 'scan-ocr' : 'text-only'),
    docKey: 'pdfImportConversionMode',
    default: () => 'text-only',
    options: ['text-only', 'image-heavy', 'scan-ocr'],
  },
  {
    key: 'pdfImportMaxPages',
    type: 'number',
    source: 'store',
    read: () => s().pdfImportMaxPages,
    write: v => s().setPdfImportMaxPages(Number(v)),
    docKey: 'pdfImportMaxPages',
    default: () => 0,
  },
  {
    key: 'pdfImportMaxPdfBytes',
    type: 'number',
    source: 'store',
    read: () => s().pdfImportMaxPdfBytes,
    write: v => s().setPdfImportMaxPdfBytes(Number(v)),
    docKey: 'pdfImportMaxPdfBytes',
    default: () => 100 * 1024 * 1024,
  },
  {
    key: 'pdfImportFetchTimeoutMs',
    type: 'number',
    source: 'store',
    read: () => s().pdfImportFetchTimeoutMs,
    write: v => s().setPdfImportFetchTimeoutMs(Number(v)),
    docKey: 'pdfImportFetchTimeoutMs',
    default: () => 60_000,
  },
  {
    key: 'pdfImportUploadTimeoutMs',
    type: 'number',
    source: 'store',
    read: () => s().pdfImportUploadTimeoutMs,
    write: v => s().setPdfImportUploadTimeoutMs(Number(v)),
    docKey: 'pdfImportUploadTimeoutMs',
    default: () => 30_000,
  },
  {
    key: 'pdfImportConvertTimeoutMs',
    type: 'number',
    source: 'store',
    read: () => s().pdfImportConvertTimeoutMs,
    write: v => s().setPdfImportConvertTimeoutMs(Number(v)),
    docKey: 'pdfImportConvertTimeoutMs',
    default: () => 180_000,
  },
  {
    key: 'pdfImportStreamDecodeCacheMaxBytes',
    type: 'number',
    source: 'store',
    read: () => s().pdfImportStreamDecodeCacheMaxBytes,
    write: v => s().setPdfImportStreamDecodeCacheMaxBytes(Number(v)),
    docKey: 'pdfImportStreamDecodeCacheMaxBytes',
    default: () => 64 * 1024 * 1024,
  },
  {
    key: 'pdfImportContentStreamMaxDecodeBytes',
    type: 'number',
    source: 'store',
    read: () => s().pdfImportContentStreamMaxDecodeBytes,
    write: v => s().setPdfImportContentStreamMaxDecodeBytes(Number(v)),
    docKey: 'pdfImportContentStreamMaxDecodeBytes',
    default: () => 8 * 1024 * 1024,
  },
  {
    key: 'pdfImportPageContentMaxBytes',
    type: 'number',
    source: 'store',
    read: () => s().pdfImportPageContentMaxBytes,
    write: v => s().setPdfImportPageContentMaxBytes(Number(v)),
    docKey: 'pdfImportPageContentMaxBytes',
    default: () => 8 * 1024 * 1024,
  },
  {
    key: 'pdfImportCmapMaxBytes',
    type: 'number',
    source: 'store',
    read: () => s().pdfImportCmapMaxBytes,
    write: v => s().setPdfImportCmapMaxBytes(Number(v)),
    docKey: 'pdfImportCmapMaxBytes',
    default: () => 256 * 1024,
  },
  {
    key: 'pdfImportMaxToUnicodeStreamBytes',
    type: 'number',
    source: 'store',
    read: () => s().pdfImportMaxToUnicodeStreamBytes,
    write: v => s().setPdfImportMaxToUnicodeStreamBytes(Number(v)),
    docKey: 'pdfImportMaxToUnicodeStreamBytes',
    default: () => 256 * 1024,
  },
  {
    key: 'pdfImportToUnicodeMaxDecodeBytes',
    type: 'number',
    source: 'store',
    read: () => s().pdfImportToUnicodeMaxDecodeBytes,
    write: v => s().setPdfImportToUnicodeMaxDecodeBytes(Number(v)),
    docKey: 'pdfImportToUnicodeMaxDecodeBytes',
    default: () => 512 * 1024,
  },
  {
    key: 'pdfImportImageStreamMaxDecodeBytes',
    type: 'number',
    source: 'store',
    read: () => s().pdfImportImageStreamMaxDecodeBytes,
    write: v => s().setPdfImportImageStreamMaxDecodeBytes(Number(v)),
    docKey: 'pdfImportImageStreamMaxDecodeBytes',
    default: () => 32 * 1024 * 1024,
  },
  {
    key: 'pdfImportMaxTextContentBytesPerPage',
    type: 'number',
    source: 'store',
    read: () => s().pdfImportMaxTextContentBytesPerPage,
    write: v => s().setPdfImportMaxTextContentBytesPerPage(Number(v)),
    docKey: 'pdfImportMaxTextContentBytesPerPage',
    default: () => 512 * 1024,
  },
  {
    key: 'pdfImportMaxTextStreamBytes',
    type: 'number',
    source: 'store',
    read: () => s().pdfImportMaxTextStreamBytes,
    write: v => s().setPdfImportMaxTextStreamBytes(Number(v)),
    docKey: 'pdfImportMaxTextStreamBytes',
    default: () => 256 * 1024,
  },
  {
    key: 'pdfImportMaxFormXObjectBytes',
    type: 'number',
    source: 'store',
    read: () => s().pdfImportMaxFormXObjectBytes,
    write: v => s().setPdfImportMaxFormXObjectBytes(Number(v)),
    docKey: 'pdfImportMaxFormXObjectBytes',
    default: () => 512 * 1024,
  },
  {
    key: 'pdfImportMaxFormXObjectStreamBytes',
    type: 'number',
    source: 'store',
    read: () => s().pdfImportMaxFormXObjectStreamBytes,
    write: v => s().setPdfImportMaxFormXObjectStreamBytes(Number(v)),
    docKey: 'pdfImportMaxFormXObjectStreamBytes',
    default: () => 256 * 1024,
  },
  {
    key: 'pdfImportMaxFormXObjectCount',
    type: 'number',
    source: 'store',
    read: () => s().pdfImportMaxFormXObjectCount,
    write: v => s().setPdfImportMaxFormXObjectCount(Number(v)),
    docKey: 'pdfImportMaxFormXObjectCount',
    default: () => 64,
  },
  {
    key: 'pdfImportEmbedImages',
    type: 'boolean',
    source: 'store',
    read: () => s().pdfImportEmbedImages,
    write: v => s().setPdfImportEmbedImages(!!v),
    docKey: 'pdfImportEmbedImages',
    default: () => false,
  },
  {
    key: 'pdfImportMaxExtractedImagesPerPage',
    type: 'number',
    source: 'store',
    read: () => s().pdfImportMaxExtractedImagesPerPage,
    write: v => s().setPdfImportMaxExtractedImagesPerPage(Number(v)),
    docKey: 'pdfImportMaxExtractedImagesPerPage',
    default: () => 12,
  },
  {
    key: 'pdfImportMaxEmbeddedImagesPerPage',
    type: 'number',
    source: 'store',
    read: () => s().pdfImportMaxEmbeddedImagesPerPage,
    write: v => s().setPdfImportMaxEmbeddedImagesPerPage(Number(v)),
    docKey: 'pdfImportMaxEmbeddedImagesPerPage',
    default: () => 6,
  },
  {
    key: 'pdfImportMaxEmbeddedTotalBytes',
    type: 'number',
    source: 'store',
    read: () => s().pdfImportMaxEmbeddedTotalBytes,
    write: v => s().setPdfImportMaxEmbeddedTotalBytes(Number(v)),
    docKey: 'pdfImportMaxEmbeddedTotalBytes',
    default: () => 4 * 1024 * 1024,
  },
  {
    key: 'pdfImportMaxEmbeddedAssetBytes',
    type: 'number',
    source: 'store',
    read: () => s().pdfImportMaxEmbeddedAssetBytes,
    write: v => s().setPdfImportMaxEmbeddedAssetBytes(Number(v)),
    docKey: 'pdfImportMaxEmbeddedAssetBytes',
    default: () => 2 * 1024 * 1024,
  },
  {
    key: 'pdfImportReconstructTables',
    type: 'boolean',
    source: 'store',
    read: () => s().pdfImportReconstructTables,
    write: v => s().setPdfImportReconstructTables(!!v),
    docKey: 'pdfImportReconstructTables',
    default: () => true,
  },
  {
    key: 'pdfImportTableMinColumns',
    type: 'number',
    source: 'store',
    read: () => s().pdfImportTableMinColumns,
    write: v => s().setPdfImportTableMinColumns(Number(v)),
    docKey: 'pdfImportTableMinColumns',
    default: () => 2,
  },
  {
    key: 'pdfImportTableMinRows',
    type: 'number',
    source: 'store',
    read: () => s().pdfImportTableMinRows,
    write: v => s().setPdfImportTableMinRows(Number(v)),
    docKey: 'pdfImportTableMinRows',
    default: () => 3,
  },
  {
    key: 'pdfImportTableMaxRows',
    type: 'number',
    source: 'store',
    read: () => s().pdfImportTableMaxRows,
    write: v => s().setPdfImportTableMaxRows(Number(v)),
    docKey: 'pdfImportTableMaxRows',
    default: () => 60,
  },
  {
    key: 'pdfImportProvider',
    type: 'string',
    source: 'store',
    read: () => s().pdfImportProvider,
    write: v => s().setPdfImportProvider(String(v) === 'docling-remote' ? 'docling-remote' : 'native'),
    docKey: 'pdfImportProvider',
    default: () => 'native',
    options: ['native', 'docling-remote'],
  },
  {
    key: 'pdfImportDoclingEndpoint',
    type: 'string',
    source: 'store',
    read: () => s().pdfImportDoclingEndpoint,
    write: v => s().setPdfImportDoclingEndpoint(String(v || '').trim() || null),
    docKey: 'pdfImportDoclingEndpoint',
    default: () => null,
  },
  {
    key: 'pdfImportProviderFallbackToNative',
    type: 'boolean',
    source: 'store',
    read: () => s().pdfImportProviderFallbackToNative,
    write: v => s().setPdfImportProviderFallbackToNative(!!v),
    docKey: 'pdfImportProviderFallbackToNative',
    default: () => true,
  },
  {
    key: 'pdfImportOcrEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().pdfImportOcrEnabled,
    write: v => s().setPdfImportOcrEnabled(!!v),
    docKey: 'pdfImportOcrEnabled',
    default: () => false,
  },
  {
    key: 'pdfImportOcrMode',
    type: 'string',
    source: 'store',
    read: () => s().pdfImportOcrMode,
    write: v => s().setPdfImportOcrMode(String(v) === 'always' ? 'always' : 'fallback'),
    docKey: 'pdfImportOcrMode',
    default: () => 'fallback',
    options: ['fallback', 'always'],
  },
]
