import { useGraphStore } from '@/hooks/useGraphStore'
import type { SettingMeta } from './types'

const s = () => useGraphStore.getState()

export const uiMonacoSettingsRegistry: SettingMeta[] = [
  {
    key: 'monacoLanguageJsonEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoLanguageJsonEnabled,
    write: v => s().setMonacoLanguageJsonEnabled(!!v),
    docKey: 'editor.monaco.languageJson.enabled',
    default: () => true,
  },
  {
    key: 'monacoLanguageJsonLoadMode',
    type: 'string',
    source: 'store',
    read: () => s().monacoLanguageJsonLoadMode,
    write: v => s().setMonacoLanguageJsonLoadMode(v === 'eager' ? 'eager' : 'lazy'),
    docKey: 'editor.monaco.languageJson.loadMode',
    default: () => 'lazy',
    options: ['lazy', 'eager'],
  },
  {
    key: 'monacoLanguageSqlEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoLanguageSqlEnabled,
    write: v => s().setMonacoLanguageSqlEnabled(!!v),
    docKey: 'editor.monaco.languageSql.enabled',
    default: () => true,
  },
  {
    key: 'monacoLanguageSqlLoadMode',
    type: 'string',
    source: 'store',
    read: () => s().monacoLanguageSqlLoadMode,
    write: v => s().setMonacoLanguageSqlLoadMode(v === 'eager' ? 'eager' : 'lazy'),
    docKey: 'editor.monaco.languageSql.loadMode',
    default: () => 'lazy',
    options: ['lazy', 'eager'],
  },
  {
    key: 'monacoLanguageYamlEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoLanguageYamlEnabled,
    write: v => s().setMonacoLanguageYamlEnabled(!!v),
    docKey: 'editor.monaco.languageYaml.enabled',
    default: () => true,
  },
  {
    key: 'monacoLanguageYamlLoadMode',
    type: 'string',
    source: 'store',
    read: () => s().monacoLanguageYamlLoadMode,
    write: v => s().setMonacoLanguageYamlLoadMode(v === 'eager' ? 'eager' : 'lazy'),
    docKey: 'editor.monaco.languageYaml.loadMode',
    default: () => 'lazy',
    options: ['lazy', 'eager'],
  },
  {
    key: 'monacoWorkerJsonEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoWorkerJsonEnabled,
    write: v => s().setMonacoWorkerJsonEnabled(!!v),
    docKey: 'editor.monaco.workerJson.enabled',
    default: () => true,
  },
  {
    key: 'monacoWorkerJsonLoadMode',
    type: 'string',
    source: 'store',
    read: () => s().monacoWorkerJsonLoadMode,
    write: v => s().setMonacoWorkerJsonLoadMode(v === 'eager' ? 'eager' : 'lazy'),
    docKey: 'editor.monaco.workerJson.loadMode',
    default: () => 'lazy',
    options: ['lazy', 'eager'],
  },
  {
    key: 'monacoHoverEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoHoverEnabled,
    write: v => s().setMonacoHoverEnabled(!!v),
    docKey: 'editor.monaco.hover.enabled',
    default: () => false,
  },
  {
    key: 'monacoLinksEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoLinksEnabled,
    write: v => s().setMonacoLinksEnabled(!!v),
    docKey: 'editor.monaco.links.enabled',
    default: () => false,
  },
  {
    key: 'monacoQuickSuggestionsEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoQuickSuggestionsEnabled,
    write: v => s().setMonacoQuickSuggestionsEnabled(!!v),
    docKey: 'editor.monaco.quickSuggestions.enabled',
    default: () => false,
  },
  {
    key: 'monacoSuggestOnTriggerCharactersEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoSuggestOnTriggerCharactersEnabled,
    write: v => s().setMonacoSuggestOnTriggerCharactersEnabled(!!v),
    docKey: 'editor.monaco.suggestOnTriggerCharacters.enabled',
    default: () => false,
  },
  {
    key: 'monacoParameterHintsEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoParameterHintsEnabled,
    write: v => s().setMonacoParameterHintsEnabled(!!v),
    docKey: 'editor.monaco.parameterHints.enabled',
    default: () => false,
  },
  {
    key: 'monacoLineNumbersEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoLineNumbersEnabled,
    write: v => s().setMonacoLineNumbersEnabled(!!v),
    docKey: 'editor.monaco.lineNumbers.enabled',
    default: () => true,
  },
  {
    key: 'monacoFoldingEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoFoldingEnabled,
    write: v => s().setMonacoFoldingEnabled(!!v),
    docKey: 'editor.monaco.folding.enabled',
    default: () => false,
  },
  {
    key: 'monacoMinimapEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoMinimapEnabled,
    write: v => s().setMonacoMinimapEnabled(!!v),
    docKey: 'editor.monaco.minimap.enabled',
    default: () => false,
  },
  {
    key: 'monacoSelectionHighlightEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoSelectionHighlightEnabled,
    write: v => s().setMonacoSelectionHighlightEnabled(!!v),
    docKey: 'editor.monaco.selectionHighlight.enabled',
    default: () => false,
  },
  {
    key: 'monacoOccurrencesHighlightEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoOccurrencesHighlightEnabled,
    write: v => s().setMonacoOccurrencesHighlightEnabled(!!v),
    docKey: 'editor.monaco.occurrencesHighlight.enabled',
    default: () => false,
  },
  {
    key: 'monacoGuidesEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoGuidesEnabled,
    write: v => s().setMonacoGuidesEnabled(!!v),
    docKey: 'editor.monaco.guides.enabled',
    default: () => false,
  },
  {
    key: 'monacoBracketPairColorizationEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoBracketPairColorizationEnabled,
    write: v => s().setMonacoBracketPairColorizationEnabled(!!v),
    docKey: 'editor.monaco.bracketPairColorization.enabled',
    default: () => false,
  },
  {
    key: 'monacoCodeLensEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoCodeLensEnabled,
    write: v => s().setMonacoCodeLensEnabled(!!v),
    docKey: 'editor.monaco.codeLens.enabled',
    default: () => false,
  },
  {
    key: 'monacoLightbulbEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoLightbulbEnabled,
    write: v => s().setMonacoLightbulbEnabled(!!v),
    docKey: 'editor.monaco.lightbulb.enabled',
    default: () => false,
  },
  {
    key: 'monacoInlayHintsEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoInlayHintsEnabled,
    write: v => s().setMonacoInlayHintsEnabled(!!v),
    docKey: 'editor.monaco.inlayHints.enabled',
    default: () => false,
  },
  {
    key: 'monacoWordBasedSuggestionsEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoWordBasedSuggestionsEnabled,
    write: v => s().setMonacoWordBasedSuggestionsEnabled(!!v),
    docKey: 'editor.monaco.wordBasedSuggestions.enabled',
    default: () => false,
  },
  {
    key: 'monacoInlineSuggestEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoInlineSuggestEnabled,
    write: v => s().setMonacoInlineSuggestEnabled(!!v),
    docKey: 'editor.monaco.inlineSuggest.enabled',
    default: () => false,
  },
  {
    key: 'monacoAcceptSuggestionOnEnterEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoAcceptSuggestionOnEnterEnabled,
    write: v => s().setMonacoAcceptSuggestionOnEnterEnabled(!!v),
    docKey: 'editor.monaco.acceptSuggestionOnEnter.enabled',
    default: () => false,
  },
  {
    key: 'monacoDragAndDropEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoDragAndDropEnabled,
    write: v => s().setMonacoDragAndDropEnabled(!!v),
    docKey: 'editor.monaco.dragAndDrop.enabled',
    default: () => false,
  },
  {
    key: 'monacoDropIntoEditorEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoDropIntoEditorEnabled,
    write: v => s().setMonacoDropIntoEditorEnabled(!!v),
    docKey: 'editor.monaco.dropIntoEditor.enabled',
    default: () => false,
  },
  {
    key: 'monacoColorDecoratorsEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoColorDecoratorsEnabled,
    write: v => s().setMonacoColorDecoratorsEnabled(!!v),
    docKey: 'editor.monaco.colorDecorators.enabled',
    default: () => false,
  },
  {
    key: 'monacoUnicodeHighlightEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoUnicodeHighlightEnabled,
    write: v => s().setMonacoUnicodeHighlightEnabled(!!v),
    docKey: 'editor.monaco.unicodeHighlight.enabled',
    default: () => false,
  },
  {
    key: 'monacoMatchBracketsEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoMatchBracketsEnabled,
    write: v => s().setMonacoMatchBracketsEnabled(!!v),
    docKey: 'editor.monaco.matchBrackets.enabled',
    default: () => false,
  },
  {
    key: 'monacoRenderLineHighlightEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoRenderLineHighlightEnabled,
    write: v => s().setMonacoRenderLineHighlightEnabled(!!v),
    docKey: 'editor.monaco.renderLineHighlight.enabled',
    default: () => false,
  },
  {
    key: 'monacoGlyphMarginEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoGlyphMarginEnabled,
    write: v => s().setMonacoGlyphMarginEnabled(!!v),
    docKey: 'editor.monaco.glyphMargin.enabled',
    default: () => false,
  },
  {
    key: 'monacoOverviewRulerLanesEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoOverviewRulerLanesEnabled,
    write: v => s().setMonacoOverviewRulerLanesEnabled(!!v),
    docKey: 'editor.monaco.overviewRulerLanes.enabled',
    default: () => false,
  },
  {
    key: 'monacoLineDecorationsWidthEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoLineDecorationsWidthEnabled,
    write: v => s().setMonacoLineDecorationsWidthEnabled(!!v),
    docKey: 'editor.monaco.lineDecorationsWidth.enabled',
    default: () => false,
  },
  {
    key: 'monacoRenderWhitespaceEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoRenderWhitespaceEnabled,
    write: v => s().setMonacoRenderWhitespaceEnabled(!!v),
    docKey: 'editor.monaco.renderWhitespace.enabled',
    default: () => false,
  },
  {
    key: 'monacoRenderControlCharactersEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoRenderControlCharactersEnabled,
    write: v => s().setMonacoRenderControlCharactersEnabled(!!v),
    docKey: 'editor.monaco.renderControlCharacters.enabled',
    default: () => false,
  },
  {
    key: 'monacoSmoothScrollingEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoSmoothScrollingEnabled,
    write: v => s().setMonacoSmoothScrollingEnabled(!!v),
    docKey: 'editor.monaco.smoothScrolling.enabled',
    default: () => false,
  },
  {
    key: 'monacoScrollBeyondLastLineEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoScrollBeyondLastLineEnabled,
    write: v => s().setMonacoScrollBeyondLastLineEnabled(!!v),
    docKey: 'editor.monaco.scrollBeyondLastLine.enabled',
    default: () => false,
  },
  {
    key: 'monacoMouseWheelZoomEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoMouseWheelZoomEnabled,
    write: v => s().setMonacoMouseWheelZoomEnabled(!!v),
    docKey: 'editor.monaco.mouseWheelZoom.enabled',
    default: () => false,
  },
  {
    key: 'monacoCursorBlinkingEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoCursorBlinkingEnabled,
    write: v => s().setMonacoCursorBlinkingEnabled(!!v),
    docKey: 'editor.monaco.cursorBlinking.enabled',
    default: () => false,
  },
  {
    key: 'monacoCursorSmoothCaretAnimationEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoCursorSmoothCaretAnimationEnabled,
    write: v => s().setMonacoCursorSmoothCaretAnimationEnabled(!!v),
    docKey: 'editor.monaco.cursorSmoothCaretAnimation.enabled',
    default: () => false,
  },
  {
    key: 'monacoWordWrapEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoWordWrapEnabled,
    write: v => s().setMonacoWordWrapEnabled(!!v),
    docKey: 'editor.monaco.wordWrap.enabled',
    default: () => false,
  },
  {
    key: 'monacoWrappingIndentEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoWrappingIndentEnabled,
    write: v => s().setMonacoWrappingIndentEnabled(!!v),
    docKey: 'editor.monaco.wrappingIndent.enabled',
    default: () => false,
  },
  {
    key: 'monacoWrappingStrategyEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoWrappingStrategyEnabled,
    write: v => s().setMonacoWrappingStrategyEnabled(!!v),
    docKey: 'editor.monaco.wrappingStrategy.enabled',
    default: () => false,
  },
  {
    key: 'monacoCursorWidthEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoCursorWidthEnabled,
    write: v => s().setMonacoCursorWidthEnabled(!!v),
    docKey: 'editor.monaco.cursorWidth.enabled',
    default: () => false,
  },
  {
    key: 'monacoCursorStyleEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoCursorStyleEnabled,
    write: v => s().setMonacoCursorStyleEnabled(!!v),
    docKey: 'editor.monaco.cursorStyle.enabled',
    default: () => false,
  },
  {
    key: 'monacoCursorSurroundingLinesEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoCursorSurroundingLinesEnabled,
    write: v => s().setMonacoCursorSurroundingLinesEnabled(!!v),
    docKey: 'editor.monaco.cursorSurroundingLines.enabled',
    default: () => false,
  },
  {
    key: 'monacoCursorSurroundingLinesStyleEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoCursorSurroundingLinesStyleEnabled,
    write: v => s().setMonacoCursorSurroundingLinesStyleEnabled(!!v),
    docKey: 'editor.monaco.cursorSurroundingLinesStyle.enabled',
    default: () => false,
  },
  {
    key: 'monacoCursorHeightEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoCursorHeightEnabled,
    write: v => s().setMonacoCursorHeightEnabled(!!v),
    docKey: 'editor.monaco.cursorHeight.enabled',
    default: () => false,
  },
  {
    key: 'monacoStickyScrollEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoStickyScrollEnabled,
    write: v => s().setMonacoStickyScrollEnabled(!!v),
    docKey: 'editor.monaco.stickyScroll.enabled',
    default: () => false,
  },
  {
    key: 'monacoSelectionClipboardEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoSelectionClipboardEnabled,
    write: v => s().setMonacoSelectionClipboardEnabled(!!v),
    docKey: 'editor.monaco.selectionClipboard.enabled',
    default: () => false,
  },
  {
    key: 'monacoCopyWithSyntaxHighlightingEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoCopyWithSyntaxHighlightingEnabled,
    write: v => s().setMonacoCopyWithSyntaxHighlightingEnabled(!!v),
    docKey: 'editor.monaco.copyWithSyntaxHighlighting.enabled',
    default: () => false,
  },
  {
    key: 'monacoOccurrencesHighlightDelayEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoOccurrencesHighlightDelayEnabled,
    write: v => s().setMonacoOccurrencesHighlightDelayEnabled(!!v),
    docKey: 'editor.monaco.occurrencesHighlightDelay.enabled',
    default: () => false,
  },
  {
    key: 'monacoFormatOnPasteEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoFormatOnPasteEnabled,
    write: v => s().setMonacoFormatOnPasteEnabled(!!v),
    docKey: 'editor.monaco.formatOnPaste.enabled',
    default: () => false,
  },
  {
    key: 'monacoFormatOnTypeEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoFormatOnTypeEnabled,
    write: v => s().setMonacoFormatOnTypeEnabled(!!v),
    docKey: 'editor.monaco.formatOnType.enabled',
    default: () => false,
  },
  {
    key: 'monacoAutoClosingBracketsEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoAutoClosingBracketsEnabled,
    write: v => s().setMonacoAutoClosingBracketsEnabled(!!v),
    docKey: 'editor.monaco.autoClosingBrackets.enabled',
    default: () => false,
  },
  {
    key: 'monacoAutoClosingQuotesEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoAutoClosingQuotesEnabled,
    write: v => s().setMonacoAutoClosingQuotesEnabled(!!v),
    docKey: 'editor.monaco.autoClosingQuotes.enabled',
    default: () => false,
  },
  {
    key: 'monacoAutoIndentEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoAutoIndentEnabled,
    write: v => s().setMonacoAutoIndentEnabled(!!v),
    docKey: 'editor.monaco.autoIndent.enabled',
    default: () => false,
  },
  {
    key: 'monacoAutoSurroundEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoAutoSurroundEnabled,
    write: v => s().setMonacoAutoSurroundEnabled(!!v),
    docKey: 'editor.monaco.autoSurround.enabled',
    default: () => false,
  },
  {
    key: 'monacoMatchOnWordStartOnlyEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoMatchOnWordStartOnlyEnabled,
    write: v => s().setMonacoMatchOnWordStartOnlyEnabled(!!v),
    docKey: 'editor.monaco.matchOnWordStartOnly.enabled',
    default: () => false,
  },
  {
    key: 'monacoFindSeedSearchStringFromSelectionEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoFindSeedSearchStringFromSelectionEnabled,
    write: v => s().setMonacoFindSeedSearchStringFromSelectionEnabled(!!v),
    docKey: 'editor.monaco.find.seedSearchStringFromSelection.enabled',
    default: () => false,
  },
  {
    key: 'monacoFindCursorMoveOnTypeEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoFindCursorMoveOnTypeEnabled,
    write: v => s().setMonacoFindCursorMoveOnTypeEnabled(!!v),
    docKey: 'editor.monaco.find.cursorMoveOnType.enabled',
    default: () => false,
  },
  {
    key: 'monacoFindFindOnTypeEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoFindFindOnTypeEnabled,
    write: v => s().setMonacoFindFindOnTypeEnabled(!!v),
    docKey: 'editor.monaco.find.findOnType.enabled',
    default: () => false,
  },
  {
    key: 'monacoFindLoopEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoFindLoopEnabled,
    write: v => s().setMonacoFindLoopEnabled(!!v),
    docKey: 'editor.monaco.find.loop.enabled',
    default: () => false,
  },
  {
    key: 'monacoAutoClosingDeleteEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoAutoClosingDeleteEnabled,
    write: v => s().setMonacoAutoClosingDeleteEnabled(!!v),
    docKey: 'editor.monaco.autoClosingDelete.enabled',
    default: () => false,
  },
  {
    key: 'monacoAutoClosingCommentsEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoAutoClosingCommentsEnabled,
    write: v => s().setMonacoAutoClosingCommentsEnabled(!!v),
    docKey: 'editor.monaco.autoClosingComments.enabled',
    default: () => false,
  },
  {
    key: 'monacoEmptySelectionClipboardEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoEmptySelectionClipboardEnabled,
    write: v => s().setMonacoEmptySelectionClipboardEnabled(!!v),
    docKey: 'editor.monaco.emptySelectionClipboard.enabled',
    default: () => false,
  },
  {
    key: 'monacoColumnSelectionEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoColumnSelectionEnabled,
    write: v => s().setMonacoColumnSelectionEnabled(!!v),
    docKey: 'editor.monaco.columnSelection.enabled',
    default: () => false,
  },
  {
    key: 'monacoWordSeparatorsEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoWordSeparatorsEnabled,
    write: v => s().setMonacoWordSeparatorsEnabled(!!v),
    docKey: 'editor.monaco.wordSeparators.enabled',
    default: () => false,
  },
  {
    key: 'monacoMultiCursorModifierEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoMultiCursorModifierEnabled,
    write: v => s().setMonacoMultiCursorModifierEnabled(!!v),
    docKey: 'editor.monaco.multiCursorModifier.enabled',
    default: () => false,
  },
  {
    key: 'monacoMultiCursorMergeOverlappingEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoMultiCursorMergeOverlappingEnabled,
    write: v => s().setMonacoMultiCursorMergeOverlappingEnabled(!!v),
    docKey: 'editor.monaco.multiCursorMergeOverlapping.enabled',
    default: () => false,
  },
  {
    key: 'monacoMultiCursorPasteEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoMultiCursorPasteEnabled,
    write: v => s().setMonacoMultiCursorPasteEnabled(!!v),
    docKey: 'editor.monaco.multiCursorPaste.enabled',
    default: () => false,
  },
  {
    key: 'monacoAutoClosingOvertypeEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoAutoClosingOvertypeEnabled,
    write: v => s().setMonacoAutoClosingOvertypeEnabled(!!v),
    docKey: 'editor.monaco.autoClosingOvertype.enabled',
    default: () => false,
  },
]
