import { useGraphStore } from '@/hooks/useGraphStore'
import type { SettingMeta } from './types'
import { UI_THEME_TOKENS } from '@/lib/ui/theme-tokens'
import type { ThemeMode } from '@/lib/ui/theme'
import { LS_KEYS } from '@/lib/config'
import { lsBool, lsSetBool } from '@/lib/persistence'
import {
  CHAT_DEFAULT_ENDPOINT_URL,
  CHAT_DEFAULT_MODEL,
  CHAT_PROVIDER_OPTIONS,
  CHAT_OPENAI_MODEL_OPTIONS,
  CHAT_LOCAL_MODEL_OPTIONS,
  normalizeChatEndpointUrlInput,
} from '@/lib/chatEndpoint'
import { DEFAULT_INTEGRATION_CONFIGS, stringifyIntegrationConfigs } from '@/features/integrations/config'

const s = () => useGraphStore.getState()

export const uiUiSettingsRegistry: SettingMeta[] = [
  {
    key: 'startup.openWorkflowPanel',
    type: 'boolean',
    source: 'localStorage',
    read: () => lsBool(LS_KEYS.startupOpenWorkflowPanel, false),
    write: (v) => {
      lsSetBool(LS_KEYS.startupOpenWorkflowPanel, Boolean(v))
    },
    docKey: 'startup.openWorkflowPanel',
    default: () => false,
  },
  {
    key: 'uiOverlayOpacity',
    type: 'number',
    source: 'store',
    read: () => s().uiOverlayOpacity,
    write: (v) => s().setUiOverlayOpacity(Number(v)),
    docKey: 'overlayOpacity',
    default: () => 0.95,
  },
  {
    key: 'uiPanelOpacity',
    type: 'number',
    source: 'store',
    read: () => s().uiPanelOpacity,
    write: (v) => s().setUiPanelOpacity(Number(v)),
    docKey: 'panelOpacity',
    default: () => 0.95,
  },
  {
    key: 'uiToolbarOpacity',
    type: 'number',
    source: 'store',
    read: () => s().uiToolbarOpacity,
    write: (v) => s().setUiToolbarOpacity(Number(v)),
    docKey: 'toolbarOpacity',
    default: () => 0.95,
  },
  {
    key: 'selectionFlashDurationMs',
    type: 'number',
    source: 'store',
    read: () => s().selectionFlashDurationMs,
    write: v => s().setSelectionFlashDurationMs(Number(v)),
    docKey: 'selectionFlashDurationMs',
    default: () => 500,
  },
  {
    key: 'selectionFlashOpacity',
    type: 'number',
    source: 'store',
    read: () => s().selectionFlashOpacity,
    write: v => s().setSelectionFlashOpacity(Number(v)),
    docKey: 'selectionFlashOpacity',
    default: () => 0.18,
  },
  {
    key: 'uiIconScale',
    type: 'string',
    source: 'store',
    read: () => s().uiIconScale,
    write: (v) => {
      const raw = String(v || '')
      const scale: 'compact' | 'default' = raw === 'compact' ? 'compact' : 'default'
      s().setUiIconScale(scale)
    },
    docKey: 'uiIconScale',
    default: () => 'default',
    options: ['default', 'compact'],
  },
  {
    key: 'uiPanelTextFontClass',
    type: 'string',
    source: 'store',
    read: () => s().uiPanelTextFontClass,
    write: (v) => s().setUiPanelTextFontClass(String(v || '')),
    docKey: 'uiPanelTextFontClass',
    default: () => 'font-sans',
  },
  {
    key: 'uiPanelKeyValueTextSizeClass',
    type: 'string',
    source: 'store',
    read: () => s().uiPanelKeyValueTextSizeClass,
    write: (v) => s().setUiPanelKeyValueTextSizeClass(String(v || '')),
    docKey: 'uiPanelKeyValueTextSizeClass',
    default: () => 'text-sm',
  },
  {
    key: 'uiPanelKeyValueInputClass',
    type: 'string',
    source: 'store',
    read: () => s().uiPanelKeyValueInputClass,
    write: (v) => s().setUiPanelKeyValueInputClass(String(v || '')),
    docKey: 'uiPanelKeyValueInputClass',
    default: () => 'w-full h-6 px-2 text-sm border border-gray-300 rounded text-right',
  },
  {
    key: 'uiPanelMonospaceTextClass',
    type: 'string',
    source: 'store',
    read: () => s().uiPanelMonospaceTextClass,
    write: (v) => s().setUiPanelMonospaceTextClass(String(v || '')),
    docKey: 'uiPanelMonospaceTextClass',
    default: () => 'font-mono text-xs',
  },
  {
    key: 'uiPanelRowDensityDefaultClass',
    type: 'string',
    source: 'store',
    read: () => s().uiPanelRowDensityDefaultClass,
    write: (v) => s().setUiPanelRowDensityDefaultClass(String(v || '')),
    docKey: 'uiPanelRowDensityDefaultClass',
    default: () => 'py-1',
  },
  {
    key: 'uiHeaderRowHeightClass',
    type: 'string',
    source: 'store',
    read: () => s().uiHeaderRowHeightClass,
    write: (v) => s().setUiHeaderRowHeightClass(String(v || '')),
    docKey: 'uiHeaderRowHeightClass',
    default: () => 'min-h-[36px]',
  },
  {
    key: 'uiHeaderRowPaddingClass',
    type: 'string',
    source: 'store',
    read: () => s().uiHeaderRowPaddingClass,
    write: (v) => s().setUiHeaderRowPaddingClass(String(v || '')),
    docKey: 'uiHeaderRowPaddingClass',
    default: () => 'py-1',
  },
  {
    key: 'uiSectionHeaderRowHeightClass',
    type: 'string',
    source: 'store',
    read: () => s().uiSectionHeaderRowHeightClass,
    write: (v) => s().setUiSectionHeaderRowHeightClass(String(v || '')),
    docKey: 'uiSectionHeaderRowHeightClass',
    default: () => 'min-h-[36px]',
  },
  {
    key: 'uiSectionHeaderRowPaddingClass',
    type: 'string',
    source: 'store',
    read: () => s().uiSectionHeaderRowPaddingClass,
    write: (v) => s().setUiSectionHeaderRowPaddingClass(String(v || '')),
    docKey: 'uiSectionHeaderRowPaddingClass',
    default: () => 'py-1',
  },
  {
    key: 'uiIconFormat',
    type: 'string',
    source: 'store',
    read: () => s().uiIconFormat,
    write: (v) => {
      const raw = String(v || '')
      const format: 'default' | 'minimal' | '1' =
        raw === 'minimal' ? 'minimal' : raw === '1' ? '1' : 'default'
      s().setUiIconFormat(format)
    },
    docKey: 'uiIconFormat',
    default: () => '1',
    options: ['1', 'default', 'minimal'],
  },
  {
    key: 'uiIconStrokeWidth',
    type: 'number',
    source: 'store',
    read: () => s().uiIconStrokeWidth,
    write: (v) => s().setUiIconStrokeWidth(Number(v)),
    docKey: 'uiIconStrokeWidth',
    default: () => 2,
  },
  {
    key: 'uiIconColorClass',
    type: 'string',
    source: 'store',
    read: () => s().uiIconColorClass,
    write: (v) => s().setUiIconColorClass(String(v || '')),
    docKey: 'uiIconColorClass',
    default: () => UI_THEME_TOKENS.icon.color,
  },
  {
    key: 'uiIconHoverBgClass',
    type: 'string',
    source: 'store',
    read: () => s().uiIconHoverBgClass,
    write: (v) => s().setUiIconHoverBgClass(String(v || '')),
    docKey: 'uiIconHoverBgClass',
    default: () => UI_THEME_TOKENS.button.hoverBg,
  },
  {
    key: 'uiIconButtonPaddingClass',
    type: 'string',
    source: 'store',
    read: () => s().uiIconButtonPaddingClass,
    write: (v) => s().setUiIconButtonPaddingClass(String(v || '')),
    docKey: 'uiIconButtonPaddingClass',
    default: () => 'p-2',
  },
  {
    key: 'uiIconPillClass',
    type: 'string',
    source: 'store',
    read: () => s().uiIconPillClass,
    write: (v) => s().setUiIconPillClass(String(v || '')),
    docKey: 'uiIconPillClass',
    default: () =>
      `inline-flex items-center justify-center rounded border ${UI_THEME_TOKENS.panel.border} ${UI_THEME_TOKENS.panel.headerBg} px-1.5 py-0.5`,
  },
  {
    key: 'uiIconPillLegendTextSizeClass',
    type: 'string',
    source: 'store',
    read: () => s().uiIconPillLegendTextSizeClass,
    write: (v) => s().setUiIconPillLegendTextSizeClass(String(v || '')),
    docKey: 'uiIconPillLegendTextSizeClass',
    default: () => 'text-xs',
  },
  {
    key: 'uiIconPillBadgeTextSizeClass',
    type: 'string',
    source: 'store',
    read: () => s().uiIconPillBadgeTextSizeClass,
    write: (v) => s().setUiIconPillBadgeTextSizeClass(String(v || '')),
    docKey: 'uiIconPillBadgeTextSizeClass',
    default: () => 'text-[9px]',
  },
  {
    key: 'uiIconBadgeChipClass',
    type: 'string',
    source: 'store',
    read: () => s().uiIconBadgeChipClass,
    write: (v) => s().setUiIconBadgeChipClass(String(v || '')),
    docKey: 'uiIconBadgeChipClass',
    default: () => 'px-1 py-[1px] rounded-full border',
  },
  {
    key: 'uiIconBadgeChipTextSizeClass',
    type: 'string',
    source: 'store',
    read: () => s().uiIconBadgeChipTextSizeClass,
    write: (v) => s().setUiIconBadgeChipTextSizeClass(String(v || '')),
    docKey: 'uiIconBadgeChipTextSizeClass',
    default: () => 'text-[9px]',
  },
  {
    key: 'uiPanelMicroLabelTextSizeClass',
    type: 'string',
    source: 'store',
    read: () => s().uiPanelMicroLabelTextSizeClass,
    write: (v) => s().setUiPanelMicroLabelTextSizeClass(String(v || '')),
    docKey: 'uiPanelMicroLabelTextSizeClass',
    default: () => '',
  },
  {
    key: 'uiIconAnimationEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().uiIconAnimationEnabled,
    write: (v) => s().setUiIconAnimationEnabled(Boolean(v)),
    docKey: 'uiIconAnimationEnabled',
    default: () => true,
  },
  {
    key: 'themeMode',
    type: 'string',
    source: 'store',
    read: () => s().themeMode,
    write: (v) => {
      const raw = String(v || '')
      const next: ThemeMode =
        raw === 'light' || raw === 'dark' || raw === 'system' ? raw : 'system'
      s().setThemeMode(next)
    },
    docKey: 'themeMode',
    default: () => 'system',
    options: ['light', 'dark', 'system'],
  },
  {
    key: 'floatingPanelWidthRatio',
    type: 'number',
    source: 'localStorage',
    read: () => s().floatingPanelWidthRatio,
    write: (v) => s().setFloatingPanelWidthRatio(Number(v)),
    docKey: 'floatingPanelWidthRatio',
    default: () => 0.25,
  },
  {
    key: 'floatingPanelHeightRatio',
    type: 'number',
    source: 'localStorage',
    read: () => s().floatingPanelHeightRatio,
    write: (v) => s().setFloatingPanelHeightRatio(Number(v)),
    docKey: 'floatingPanelHeightRatio',
    default: () => 0.5,
  },
  {
    key: 'floatingPanelZIndex',
    type: 'number',
    source: 'localStorage',
    read: () => s().floatingPanelZIndex,
    write: (v) => s().setFloatingPanelZIndex(Number(v)),
    docKey: 'floatingPanelZIndex',
    default: () => 5000,
  },
  {
    key: 'enableLaunchSpotlight',
    type: 'boolean',
    source: 'store',
    read: () => s().enableLaunchSpotlight,
    write: (v) => s().setEnableLaunchSpotlight(Boolean(v)),
    docKey: 'enableLaunchSpotlight',
    default: () => false,
  },
  {
    key: 'spotlight.margin',
    type: 'number',
    source: 'store',
    read: () => s().spotlightMargin,
    write: (v) => s().setSpotlightMargin(Number(v)),
    docKey: 'spotlight.margin',
    default: () => 8,
  },
  {
    key: 'spotlight.nearTopThreshold',
    type: 'number',
    source: 'store',
    read: () => s().spotlightNearTopThreshold,
    write: (v) => s().setSpotlightNearTopThreshold(Number(v)),
    docKey: 'spotlight.nearTopThreshold',
    default: () => 96,
  },
  {
    key: 'chatProvider',
    type: 'string',
    source: 'localStorage',
    read: () => s().chatProvider,
    write: (v) => s().setChatProvider(String(v || '').trim()),
    docKey: 'chatProvider',
    default: () => CHAT_PROVIDER_OPTIONS[0],
    options: [...CHAT_PROVIDER_OPTIONS],
  },
  {
    key: 'chatEndpointUrl',
    type: 'string',
    source: 'localStorage',
    read: () => s().chatEndpointUrl,
    write: (v) => s().setChatEndpointUrl(String(v || '').trim() || null),
    docKey: 'chatEndpointUrl',
    default: () => normalizeChatEndpointUrlInput(null, s().chatProvider),
  },
  {
    key: 'chatApiKey',
    type: 'string',
    source: 'store',
    read: () => s().chatApiKey,
    write: (v) => s().setChatApiKey(String(v || '').trim() || null),
    docKey: 'chatApiKey',
    default: () => '',
  },
  {
    key: 'chatModel',
    type: 'string',
    source: 'localStorage',
    read: () => s().chatModel,
    write: (v) => s().setChatModel(String(v || '').trim() || CHAT_DEFAULT_MODEL),
    docKey: 'chatModel',
    default: () => CHAT_DEFAULT_MODEL,
    options: [...CHAT_OPENAI_MODEL_OPTIONS, ...CHAT_LOCAL_MODEL_OPTIONS],
  },
  {
    key: 'chatTemperature',
    type: 'number',
    source: 'localStorage',
    read: () => s().chatTemperature,
    write: (v) => s().setChatTemperature(Number(v)),
    docKey: 'chatTemperature',
    default: () => 0.3,
  },
  {
    key: 'chatSystemPrompt',
    type: 'string',
    source: 'localStorage',
    read: () => s().chatSystemPrompt,
    write: (v) => s().setChatSystemPrompt(String(v || '').trim() || null),
    docKey: 'chatSystemPrompt',
    default: () => null,
  },
  {
    key: 'chatHistoryWorkspacePath',
    type: 'string',
    source: 'localStorage',
    read: () => s().chatHistoryWorkspacePath,
    write: (v) => s().setChatHistoryWorkspacePath(String(v || '').trim() || null),
    docKey: 'chatHistoryWorkspacePath',
    default: () => null,
  },
  {
    key: 'chatContextScope',
    type: 'string',
    source: 'localStorage',
    read: () => s().chatContextScope,
    write: (v) =>
      s().setChatContextScope(
        String(v || '').trim() === 'selection'
          ? 'selection'
          : String(v || '').trim() === 'hybrid'
            ? 'hybrid'
            : 'workspace',
      ),
    docKey: 'chatContextScope',
    default: () => 'workspace',
    options: ['selection', 'workspace', 'hybrid'],
  },
  {
    key: 'integrationConfigsJson',
    type: 'string',
    source: 'localStorage',
    read: () => s().integrationConfigsJson,
    write: (v) => s().setIntegrationConfigsJson(String(v || '').trim() || null),
    docKey: 'integrationConfigsJson',
    default: () => stringifyIntegrationConfigs(DEFAULT_INTEGRATION_CONFIGS),
  },
];
