import { useGraphStore } from '@/hooks/useGraphStore'
import type { SettingMeta } from './types'

const s = () => useGraphStore.getState()

export const uiMonacoSettingsRegistry: SettingMeta[] = [
  {
    key: 'monacoLanguageJsonEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoLanguageJsonEnabled,
    write: v => s().setMonacoLanguageJsonEnabled(!!v),
    docKey: 'editor.monaco.languageJson.enabled',
    default: () => true,
  },
  {
    key: 'monacoLanguageJsonLoadMode',
    type: 'string',
    source: 'store',
    read: () => s().monacoLanguageJsonLoadMode,
    write: v => s().setMonacoLanguageJsonLoadMode(v === 'eager' ? 'eager' : 'lazy'),
    docKey: 'editor.monaco.languageJson.loadMode',
    default: () => 'lazy',
    options: ['lazy', 'eager'],
  },
  {
    key: 'monacoLanguageSqlEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoLanguageSqlEnabled,
    write: v => s().setMonacoLanguageSqlEnabled(!!v),
    docKey: 'editor.monaco.languageSql.enabled',
    default: () => true,
  },
  {
    key: 'monacoLanguageSqlLoadMode',
    type: 'string',
    source: 'store',
    read: () => s().monacoLanguageSqlLoadMode,
    write: v => s().setMonacoLanguageSqlLoadMode(v === 'eager' ? 'eager' : 'lazy'),
    docKey: 'editor.monaco.languageSql.loadMode',
    default: () => 'lazy',
    options: ['lazy', 'eager'],
  },
  {
    key: 'monacoLanguageYamlEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoLanguageYamlEnabled,
    write: v => s().setMonacoLanguageYamlEnabled(!!v),
    docKey: 'editor.monaco.languageYaml.enabled',
    default: () => true,
  },
  {
    key: 'monacoLanguageYamlLoadMode',
    type: 'string',
    source: 'store',
    read: () => s().monacoLanguageYamlLoadMode,
    write: v => s().setMonacoLanguageYamlLoadMode(v === 'eager' ? 'eager' : 'lazy'),
    docKey: 'editor.monaco.languageYaml.loadMode',
    default: () => 'lazy',
    options: ['lazy', 'eager'],
  },
  {
    key: 'monacoWorkerJsonEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoWorkerJsonEnabled,
    write: v => s().setMonacoWorkerJsonEnabled(!!v),
    docKey: 'editor.monaco.workerJson.enabled',
    default: () => true,
  },
  {
    key: 'monacoWorkerJsonLoadMode',
    type: 'string',
    source: 'store',
    read: () => s().monacoWorkerJsonLoadMode,
    write: v => s().setMonacoWorkerJsonLoadMode(v === 'eager' ? 'eager' : 'lazy'),
    docKey: 'editor.monaco.workerJson.loadMode',
    default: () => 'lazy',
    options: ['lazy', 'eager'],
  },
  {
    key: 'monacoHoverEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoHoverEnabled,
    write: v => s().setMonacoHoverEnabled(!!v),
    docKey: 'editor.monaco.hover.enabled',
    default: () => false,
  },
  {
    key: 'monacoLinksEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoLinksEnabled,
    write: v => s().setMonacoLinksEnabled(!!v),
    docKey: 'editor.monaco.links.enabled',
    default: () => false,
  },
  {
    key: 'monacoQuickSuggestionsEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoQuickSuggestionsEnabled,
    write: v => s().setMonacoQuickSuggestionsEnabled(!!v),
    docKey: 'editor.monaco.quickSuggestions.enabled',
    default: () => false,
  },
  {
    key: 'monacoSuggestOnTriggerCharactersEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoSuggestOnTriggerCharactersEnabled,
    write: v => s().setMonacoSuggestOnTriggerCharactersEnabled(!!v),
    docKey: 'editor.monaco.suggestOnTriggerCharacters.enabled',
    default: () => false,
  },
  {
    key: 'monacoParameterHintsEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoParameterHintsEnabled,
    write: v => s().setMonacoParameterHintsEnabled(!!v),
    docKey: 'editor.monaco.parameterHints.enabled',
    default: () => false,
  },
  {
    key: 'monacoLineNumbersEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoLineNumbersEnabled,
    write: v => s().setMonacoLineNumbersEnabled(!!v),
    docKey: 'editor.monaco.lineNumbers.enabled',
    default: () => true,
  },
  {
    key: 'monacoFoldingEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoFoldingEnabled,
    write: v => s().setMonacoFoldingEnabled(!!v),
    docKey: 'editor.monaco.folding.enabled',
    default: () => false,
  },
  {
    key: 'monacoMinimapEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoMinimapEnabled,
    write: v => s().setMonacoMinimapEnabled(!!v),
    docKey: 'editor.monaco.minimap.enabled',
    default: () => false,
  },
  {
    key: 'monacoSelectionHighlightEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoSelectionHighlightEnabled,
    write: v => s().setMonacoSelectionHighlightEnabled(!!v),
    docKey: 'editor.monaco.selectionHighlight.enabled',
    default: () => false,
  },
  {
    key: 'monacoOccurrencesHighlightEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoOccurrencesHighlightEnabled,
    write: v => s().setMonacoOccurrencesHighlightEnabled(!!v),
    docKey: 'editor.monaco.occurrencesHighlight.enabled',
    default: () => false,
  },
  {
    key: 'monacoGuidesEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoGuidesEnabled,
    write: v => s().setMonacoGuidesEnabled(!!v),
    docKey: 'editor.monaco.guides.enabled',
    default: () => false,
  },
  {
    key: 'monacoBracketPairColorizationEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoBracketPairColorizationEnabled,
    write: v => s().setMonacoBracketPairColorizationEnabled(!!v),
    docKey: 'editor.monaco.bracketPairColorization.enabled',
    default: () => false,
  },
  {
    key: 'monacoCodeLensEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoCodeLensEnabled,
    write: v => s().setMonacoCodeLensEnabled(!!v),
    docKey: 'editor.monaco.codeLens.enabled',
    default: () => false,
  },
  {
    key: 'monacoLightbulbEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoLightbulbEnabled,
    write: v => s().setMonacoLightbulbEnabled(!!v),
    docKey: 'editor.monaco.lightbulb.enabled',
    default: () => false,
  },
  {
    key: 'monacoInlayHintsEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoInlayHintsEnabled,
    write: v => s().setMonacoInlayHintsEnabled(!!v),
    docKey: 'editor.monaco.inlayHints.enabled',
    default: () => false,
  },
  {
    key: 'monacoWordBasedSuggestionsEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoWordBasedSuggestionsEnabled,
    write: v => s().setMonacoWordBasedSuggestionsEnabled(!!v),
    docKey: 'editor.monaco.wordBasedSuggestions.enabled',
    default: () => false,
  },
  {
    key: 'monacoInlineSuggestEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoInlineSuggestEnabled,
    write: v => s().setMonacoInlineSuggestEnabled(!!v),
    docKey: 'editor.monaco.inlineSuggest.enabled',
    default: () => false,
  },
  {
    key: 'monacoAcceptSuggestionOnEnterEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoAcceptSuggestionOnEnterEnabled,
    write: v => s().setMonacoAcceptSuggestionOnEnterEnabled(!!v),
    docKey: 'editor.monaco.acceptSuggestionOnEnter.enabled',
    default: () => false,
  },
  {
    key: 'monacoDragAndDropEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoDragAndDropEnabled,
    write: v => s().setMonacoDragAndDropEnabled(!!v),
    docKey: 'editor.monaco.dragAndDrop.enabled',
    default: () => false,
  },
  {
    key: 'monacoDropIntoEditorEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoDropIntoEditorEnabled,
    write: v => s().setMonacoDropIntoEditorEnabled(!!v),
    docKey: 'editor.monaco.dropIntoEditor.enabled',
    default: () => false,
  },
  {
    key: 'monacoColorDecoratorsEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().monacoColorDecoratorsEnabled,
    write: v => s().setMonacoColorDecoratorsEnabled(!!v),
    docKey: 'editor.monaco.colorDecorators.enabled',
    default: () => false,
  },
]
