import { useGraphStore } from '@/hooks/useGraphStore'
import type { SettingMeta } from './types'

const s = () => useGraphStore.getState()

export const uiUiSettingsRegistry: SettingMeta[] = [
  {
    key: 'uiOverlayOpacity',
    type: 'number',
    source: 'store',
    read: () => s().uiOverlayOpacity,
    write: (v) => s().setUiOverlayOpacity(Number(v)),
    docKey: 'overlayOpacity',
    default: () => 0.95,
  },
  {
    key: 'uiPanelOpacity',
    type: 'number',
    source: 'store',
    read: () => s().uiPanelOpacity,
    write: (v) => s().setUiPanelOpacity(Number(v)),
    docKey: 'panelOpacity',
    default: () => 0.95,
  },
  {
    key: 'uiToolbarOpacity',
    type: 'number',
    source: 'store',
    read: () => s().uiToolbarOpacity,
    write: (v) => s().setUiToolbarOpacity(Number(v)),
    docKey: 'toolbarOpacity',
    default: () => 0.95,
  },
  {
    key: 'uiIconScale',
    type: 'string',
    source: 'store',
    read: () => s().uiIconScale,
    write: (v) => {
      const raw = String(v || '')
      const scale: 'compact' | 'default' = raw === 'compact' ? 'compact' : 'default'
      s().setUiIconScale(scale)
    },
    docKey: 'uiIconScale',
    default: () => 'default',
    options: ['default', 'compact'],
  },
  {
    key: 'uiPanelTextFontClass',
    type: 'string',
    source: 'store',
    read: () => s().uiPanelTextFontClass,
    write: (v) => s().setUiPanelTextFontClass(String(v || '')),
    docKey: 'uiPanelTextFontClass',
    default: () => 'font-sans',
  },
  {
    key: 'uiPanelKeyValueTextSizeClass',
    type: 'string',
    source: 'store',
    read: () => s().uiPanelKeyValueTextSizeClass,
    write: (v) => s().setUiPanelKeyValueTextSizeClass(String(v || '')),
    docKey: 'uiPanelKeyValueTextSizeClass',
    default: () => 'text-sm',
  },
  {
    key: 'uiPanelKeyValueInputClass',
    type: 'string',
    source: 'store',
    read: () => s().uiPanelKeyValueInputClass,
    write: (v) => s().setUiPanelKeyValueInputClass(String(v || '')),
    docKey: 'uiPanelKeyValueInputClass',
    default: () => 'w-full h-6 px-2 text-sm border border-gray-300 rounded text-right',
  },
  {
    key: 'uiPanelMonospaceTextClass',
    type: 'string',
    source: 'store',
    read: () => s().uiPanelMonospaceTextClass,
    write: (v) => s().setUiPanelMonospaceTextClass(String(v || '')),
    docKey: 'uiPanelMonospaceTextClass',
    default: () => 'font-mono text-xs',
  },
  {
    key: 'uiPanelRowDensityDefaultClass',
    type: 'string',
    source: 'store',
    read: () => s().uiPanelRowDensityDefaultClass,
    write: (v) => s().setUiPanelRowDensityDefaultClass(String(v || '')),
    docKey: 'uiPanelRowDensityDefaultClass',
    default: () => 'py-1',
  },
  {
    key: 'uiHeaderRowHeightClass',
    type: 'string',
    source: 'store',
    read: () => s().uiHeaderRowHeightClass,
    write: (v) => s().setUiHeaderRowHeightClass(String(v || '')),
    docKey: 'uiHeaderRowHeightClass',
    default: () => 'min-h-[36px]',
  },
  {
    key: 'uiHeaderRowPaddingClass',
    type: 'string',
    source: 'store',
    read: () => s().uiHeaderRowPaddingClass,
    write: (v) => s().setUiHeaderRowPaddingClass(String(v || '')),
    docKey: 'uiHeaderRowPaddingClass',
    default: () => 'py-1',
  },
  {
    key: 'uiSectionHeaderRowHeightClass',
    type: 'string',
    source: 'store',
    read: () => s().uiSectionHeaderRowHeightClass,
    write: (v) => s().setUiSectionHeaderRowHeightClass(String(v || '')),
    docKey: 'uiSectionHeaderRowHeightClass',
    default: () => 'min-h-[36px]',
  },
  {
    key: 'uiSectionHeaderRowPaddingClass',
    type: 'string',
    source: 'store',
    read: () => s().uiSectionHeaderRowPaddingClass,
    write: (v) => s().setUiSectionHeaderRowPaddingClass(String(v || '')),
    docKey: 'uiSectionHeaderRowPaddingClass',
    default: () => 'py-1',
  },
  {
    key: 'uiIconFormat',
    type: 'string',
    source: 'store',
    read: () => s().uiIconFormat,
    write: (v) => {
      const raw = String(v || '')
      const format: 'default' | 'minimal' | '1' =
        raw === 'minimal' ? 'minimal' : raw === '1' ? '1' : 'default'
      s().setUiIconFormat(format)
    },
    docKey: 'uiIconFormat',
    default: () => '1',
    options: ['1', 'default', 'minimal'],
  },
  {
    key: 'uiIconStrokeWidth',
    type: 'number',
    source: 'store',
    read: () => s().uiIconStrokeWidth,
    write: (v) => s().setUiIconStrokeWidth(Number(v)),
    docKey: 'uiIconStrokeWidth',
    default: () => 2,
  },
  {
    key: 'uiIconColorClass',
    type: 'string',
    source: 'store',
    read: () => s().uiIconColorClass,
    write: (v) => s().setUiIconColorClass(String(v || '')),
    docKey: 'uiIconColorClass',
    default: () => 'text-gray-600',
  },
  {
    key: 'uiIconHoverBgClass',
    type: 'string',
    source: 'store',
    read: () => s().uiIconHoverBgClass,
    write: (v) => s().setUiIconHoverBgClass(String(v || '')),
    docKey: 'uiIconHoverBgClass',
    default: () => 'hover:bg-gray-100',
  },
  {
    key: 'uiIconButtonPaddingClass',
    type: 'string',
    source: 'store',
    read: () => s().uiIconButtonPaddingClass,
    write: (v) => s().setUiIconButtonPaddingClass(String(v || '')),
    docKey: 'uiIconButtonPaddingClass',
    default: () => 'p-2',
  },
  {
    key: 'uiIconPillClass',
    type: 'string',
    source: 'store',
    read: () => s().uiIconPillClass,
    write: (v) => s().setUiIconPillClass(String(v || '')),
    docKey: 'uiIconPillClass',
    default: () =>
      'inline-flex items-center justify-center rounded border border-gray-200 bg-gray-50 px-1.5 py-0.5',
  },
  {
    key: 'uiIconPillLegendTextSizeClass',
    type: 'string',
    source: 'store',
    read: () => s().uiIconPillLegendTextSizeClass,
    write: (v) => s().setUiIconPillLegendTextSizeClass(String(v || '')),
    docKey: 'uiIconPillLegendTextSizeClass',
    default: () => 'text-xs',
  },
  {
    key: 'uiIconPillBadgeTextSizeClass',
    type: 'string',
    source: 'store',
    read: () => s().uiIconPillBadgeTextSizeClass,
    write: (v) => s().setUiIconPillBadgeTextSizeClass(String(v || '')),
    docKey: 'uiIconPillBadgeTextSizeClass',
    default: () => 'text-[9px]',
  },
  {
    key: 'uiIconBadgeChipClass',
    type: 'string',
    source: 'store',
    read: () => s().uiIconBadgeChipClass,
    write: (v) => s().setUiIconBadgeChipClass(String(v || '')),
    docKey: 'uiIconBadgeChipClass',
    default: () => 'px-1 py-[1px] rounded-full border',
  },
  {
    key: 'uiIconBadgeChipTextSizeClass',
    type: 'string',
    source: 'store',
    read: () => s().uiIconBadgeChipTextSizeClass,
    write: (v) => s().setUiIconBadgeChipTextSizeClass(String(v || '')),
    docKey: 'uiIconBadgeChipTextSizeClass',
    default: () => 'text-[9px]',
  },
  {
    key: 'uiPanelMicroLabelTextSizeClass',
    type: 'string',
    source: 'store',
    read: () => s().uiPanelMicroLabelTextSizeClass,
    write: (v) => s().setUiPanelMicroLabelTextSizeClass(String(v || '')),
    docKey: 'uiPanelMicroLabelTextSizeClass',
    default: () => '',
  },
  {
    key: 'uiIconAnimationEnabled',
    type: 'boolean',
    source: 'store',
    read: () => s().uiIconAnimationEnabled,
    write: (v) => s().setUiIconAnimationEnabled(Boolean(v)),
    docKey: 'uiIconAnimationEnabled',
    default: () => true,
  },
  {
    key: 'bottomPanelHeightRatio',
    type: 'number',
    source: 'localStorage',
    read: () => s().bottomPanelHeightRatio,
    write: (v) => s().setBottomPanelHeightRatio(Number(v)),
    docKey: 'bottomPanelHeight',
    default: () => 0.35,
  },
  {
    key: 'floatingPanelWidthRatio',
    type: 'number',
    source: 'localStorage',
    read: () => s().floatingPanelWidthRatio,
    write: (v) => s().setFloatingPanelWidthRatio(Number(v)),
    docKey: 'floatingPanelWidthRatio',
    default: () => 0.25,
  },
  {
    key: 'floatingPanelHeightRatio',
    type: 'number',
    source: 'localStorage',
    read: () => s().floatingPanelHeightRatio,
    write: (v) => s().setFloatingPanelHeightRatio(Number(v)),
    docKey: 'floatingPanelHeightRatio',
    default: () => 0.5,
  },
  {
    key: 'floatingPanelZIndex',
    type: 'number',
    source: 'localStorage',
    read: () => s().floatingPanelZIndex,
    write: (v) => s().setFloatingPanelZIndex(Number(v)),
    docKey: 'floatingPanelZIndex',
    default: () => 5000,
  },
  {
    key: 'sidebarWidthRatio',
    type: 'number',
    source: 'localStorage',
    read: () => s().sidebarWidthRatio,
    write: (v) => s().setSidebarWidthRatio(Number(v)),
    docKey: 'sidebarWidthRatio',
    default: () => 0.25,
  },
  {
    key: 'enableLaunchSpotlight',
    type: 'boolean',
    source: 'store',
    read: () => s().enableLaunchSpotlight,
    write: (v) => s().setEnableLaunchSpotlight(Boolean(v)),
    docKey: 'enableLaunchSpotlight',
    default: () => true,
  },
  {
    key: 'spotlight.margin',
    type: 'number',
    source: 'store',
    read: () => s().spotlightMargin,
    write: (v) => s().setSpotlightMargin(Number(v)),
    docKey: 'spotlight.margin',
    default: () => 8,
  },
  {
    key: 'spotlight.nearTopThreshold',
    type: 'number',
    source: 'store',
    read: () => s().spotlightNearTopThreshold,
    write: (v) => s().setSpotlightNearTopThreshold(Number(v)),
    docKey: 'spotlight.nearTopThreshold',
    default: () => 96,
  },
  {
    key: 'chatEndpointUrl',
    type: 'string',
    source: 'localStorage',
    read: () => s().chatEndpointUrl,
    write: (v) => s().setChatEndpointUrl(String(v || '').trim() || null),
    docKey: 'chatEndpointUrl',
    default: () => 'http://localhost:1234/v1/chat/completions',
  },
  {
    key: 'chatModel',
    type: 'string',
    source: 'localStorage',
    read: () => s().chatModel,
    write: (v) => s().setChatModel(String(v || '').trim() || 'lmstudio-community/DeepSeek-R1-0528-Qwen3-8B-MLX-8bit'),
    docKey: 'chatModel',
    default: () => 'lmstudio-community/DeepSeek-R1-0528-Qwen3-8B-MLX-8bit',
  },
  {
    key: 'chatTemperature',
    type: 'number',
    source: 'localStorage',
    read: () => s().chatTemperature,
    write: (v) => s().setChatTemperature(Number(v)),
    docKey: 'chatTemperature',
    default: () => 0.3,
  },
  {
    key: 'chatSystemPrompt',
    type: 'string',
    source: 'localStorage',
    read: () => s().chatSystemPrompt,
    write: (v) => s().setChatSystemPrompt(String(v || '').trim() || null),
    docKey: 'chatSystemPrompt',
    default: () => null,
  },
]
