import type { FloatingPanelChatSubmitArgs } from '@/features/chat/floatingPanelChat/floatingPanelChatSubmitTypes'

export const buildSubmitArgsFixture = (
  overrides: Partial<FloatingPanelChatSubmitArgs> = {},
): FloatingPanelChatSubmitArgs => ({
  historyKey: 'history-key',
  graphData: null,
  currentNode: null,
  markdownText: null,
  markdownDocumentName: null,
  sourceFiles: [],
  workspaceContextCacheKey: 'workspace-cache',
  chatProvider: 'openai',
  chatAuthMode: 'serverManaged',
  chatApiKey: null,
  chatEndpointUrl: 'https://chat.example.test/v1/chat/completions',
  chatModel: 'gpt-4.1-mini',
  chatTemperature: 0.3,
  chatMaxCompletionTokens: 128,
  chatServiceTier: null,
  chatStream: true,
  chatMessagesJson: null,
  chatReasoningEffort: null,
  chatThinkingType: null,
  chatThinkingJson: null,
  chatFrequencyPenalty: null,
  chatPresencePenalty: null,
  chatTopP: null,
  chatLogprobs: null,
  chatTopLogprobs: null,
  chatParallelToolCalls: null,
  chatStopJson: null,
  chatStreamOptionsJson: null,
  chatResponseFormatJson: null,
  chatLogitBiasJson: null,
  chatToolsJson: null,
  chatToolChoiceJson: null,
  chatGraphSummaryMaxTokens: null,
  chatGuidelineDigestMaxTokens: null,
  chatSystemPrompt: null,
  chatSkillId: 'storybuilding',
  chatContextScope: 'workspace',
  chatStorageTarget: 'chatHistory',
  chatLocalStorageRootPath: '/workspace',
  chatKnowgrphWorkspacePath: null,
  setChatKnowgrphWorkspacePath: () => {},
  chatProviderSummary: 'openai:gpt-4.1-mini',
  setChatModel: () => {},
  messages: [],
  setMessages: () => {},
  input: '',
  setInput: () => {},
  isLoading: false,
  setIsLoading: () => {},
  setErrorText: () => {},
  setConnectivity: () => {},
  setConnectivityDetail: () => {},
  setStreamingAssistant: () => {},
  setStreamingInsights: () => {},
  setStreamingWorkspacePath: () => {},
  abortRef: { current: null },
  streamDraftTextRef: { current: null },
  streamFollowRef: { current: null },
  followWorkspaceMarkdownPath: () => {},
  finalizeAssistantSuccess: async () => {},
  pushChatExchangeLog: () => {},
  persistChatExchangeLog: async () => {},
  ...overrides,
})
