name = "knowgrph-research"
main = "index.ts"
compatibility_date = "2026-06-03"
workers_dev = true

[observability]
enabled = true

[[routes]]
pattern = "airvio.co/api/research/*"
zone_name = "airvio.co"

[[d1_databases]]
binding = "DB"
database_name = "knowgrph-storage"
database_id = "633355bf-1a52-4085-bd3c-eba4220ff152"
migrations_dir = "../../d1/migrations"

[[queues.producers]]
binding = "RESEARCH_THESIS_QUEUE"
queue = "knowgrph-research-thesis"

[[queues.consumers]]
queue = "knowgrph-research-thesis"
max_batch_size = 3
max_batch_timeout = 5

[[r2_buckets]]
binding = "RESEARCH_THESIS_ARTIFACTS"
bucket_name = "knowgrph-research-thesis"
