name = "knowgrph-payment"
main = "index.ts"
compatibility_date = "2026-05-29"
compatibility_flags = [ "nodejs_compat" ]

[observability]
enabled = true

[[routes]]
pattern = "airvio.co/api/payments/*"
zone_name = "airvio.co"

[[routes]]
pattern = "airvio.co/api"
zone_name = "airvio.co"

[[routes]]
pattern = "airvio.co/api/v1"
zone_name = "airvio.co"

[[routes]]
pattern = "airvio.co/.well-known/acp-config"
zone_name = "airvio.co"

[[routes]]
pattern = "airvio.co/checkout/sessions*"
zone_name = "airvio.co"

[[d1_databases]]
binding = "DB"
database_name = "knowgrph-storage"
database_id = "633355bf-1a52-4085-bd3c-eba4220ff152"
migrations_dir = "../../d1/migrations"
