import React from 'react'
import { createRoot } from 'react-dom/client'
import McpHubView from '@/features/panels/views/McpHubView'
import { initJsdomHarness } from '@/tests/lib/jsdomHarness'
import { initWindowHarness } from '@/tests/lib/windowHarness'
import { MemoryStorage } from '@/tests/lib/memoryStorage'
import { installDeterministicRaf, mountReactRoot, unmountReactRoot } from '@/tests/lib/reactRootHarness'
import { useGraphStore } from '@/hooks/useGraphStore'
import { assertMcpHubSurfacesLarkAppMcpConfig } from '@/__tests__/helpers/mainPanelMcpExpectations'
import {
  LARK_APP_MCP_AUTH_BOUNDARY,
  LARK_APP_MCP_BASEINFO_URL,
  LARK_APP_MCP_CANVAS_SURFACE,
  LARK_APP_MCP_DEFAULT_SERVER_KEY,
  LARK_APP_MCP_DEPLOYED_URL,
  LARK_APP_MCP_IMPORT_COMMAND,
  LARK_APP_MCP_OPERATOR_GUIDANCE,
  LARK_APP_MCP_PHASE_1_STATUS,
  LARK_APP_MCP_PHASE_2_STATUS,
  LARK_APP_MCP_PHASE_3_STATUS,
  LARK_APP_MCP_PHASE_SCOPE,
  LARK_APP_MCP_REMOTE_MUTATION_AUDIT,
  LARK_APP_MCP_REMOTE_MUTATION_AUTH_MODE,
  LARK_APP_MCP_REMOTE_MUTATION_BRIDGE_KIND,
  LARK_APP_MCP_REMOTE_MUTATION_CONFLICT_POLICY,
  LARK_APP_MCP_REMOTE_MUTATION_DEFERRED_ACTION,
  LARK_APP_MCP_REMOTE_MUTATION_IDEMPOTENCY,
  LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_BLOCKING_REASON,
  LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_MANIFEST,
  LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_MANIFEST_KIND,
  LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_CHECKLIST,
  LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_METADATA,
  LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_NEXT_STEP,
  LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_REQUIRED_HOST_CAPABILITY,
  LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_REQUIRED_HOST_CAPABILITY_STATUS,
  LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_REQUIRED_HOST_CAPABILITY_VERIFICATION_METHOD,
  LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_REQUIRED_HOST_CAPABILITY_VERIFICATION_TARGET,
  LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_REQUIRED_HOST_CAPABILITY_VERIFICATION_EVIDENCE,
  LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_REQUIRED_HOST_CAPABILITY_OWNER,
  LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_RETRY_DISPOSITION,
  LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_REMEDIATION_HINT,
  LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_SEVERITY,
  LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_SUMMARY,
  LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_READINESS,
  LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_STATUS,
  LARK_APP_MCP_REMOTE_MUTATION_RUNTIME_COMMAND,
  LARK_APP_MCP_REMOTE_MUTATION_SCOPE,
  LARK_APP_MCP_REMOTE_MUTATION_SUPPORTED_DRY_RUN_ACTION,
  LARK_APP_MCP_REMOTE_MUTATION_SUPPORTED_RUNTIME_ACTION,
  LARK_APP_MCP_TRANSPORT_TYPE,
  LARK_APP_MCP_TROUBLESHOOTING,
  LARK_APP_MCP_WEBPAGE_URL,
} from 'grph-shared/search/larkAppMcpSsot'
import { buildLarkAppRemoteMcpConfigJson } from '@/features/panels/views/larkAppMcpApiDocs'
import { buildLarkAppCanvasReviewHandoffQuery } from '@/features/canvas/larkAppCanvasHandoff'
import { buildLarkAppRemoteMutationRequestExample } from '@/features/canvas/larkAppRemoteMutationBridge'
import { QUERY_PARAM_LARK_HANDOFF } from '@/lib/routing/queryParams'

const withRenderedMcpHub = async (assertions: (container: Element) => void): Promise<void> => {
  const storage = new MemoryStorage()
  const { restore: restoreWindow } = initWindowHarness({ storage })
  const { dom, restore: restoreDom } = initJsdomHarness()
  let root: ReturnType<typeof createRoot> | null = null

  try {
    const anyWindow = dom.window as unknown as { requestAnimationFrame?: (cb: (ts: number) => void) => number }
    anyWindow.requestAnimationFrame = installDeterministicRaf(dom.window)

    useGraphStore.getState().resetAll()

    const doc = dom.window.document
    const container = doc.createElement('section')
    doc.body.appendChild(container)
    root = createRoot(container as unknown as HTMLElement)
    await mountReactRoot(root, React.createElement(McpHubView), { window: dom.window, frames: 4 })

    assertions(container)
  } finally {
    try {
      if (root) await unmountReactRoot(root, { window: dom.window })
    } catch {
      void 0
    }
    restoreDom()
    restoreWindow()
  }
}

export async function testMcpHubSurfacesLarkAppMcpConfig() {
  await withRenderedMcpHub(assertMcpHubSurfacesLarkAppMcpConfig)
}

export function testLarkAppMcpDefaultsStayCanvasBoundAndNonSecret() {
  const remoteConfig = buildLarkAppRemoteMcpConfigJson()
  const reviewQuery = buildLarkAppCanvasReviewHandoffQuery()
  const remoteMutationExample = buildLarkAppRemoteMutationRequestExample()
  const combined = [
    LARK_APP_MCP_DEFAULT_SERVER_KEY,
    LARK_APP_MCP_DEPLOYED_URL,
    LARK_APP_MCP_TRANSPORT_TYPE,
    LARK_APP_MCP_BASEINFO_URL,
    LARK_APP_MCP_WEBPAGE_URL,
    LARK_APP_MCP_CANVAS_SURFACE,
    LARK_APP_MCP_IMPORT_COMMAND,
    QUERY_PARAM_LARK_HANDOFF,
    LARK_APP_MCP_PHASE_1_STATUS,
    LARK_APP_MCP_PHASE_2_STATUS,
    LARK_APP_MCP_PHASE_3_STATUS,
    LARK_APP_MCP_REMOTE_MUTATION_BRIDGE_KIND,
    LARK_APP_MCP_REMOTE_MUTATION_AUTH_MODE,
    LARK_APP_MCP_REMOTE_MUTATION_IDEMPOTENCY,
    LARK_APP_MCP_REMOTE_MUTATION_CONFLICT_POLICY,
    LARK_APP_MCP_REMOTE_MUTATION_AUDIT,
    LARK_APP_MCP_REMOTE_MUTATION_SCOPE,
    LARK_APP_MCP_REMOTE_MUTATION_RUNTIME_COMMAND,
    LARK_APP_MCP_REMOTE_MUTATION_SUPPORTED_RUNTIME_ACTION,
    LARK_APP_MCP_REMOTE_MUTATION_SUPPORTED_DRY_RUN_ACTION,
    LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_STATUS,
    LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_METADATA,
    LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_READINESS,
    LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_BLOCKING_REASON,
    LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_MANIFEST,
    LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_MANIFEST_KIND,
    LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_SUMMARY,
    LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_SEVERITY,
    LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_CHECKLIST,
    LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_REMEDIATION_HINT,
    LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_RETRY_DISPOSITION,
    LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_REQUIRED_HOST_CAPABILITY,
    LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_REQUIRED_HOST_CAPABILITY_STATUS,
    LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_REQUIRED_HOST_CAPABILITY_VERIFICATION_METHOD,
    LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_REQUIRED_HOST_CAPABILITY_VERIFICATION_TARGET,
    LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_REQUIRED_HOST_CAPABILITY_VERIFICATION_EVIDENCE,
    LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_REQUIRED_HOST_CAPABILITY_OWNER,
    LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_NEXT_STEP,
    LARK_APP_MCP_REMOTE_MUTATION_DEFERRED_ACTION,
    LARK_APP_MCP_AUTH_BOUNDARY,
    LARK_APP_MCP_OPERATOR_GUIDANCE,
    LARK_APP_MCP_PHASE_SCOPE,
    LARK_APP_MCP_TROUBLESHOOTING,
    remoteConfig,
    reviewQuery,
    remoteMutationExample,
  ].join('\n')

  ;[
    LARK_APP_MCP_DEFAULT_SERVER_KEY,
    LARK_APP_MCP_DEPLOYED_URL,
    LARK_APP_MCP_TRANSPORT_TYPE,
    LARK_APP_MCP_WEBPAGE_URL,
    LARK_APP_MCP_CANVAS_SURFACE,
    LARK_APP_MCP_IMPORT_COMMAND,
    QUERY_PARAM_LARK_HANDOFF,
    LARK_APP_MCP_PHASE_1_STATUS,
    LARK_APP_MCP_PHASE_2_STATUS,
    LARK_APP_MCP_PHASE_3_STATUS,
    LARK_APP_MCP_REMOTE_MUTATION_BRIDGE_KIND,
    LARK_APP_MCP_REMOTE_MUTATION_AUTH_MODE,
    LARK_APP_MCP_REMOTE_MUTATION_IDEMPOTENCY,
    LARK_APP_MCP_REMOTE_MUTATION_CONFLICT_POLICY,
    LARK_APP_MCP_REMOTE_MUTATION_AUDIT,
    LARK_APP_MCP_REMOTE_MUTATION_SCOPE,
    LARK_APP_MCP_REMOTE_MUTATION_RUNTIME_COMMAND,
    LARK_APP_MCP_REMOTE_MUTATION_SUPPORTED_RUNTIME_ACTION,
    LARK_APP_MCP_REMOTE_MUTATION_SUPPORTED_DRY_RUN_ACTION,
    LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_STATUS,
    LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_METADATA,
    LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_READINESS,
    LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_BLOCKING_REASON,
    LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_MANIFEST,
    LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_MANIFEST_KIND,
    LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_SUMMARY,
    LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_SEVERITY,
    LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_CHECKLIST,
    LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_REMEDIATION_HINT,
    LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_RETRY_DISPOSITION,
    LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_REQUIRED_HOST_CAPABILITY,
    LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_REQUIRED_HOST_CAPABILITY_STATUS,
    LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_REQUIRED_HOST_CAPABILITY_VERIFICATION_METHOD,
    LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_REQUIRED_HOST_CAPABILITY_VERIFICATION_TARGET,
    LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_REQUIRED_HOST_CAPABILITY_VERIFICATION_EVIDENCE,
    LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_REQUIRED_HOST_CAPABILITY_OWNER,
    LARK_APP_MCP_REMOTE_MUTATION_PREVIEW_NEXT_STEP,
    LARK_APP_MCP_REMOTE_MUTATION_DEFERRED_ACTION,
    LARK_APP_MCP_AUTH_BOUNDARY,
  ].forEach(token => {
    if (!combined.includes(token)) {
      throw new Error(`expected Lark App MCP defaults to include ${JSON.stringify(token)}, got ${JSON.stringify(combined)}`)
    }
  })

  ;[
    `/${'Users'}/`,
    'tenant_access_token',
    'app_secret',
    'https://example.com/write',
  ].forEach(token => {
    if (combined.includes(token)) {
      throw new Error(`expected Lark App MCP defaults to avoid ${JSON.stringify(token)}, got ${JSON.stringify(combined)}`)
    }
  })
}
