import { convertWebpageLayoutToGraphData } from '@/lib/websites/webpageLayoutToGraph'

import type { WebpageLayoutSnapshot } from '@/lib/websites/webpageLayoutExport'
import type { GraphNode, JSONValue } from '@/lib/graph/types'

export function testWebpageLayoutToGraphCentersAndFilters() {
  const snap: WebpageLayoutSnapshot = {
    meta: {
      kind: 'layout',
      title: 'Astro',
      href: 'https://astro.build/',
      viewport: { w: 1000, h: 800 },
      scroll: { x: 0, y: 0, height: 3000 },
      ts: 1,
    },
    elements: [
      {
        id: 'e1',
        pid: '',
        tag: 'HEADER',
        rect: { x: 0, y: 0, w: 1000, h: 80 },
        text: 'Header',
        attrs: { id: 'top', class: 'site-header', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'sticky',
          zIndex: '10',
          backgroundColor: 'rgb(255, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '0px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '16px',
          fontWeight: '700',
          fontFamily: 'Inter, system-ui',
          lineHeight: '20px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e2',
        pid: 'e1',
        tag: 'DIV',
        rect: { x: 10, y: 10, w: 10, h: 5 },
        text: 'Tiny',
        attrs: { id: '', class: '', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '0px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '12px',
          fontWeight: '400',
          fontFamily: 'Inter, system-ui',
          lineHeight: '16px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e3',
        pid: '',
        tag: 'MAIN',
        rect: { x: 0, y: 120, w: 1000, h: 900 },
        text: 'Main',
        attrs: { id: '', class: 'main', role: 'main', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '12px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '2px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '16px',
          fontWeight: '400',
          fontFamily: 'Inter, system-ui',
          lineHeight: '20px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '0.9',
        },
      },
      {
        id: 'e6',
        pid: 'e3',
        tag: 'DIV',
        rect: { x: 0, y: 120, w: 1000, h: 900 },
        text: '',
        attrs: { id: '', class: '', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '0px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '16px',
          fontWeight: '400',
          fontFamily: 'Inter, system-ui',
          lineHeight: '20px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e7',
        pid: 'e6',
        tag: 'DIV',
        rect: { x: 0, y: 120, w: 1000, h: 900 },
        text: '',
        attrs: { id: '', class: '', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '0px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '16px',
          fontWeight: '400',
          fontFamily: 'Inter, system-ui',
          lineHeight: '20px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e8',
        pid: 'e7',
        tag: 'DIV',
        rect: { x: 0, y: 120, w: 1000, h: 900 },
        text: '',
        attrs: { id: '', class: 'container', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'flex',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '0px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '16px',
          fontWeight: '400',
          fontFamily: 'Inter, system-ui',
          lineHeight: '20px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e4',
        pid: 'e8',
        tag: 'BUTTON',
        rect: { x: 40, y: 160, w: 80, h: 24 },
        text: 'Buy',
        attrs: { id: '', class: 'btn', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'inline-block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgb(0, 0, 0)',
          color: 'rgb(255, 255, 255)',
          borderRadius: '6px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '1px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '12px',
          fontWeight: '600',
          fontFamily: 'Inter, system-ui',
          lineHeight: '16px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e9',
        pid: 'e3',
        tag: 'DIV',
        rect: { x: 0, y: 600, w: 1000, h: 200 },
        text: '',
        attrs: { id: '', class: 'container mx-auto px-4 grid gap-6', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'grid',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '0px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '12px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '16px',
          fontWeight: '400',
          fontFamily: 'Inter, system-ui',
          lineHeight: '20px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e10',
        pid: 'e9',
        tag: 'BUTTON',
        rect: { x: 0, y: 610, w: 100, h: 40 },
        text: 'A',
        attrs: { id: '', class: 'btn', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'inline-block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgb(0, 0, 0)',
          color: 'rgb(255, 255, 255)',
          borderRadius: '6px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '1px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '12px',
          fontWeight: '600',
          fontFamily: 'Inter, system-ui',
          lineHeight: '16px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e11',
        pid: 'e9',
        tag: 'BUTTON',
        rect: { x: 900, y: 610, w: 100, h: 40 },
        text: 'B',
        attrs: { id: '', class: 'btn', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'inline-block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgb(0, 0, 0)',
          color: 'rgb(255, 255, 255)',
          borderRadius: '6px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '1px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '12px',
          fontWeight: '600',
          fontFamily: 'Inter, system-ui',
          lineHeight: '16px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e12',
        pid: 'e9',
        tag: 'BUTTON',
        rect: { x: 0, y: 750, w: 100, h: 40 },
        text: 'C',
        attrs: { id: '', class: 'btn', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'inline-block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgb(0, 0, 0)',
          color: 'rgb(255, 255, 255)',
          borderRadius: '6px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '1px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '12px',
          fontWeight: '600',
          fontFamily: 'Inter, system-ui',
          lineHeight: '16px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e13',
        pid: 'e9',
        tag: 'BUTTON',
        rect: { x: 900, y: 750, w: 100, h: 40 },
        text: 'D',
        attrs: { id: '', class: 'btn', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'inline-block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgb(0, 0, 0)',
          color: 'rgb(255, 255, 255)',
          borderRadius: '6px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '1px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '12px',
          fontWeight: '600',
          fontFamily: 'Inter, system-ui',
          lineHeight: '16px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e14',
        pid: 'e9',
        tag: 'BUTTON',
        rect: { x: 450, y: 690, w: 100, h: 40 },
        text: 'E',
        attrs: { id: '', class: 'btn', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'inline-block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgb(0, 0, 0)',
          color: 'rgb(255, 255, 255)',
          borderRadius: '6px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '1px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '12px',
          fontWeight: '600',
          fontFamily: 'Inter, system-ui',
          lineHeight: '16px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e15',
        pid: 'e9',
        tag: 'BUTTON',
        rect: { x: 450, y: 730, w: 100, h: 40 },
        text: 'F',
        attrs: { id: '', class: 'btn', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'inline-block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgb(0, 0, 0)',
          color: 'rgb(255, 255, 255)',
          borderRadius: '6px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '1px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '12px',
          fontWeight: '600',
          fontFamily: 'Inter, system-ui',
          lineHeight: '16px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e5',
        pid: 'e3',
        tag: 'DIV',
        rect: { x: 150, y: 160, w: 30, h: 18 },
        text: '',
        attrs: { id: '', class: 'hero', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '0px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '12px',
          fontWeight: '400',
          fontFamily: 'Inter, system-ui',
          lineHeight: '16px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e16',
        pid: 'e3',
        tag: 'DIV',
        rect: { x: 200, y: 1500, w: 600, h: 200 },
        text: '',
        attrs: { id: '', class: 'card', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '0px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '16px',
          fontWeight: '400',
          fontFamily: 'Inter, system-ui',
          lineHeight: '20px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e17',
        pid: 'e16',
        tag: 'DIV',
        rect: { x: 280, y: 1560, w: 80, h: 40 },
        text: '',
        attrs: { id: '', class: 'glue', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '0px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '12px',
          fontWeight: '400',
          fontFamily: 'Inter, system-ui',
          lineHeight: '16px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e18',
        pid: 'e16',
        tag: 'DIV',
        rect: { x: 280, y: 1560, w: 80, h: 40 },
        text: '',
        attrs: { id: '', class: 'glue2', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '0px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '12px',
          fontWeight: '400',
          fontFamily: 'Inter, system-ui',
          lineHeight: '16px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e19',
        pid: 'e16',
        tag: 'DIV',
        rect: { x: 220, y: 1520, w: 560, h: 160 },
        text: '',
        attrs: { id: '', class: 'container flex gap-4', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'flex',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '0px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '10px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '12px',
          fontWeight: '400',
          fontFamily: 'Inter, system-ui',
          lineHeight: '16px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e20',
        pid: 'e16',
        tag: 'DIV',
        rect: { x: 280, y: 1560, w: 80, h: 40 },
        text: '',
        attrs: { id: '', class: '', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '0px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '12px',
          fontWeight: '400',
          fontFamily: 'Inter, system-ui',
          lineHeight: '16px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e21',
        pid: 'e3',
        tag: 'DIV',
        rect: { x: 50, y: 2400, w: 60, h: 20 },
        text: '',
        attrs: { id: '', class: 'text-sm leading-none', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '0px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '12px',
          fontWeight: '400',
          fontFamily: 'Inter, system-ui',
          lineHeight: '16px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e22',
        pid: '',
        tag: 'DIV',
        rect: { x: 0, y: 2600, w: 1000, h: 300 },
        text: '',
        attrs: { id: '', class: 'card', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '0px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '16px',
          fontWeight: '400',
          fontFamily: 'Inter, system-ui',
          lineHeight: '20px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e23',
        pid: '',
        tag: 'BUTTON',
        rect: { x: 10, y: 2610, w: 200, h: 40 },
        text: 'X',
        attrs: { id: '', class: 'btn', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'inline-block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '0px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '12px',
          fontWeight: '400',
          fontFamily: 'Inter, system-ui',
          lineHeight: '16px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
    ],
  }

  const graph = convertWebpageLayoutToGraphData(snap, { maxNodes: 1200, minAreaPx: 9000 })
  const ids = new Set((graph.nodes || []).map(n => String(n.id)))
  if (!ids.has('e1')) throw new Error('expected to keep large header')
  if (!ids.has('e3')) throw new Error('expected to keep large main')
  if (!ids.has('e4')) throw new Error('expected to keep small interactive button')
  if (!ids.has('e10') || !ids.has('e11') || !ids.has('e12') || !ids.has('e13') || !ids.has('e14') || !ids.has('e15')) {
    throw new Error('expected to keep multi-child buttons')
  }
  if (!ids.has('e16')) throw new Error('expected to keep semantic card container')
  if (ids.has('e2')) throw new Error('expected to drop tiny non-semantic div')
  if (ids.has('e5')) throw new Error('expected to drop tiny semantic-class div')
  if (ids.has('e6') || ids.has('e7')) throw new Error('expected to prune redundant wrapper elements')
  if (ids.has('e9')) throw new Error('expected to prune multi-child layout-glue wrapper')
  if (ids.has('e17') || ids.has('e18') || ids.has('e20')) throw new Error('expected overlap cleanup to drop glue boxes')
  if (ids.has('e21')) throw new Error('expected small noisy leaf suppression to drop tiny leaf div')
  if (!ids.has('e22') || !ids.has('e23')) throw new Error('expected geometric nesting candidates to remain')

  const edgeIds = new Set((graph.edges || []).map(e => String(e.id)))
  if (!edgeIds.has('dom:e3->e8')) throw new Error('expected wrapper-pruned parent-child contains edge')
  if (!edgeIds.has('dom:e8->e4')) throw new Error('expected nested parent-child contains edge')
  if (!edgeIds.has('dom:e3->e10') || !edgeIds.has('dom:e3->e11') || !edgeIds.has('dom:e3->e12')) {
    throw new Error('expected reparented contains edges after multi-child pruning')
  }
  if (!edgeIds.has('dom:e22->e23')) throw new Error('expected geometric nesting to assign containment edge')

  let minLeft = Infinity
  let maxRight = -Infinity
  let minTop = Infinity
  let maxBottom = -Infinity
  for (const raw of graph.nodes || []) {
    const n = raw as GraphNode
    const props = (n.properties || {}) as Record<string, JSONValue>
    const w = typeof props['visual:width'] === 'number' ? (props['visual:width'] as number) : 0
    const h = typeof props['visual:height'] === 'number' ? (props['visual:height'] as number) : 0
    const x = typeof n.x === 'number' ? n.x : 0
    const y = typeof n.y === 'number' ? n.y : 0
    minLeft = Math.min(minLeft, x - w / 2)
    maxRight = Math.max(maxRight, x + w / 2)
    minTop = Math.min(minTop, y - h / 2)
    maxBottom = Math.max(maxBottom, y + h / 2)
  }
  const cx = (minLeft + maxRight) / 2
  const cy = (minTop + maxBottom) / 2
  if (Math.abs(cx) > 1e-6 || Math.abs(cy) > 1e-6) throw new Error('expected centered bounding box')

  const header = (graph.nodes || []).find(n => String(n.id) === 'e1') as GraphNode | undefined
  if (!header) throw new Error('missing header node')
  const headerFill = (header.properties as Record<string, JSONValue>)['visual:fill']
  if (typeof headerFill !== 'string' || !headerFill.includes('rgb(255')) throw new Error('expected visual:fill from backgroundColor')

  const main = (graph.nodes || []).find(n => String(n.id) === 'e3') as GraphNode | undefined
  if (!main) throw new Error('missing main node')
  const mainFill = (main.properties as Record<string, JSONValue>)['visual:fill']
  if (typeof mainFill === 'string' && mainFill.trim()) throw new Error('expected transparent background to omit visual:fill')
}
