import { convertWebpageLayoutToGraphData } from '@/lib/websites/webpageLayoutToGraph'

import type { WebpageLayoutSnapshot } from '@/lib/websites/webpageLayoutExport'
import type { GraphNode, JSONValue } from '@/lib/graph/types'

export function testWebpageLayoutToGraphCentersAndFilters() {
  const snap: WebpageLayoutSnapshot = {
    meta: {
      kind: 'layout',
      title: 'Astro',
      href: 'https://astro.build/',
      viewport: { w: 1000, h: 800 },
      scroll: { x: 0, y: 0, height: 3000 },
      ts: 1,
    },
    elements: [
      {
        id: 'e1',
        pid: '',
        tag: 'HEADER',
        rect: { x: 0, y: 0, w: 1000, h: 80 },
        text: 'Header',
        attrs: { id: 'top', class: 'site-header', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'sticky',
          zIndex: '10',
          backgroundColor: 'rgb(255, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '0px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '16px',
          fontWeight: '700',
          fontFamily: 'Inter, system-ui',
          lineHeight: '20px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e2',
        pid: 'e1',
        tag: 'DIV',
        rect: { x: 10, y: 10, w: 10, h: 5 },
        text: 'Tiny',
        attrs: { id: '', class: '', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '0px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '12px',
          fontWeight: '400',
          fontFamily: 'Inter, system-ui',
          lineHeight: '16px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e3',
        pid: '',
        tag: 'MAIN',
        rect: { x: 0, y: 120, w: 1000, h: 900 },
        text: 'Main',
        attrs: { id: '', class: 'main', role: 'main', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '12px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '2px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '16px',
          fontWeight: '400',
          fontFamily: 'Inter, system-ui',
          lineHeight: '20px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '0.9',
        },
      },
      {
        id: 'e6',
        pid: 'e3',
        tag: 'DIV',
        rect: { x: 0, y: 120, w: 1000, h: 900 },
        text: '',
        attrs: { id: '', class: '', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '0px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '16px',
          fontWeight: '400',
          fontFamily: 'Inter, system-ui',
          lineHeight: '20px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e7',
        pid: 'e6',
        tag: 'DIV',
        rect: { x: 0, y: 120, w: 1000, h: 900 },
        text: '',
        attrs: { id: '', class: '', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '0px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '16px',
          fontWeight: '400',
          fontFamily: 'Inter, system-ui',
          lineHeight: '20px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e8',
        pid: 'e7',
        tag: 'DIV',
        rect: { x: 0, y: 120, w: 1000, h: 900 },
        text: '',
        attrs: { id: '', class: 'container', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'flex',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '0px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '16px',
          fontWeight: '400',
          fontFamily: 'Inter, system-ui',
          lineHeight: '20px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e4',
        pid: 'e8',
        tag: 'BUTTON',
        rect: { x: 40, y: 160, w: 80, h: 24 },
        text: 'Buy',
        attrs: { id: '', class: 'btn', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'inline-block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgb(0, 0, 0)',
          color: 'rgb(255, 255, 255)',
          borderRadius: '6px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '1px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '12px',
          fontWeight: '600',
          fontFamily: 'Inter, system-ui',
          lineHeight: '16px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e9',
        pid: 'e3',
        tag: 'DIV',
        rect: { x: 0, y: 600, w: 1000, h: 200 },
        text: '',
        attrs: { id: '', class: 'container mx-auto px-4 grid gap-6', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'grid',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '0px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '12px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '16px',
          fontWeight: '400',
          fontFamily: 'Inter, system-ui',
          lineHeight: '20px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e10',
        pid: 'e9',
        tag: 'BUTTON',
        rect: { x: 0, y: 610, w: 100, h: 40 },
        text: 'A',
        attrs: { id: '', class: 'btn', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'inline-block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgb(0, 0, 0)',
          color: 'rgb(255, 255, 255)',
          borderRadius: '6px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '1px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '12px',
          fontWeight: '600',
          fontFamily: 'Inter, system-ui',
          lineHeight: '16px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e11',
        pid: 'e9',
        tag: 'BUTTON',
        rect: { x: 900, y: 610, w: 100, h: 40 },
        text: 'B',
        attrs: { id: '', class: 'btn', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'inline-block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgb(0, 0, 0)',
          color: 'rgb(255, 255, 255)',
          borderRadius: '6px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '1px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '12px',
          fontWeight: '600',
          fontFamily: 'Inter, system-ui',
          lineHeight: '16px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e12',
        pid: 'e9',
        tag: 'BUTTON',
        rect: { x: 0, y: 750, w: 100, h: 40 },
        text: 'C',
        attrs: { id: '', class: 'btn', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'inline-block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgb(0, 0, 0)',
          color: 'rgb(255, 255, 255)',
          borderRadius: '6px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '1px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '12px',
          fontWeight: '600',
          fontFamily: 'Inter, system-ui',
          lineHeight: '16px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e13',
        pid: 'e9',
        tag: 'BUTTON',
        rect: { x: 900, y: 750, w: 100, h: 40 },
        text: 'D',
        attrs: { id: '', class: 'btn', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'inline-block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgb(0, 0, 0)',
          color: 'rgb(255, 255, 255)',
          borderRadius: '6px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '1px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '12px',
          fontWeight: '600',
          fontFamily: 'Inter, system-ui',
          lineHeight: '16px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e14',
        pid: 'e9',
        tag: 'BUTTON',
        rect: { x: 450, y: 690, w: 100, h: 40 },
        text: 'E',
        attrs: { id: '', class: 'btn', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'inline-block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgb(0, 0, 0)',
          color: 'rgb(255, 255, 255)',
          borderRadius: '6px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '1px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '12px',
          fontWeight: '600',
          fontFamily: 'Inter, system-ui',
          lineHeight: '16px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e15',
        pid: 'e9',
        tag: 'BUTTON',
        rect: { x: 450, y: 730, w: 100, h: 40 },
        text: 'F',
        attrs: { id: '', class: 'btn', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'inline-block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgb(0, 0, 0)',
          color: 'rgb(255, 255, 255)',
          borderRadius: '6px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '1px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '12px',
          fontWeight: '600',
          fontFamily: 'Inter, system-ui',
          lineHeight: '16px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e5',
        pid: 'e3',
        tag: 'DIV',
        rect: { x: 150, y: 160, w: 30, h: 18 },
        text: '',
        attrs: { id: '', class: 'hero', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '0px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '12px',
          fontWeight: '400',
          fontFamily: 'Inter, system-ui',
          lineHeight: '16px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e16',
        pid: 'e3',
        tag: 'DIV',
        rect: { x: 200, y: 1500, w: 600, h: 200 },
        text: '',
        attrs: { id: '', class: 'card', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '0px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '16px',
          fontWeight: '400',
          fontFamily: 'Inter, system-ui',
          lineHeight: '20px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e17',
        pid: 'e16',
        tag: 'DIV',
        rect: { x: 280, y: 1560, w: 80, h: 40 },
        text: '',
        attrs: { id: '', class: 'glue', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '0px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '12px',
          fontWeight: '400',
          fontFamily: 'Inter, system-ui',
          lineHeight: '16px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e18',
        pid: 'e16',
        tag: 'DIV',
        rect: { x: 280, y: 1560, w: 80, h: 40 },
        text: '',
        attrs: { id: '', class: 'glue2', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '0px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '12px',
          fontWeight: '400',
          fontFamily: 'Inter, system-ui',
          lineHeight: '16px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e19',
        pid: 'e16',
        tag: 'DIV',
        rect: { x: 220, y: 1520, w: 560, h: 160 },
        text: '',
        attrs: { id: '', class: 'container flex gap-4', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'flex',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '0px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '10px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '12px',
          fontWeight: '400',
          fontFamily: 'Inter, system-ui',
          lineHeight: '16px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e20',
        pid: 'e16',
        tag: 'DIV',
        rect: { x: 280, y: 1560, w: 80, h: 40 },
        text: '',
        attrs: { id: '', class: '', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '0px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '12px',
          fontWeight: '400',
          fontFamily: 'Inter, system-ui',
          lineHeight: '16px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e21',
        pid: 'e3',
        tag: 'DIV',
        rect: { x: 50, y: 2400, w: 60, h: 20 },
        text: '',
        attrs: { id: '', class: 'text-sm leading-none', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '0px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '12px',
          fontWeight: '400',
          fontFamily: 'Inter, system-ui',
          lineHeight: '16px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e22',
        pid: '',
        tag: 'DIV',
        rect: { x: 0, y: 2600, w: 1000, h: 300 },
        text: '',
        attrs: { id: '', class: 'card', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '0px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '16px',
          fontWeight: '400',
          fontFamily: 'Inter, system-ui',
          lineHeight: '20px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e23',
        pid: '',
        tag: 'BUTTON',
        rect: { x: 10, y: 2610, w: 200, h: 40 },
        text: 'X',
        attrs: { id: '', class: 'btn', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'inline-block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '0px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '12px',
          fontWeight: '400',
          fontFamily: 'Inter, system-ui',
          lineHeight: '16px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e24',
        pid: 'e3',
        tag: 'DIV',
        rect: { x: 0, y: 900, w: 1000, h: 420 },
        text: '',
        attrs: { id: '', class: '', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'grid',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '0px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '20px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '16px',
          fontWeight: '400',
          fontFamily: 'Inter, system-ui',
          lineHeight: '20px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e25',
        pid: 'e24',
        tag: 'H2',
        rect: { x: 30, y: 930, w: 420, h: 44 },
        text: 'Features',
        attrs: { id: '', class: '', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '0px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '32px',
          fontWeight: '700',
          fontFamily: 'Inter, system-ui',
          lineHeight: '36px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e26',
        pid: 'e24',
        tag: 'DIV',
        rect: { x: 0, y: 900, w: 1000, h: 420 },
        text: '',
        attrs: { id: '', class: 'wrapper', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '0px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '16px',
          fontWeight: '400',
          fontFamily: 'Inter, system-ui',
          lineHeight: '20px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e27',
        pid: 'e24',
        tag: 'DIV',
        rect: { x: 30, y: 990, w: 280, h: 120 },
        text: '',
        attrs: { id: '', class: 'tile', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '0px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '16px',
          fontWeight: '400',
          fontFamily: 'Inter, system-ui',
          lineHeight: '20px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e28',
        pid: 'e24',
        tag: 'DIV',
        rect: { x: 340, y: 990, w: 280, h: 120 },
        text: '',
        attrs: { id: '', class: 'tile', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '0px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '16px',
          fontWeight: '400',
          fontFamily: 'Inter, system-ui',
          lineHeight: '20px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e29',
        pid: 'e24',
        tag: 'DIV',
        rect: { x: 650, y: 990, w: 320, h: 120 },
        text: '',
        attrs: { id: '', class: 'tile', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '0px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '16px',
          fontWeight: '400',
          fontFamily: 'Inter, system-ui',
          lineHeight: '20px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e30',
        pid: 'e24',
        tag: 'A',
        rect: { x: 30, y: 1140, w: 220, h: 44 },
        text: 'Learn more',
        attrs: { id: '', class: '', role: '', ariaLabel: '', placeholder: '', href: 'https://example.com', src: '', alt: '' },
        style: {
          display: 'inline-block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '0px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '14px',
          fontWeight: '600',
          fontFamily: 'Inter, system-ui',
          lineHeight: '18px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e31',
        pid: '',
        tag: 'H2',
        rect: { x: 40, y: 1820, w: 520, h: 44 },
        text: 'Highlights',
        attrs: { id: '', class: '', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '0px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '32px',
          fontWeight: '700',
          fontFamily: 'Inter, system-ui',
          lineHeight: '36px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e32',
        pid: '',
        tag: 'DIV',
        rect: { x: 40, y: 1890, w: 300, h: 140 },
        text: '',
        attrs: { id: '', class: 'card', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '0px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '16px',
          fontWeight: '400',
          fontFamily: 'Inter, system-ui',
          lineHeight: '20px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e33',
        pid: '',
        tag: 'DIV',
        rect: { x: 360, y: 1890, w: 300, h: 140 },
        text: '',
        attrs: { id: '', class: 'card', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '0px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '16px',
          fontWeight: '400',
          fontFamily: 'Inter, system-ui',
          lineHeight: '20px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e34',
        pid: '',
        tag: 'DIV',
        rect: { x: 680, y: 1890, w: 300, h: 140 },
        text: '',
        attrs: { id: '', class: 'card', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '0px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '16px',
          fontWeight: '400',
          fontFamily: 'Inter, system-ui',
          lineHeight: '20px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e35',
        pid: '',
        tag: 'DIV',
        rect: { x: 40, y: 2050, w: 300, h: 140 },
        text: '',
        attrs: { id: '', class: 'card', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '0px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '16px',
          fontWeight: '400',
          fontFamily: 'Inter, system-ui',
          lineHeight: '20px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e36',
        pid: '',
        tag: 'DIV',
        rect: { x: 360, y: 2050, w: 300, h: 140 },
        text: '',
        attrs: { id: '', class: 'card', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '0px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '16px',
          fontWeight: '400',
          fontFamily: 'Inter, system-ui',
          lineHeight: '20px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'e37',
        pid: '',
        tag: 'DIV',
        rect: { x: 680, y: 2050, w: 300, h: 140 },
        text: '',
        attrs: { id: '', class: 'card', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: 'rgb(0, 0, 0)',
          borderRadius: '0px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '16px',
          fontWeight: '400',
          fontFamily: 'Inter, system-ui',
          lineHeight: '20px',
          letterSpacing: '0px',
          textTransform: 'none',
          textAlign: 'start',
          boxShadow: 'none',
          opacity: '1',
        },
      },
    ],
  }

  const graph = convertWebpageLayoutToGraphData(snap, { maxNodes: 1200, minAreaPx: 9000 })
  const ids = new Set((graph.nodes || []).map(n => String(n.id)))
  if (!ids.has('e1')) throw new Error('expected to keep large header')
  if (!ids.has('e3')) throw new Error('expected to keep large main')
  if (!ids.has('e4')) throw new Error('expected to keep small interactive button')
  if (!ids.has('e10') || !ids.has('e11') || !ids.has('e12') || !ids.has('e13') || !ids.has('e14') || !ids.has('e15')) {
    throw new Error('expected to keep multi-child buttons')
  }
  if (!ids.has('e16')) throw new Error('expected to keep semantic card container')
  if (ids.has('e2')) throw new Error('expected to drop tiny non-semantic div')
  if (ids.has('e5')) throw new Error('expected to drop tiny semantic-class div')
  if (ids.has('e6') || ids.has('e7')) throw new Error('expected to prune redundant wrapper elements')
  if (ids.has('e9')) throw new Error('expected to prune multi-child layout-glue wrapper')
  if (ids.has('e17') || ids.has('e18') || ids.has('e20')) throw new Error('expected overlap cleanup to drop glue boxes')
  if (ids.has('e21')) throw new Error('expected small noisy leaf suppression to drop tiny leaf div')
  if (!ids.has('e22') || !ids.has('e23')) throw new Error('expected geometric nesting candidates to remain')
  if (!ids.has('e24')) throw new Error('expected major section wrapper to remain')
  if (!ids.has('e25') || !ids.has('e30')) throw new Error('expected major section content to remain')
  if (!ids.has('e31') || !ids.has('e32') || !ids.has('e33') || !ids.has('e34') || !ids.has('e35') || !ids.has('e36') || !ids.has('e37')) {
    throw new Error('expected synthetic section candidates to remain')
  }

  const edgeIds = new Set((graph.edges || []).map(e => String(e.id)))
  if (!edgeIds.has('dom:e3->e8')) throw new Error('expected wrapper-pruned parent-child contains edge')
  if (!edgeIds.has('dom:e8->e4')) throw new Error('expected nested parent-child contains edge')
  if (!edgeIds.has('dom:e3->e10') || !edgeIds.has('dom:e3->e11') || !edgeIds.has('dom:e3->e12')) {
    throw new Error('expected reparented contains edges after multi-child pruning')
  }
  if (!edgeIds.has('dom:e22->e23')) throw new Error('expected geometric nesting to assign containment edge')

  const synthSectionNodes = (graph.nodes || [])
    .map(n => n as GraphNode)
    .filter(n => {
      const props = (n.properties || {}) as Record<string, JSONValue>
      return props['dom:tag'] === 'SECTION' && props['dom:attrs:class'] === 'kg-synth-section' && props['dom:attrs:ariaLabel'] === 'Highlights'
    })
  if (synthSectionNodes.length === 0) throw new Error('expected section synthesis to create a Highlights container')
  const secId = String(synthSectionNodes[0]!.id)
  if (String((synthSectionNodes[0]!.metadata as unknown as { domParentId?: unknown })?.domParentId || '') !== '') {
    throw new Error('expected synthetic section to be top-level (no dom parent)')
  }
  if (!edgeIds.has(`dom:${secId}->e31`) || !edgeIds.has(`dom:${secId}->e32`) || !edgeIds.has(`dom:${secId}->e37`)) {
    throw new Error('expected synthetic section to contain heading and cards')
  }

  let minLeft = Infinity
  let maxRight = -Infinity
  let minTop = Infinity
  let maxBottom = -Infinity
  for (const raw of graph.nodes || []) {
    const n = raw as GraphNode
    const props = (n.properties || {}) as Record<string, JSONValue>
    const w = typeof props['visual:width'] === 'number' ? (props['visual:width'] as number) : 0
    const h = typeof props['visual:height'] === 'number' ? (props['visual:height'] as number) : 0
    const x = typeof n.x === 'number' ? n.x : 0
    const y = typeof n.y === 'number' ? n.y : 0
    minLeft = Math.min(minLeft, x - w / 2)
    maxRight = Math.max(maxRight, x + w / 2)
    minTop = Math.min(minTop, y - h / 2)
    maxBottom = Math.max(maxBottom, y + h / 2)
  }
  const cx = (minLeft + maxRight) / 2
  const cy = (minTop + maxBottom) / 2
  if (Math.abs(cx) > 1e-6 || Math.abs(cy) > 1e-6) throw new Error('expected centered bounding box')

  const header = (graph.nodes || []).find(n => String(n.id) === 'e1') as GraphNode | undefined
  if (!header) throw new Error('missing header node')
  const headerFill = (header.properties as Record<string, JSONValue>)['visual:fill']
  if (typeof headerFill !== 'string' || !headerFill.includes('rgb(255')) throw new Error('expected visual:fill from backgroundColor')

  const main = (graph.nodes || []).find(n => String(n.id) === 'e3') as GraphNode | undefined
  if (!main) throw new Error('missing main node')
  const mainFill = (main.properties as Record<string, JSONValue>)['visual:fill']
  if (typeof mainFill === 'string' && mainFill.trim()) throw new Error('expected transparent background to omit visual:fill')
}

export function testWebpageLayoutToGraphWrapperSingleChildPrune() {
  const snap: WebpageLayoutSnapshot = {
    meta: { kind: 'layout', title: 'Wrapper', href: 'https://example.invalid/', viewport: { w: 1000, h: 800 }, scroll: { x: 0, y: 0, height: 1600 }, ts: 1 },
    elements: [
      {
        id: 'e1',
        pid: '',
        tag: 'MAIN',
        rect: { x: 0, y: 0, w: 1000, h: 800 },
        text: '',
        attrs: { id: '', class: '', role: 'main', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: '',
          borderRadius: '0px',
          borderColor: 'rgba(0, 0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '',
          fontWeight: '',
          fontFamily: '',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textAlign: '',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'w1',
        pid: 'e1',
        tag: 'DIV',
        rect: { x: 0, y: 0, w: 1000, h: 240 },
        text: '',
        attrs: { id: '', class: 'container mx-auto max-w-7xl px-4', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: '',
          borderRadius: '0px',
          borderColor: 'rgba(0, 0, 0, 0)',
          borderWidth: '0px',
          padding: '16px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '',
          fontWeight: '',
          fontFamily: '',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textAlign: '',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'c1',
        pid: 'w1',
        tag: 'DIV',
        rect: { x: 120, y: 20, w: 760, h: 200 },
        text: '',
        attrs: { id: '', class: 'grid grid-cols-2 gap-6', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'grid',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: '',
          borderRadius: '0px',
          borderColor: 'rgba(0, 0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '24px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '',
          fontWeight: '',
          fontFamily: '',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textAlign: '',
          boxShadow: 'none',
          opacity: '1',
        },
      },
    ],
  }

  const graph = convertWebpageLayoutToGraphData(snap, { maxNodes: 1200, minAreaPx: 9000 })
  const ids = new Set((graph.nodes || []).map(n => String(n.id)))
  if (!ids.has('e1')) throw new Error('expected to keep main container')
  if (ids.has('w1')) throw new Error('expected to prune single-child layout-glue wrapper')
  if (!ids.has('c1')) throw new Error('expected to keep content container')
  const edgeIds = new Set((graph.edges || []).map(e => String(e.id)))
  if (!edgeIds.has('dom:e1->c1')) throw new Error('expected content container to be reparented to main')
}

export function testWebpageLayoutToGraphOverlapIntersectionPrune() {
  const snap: WebpageLayoutSnapshot = {
    meta: { kind: 'layout', title: 'Overlap', href: 'https://example.invalid/', viewport: { w: 1000, h: 800 }, scroll: { x: 0, y: 0, height: 1600 }, ts: 1 },
    elements: [
      {
        id: 'p1',
        pid: '',
        tag: 'DIV',
        rect: { x: 0, y: 0, w: 1000, h: 800 },
        text: '',
        attrs: { id: '', class: '', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: '',
          borderRadius: '0px',
          borderColor: 'rgba(0, 0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '',
          fontWeight: '',
          fontFamily: '',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textAlign: '',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'a',
        pid: 'p1',
        tag: 'DIV',
        rect: { x: 100, y: 100, w: 300, h: 120 },
        text: '',
        attrs: { id: '', class: '', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'absolute',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: '',
          borderRadius: '0px',
          borderColor: 'rgba(0, 0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '',
          fontWeight: '',
          fontFamily: '',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textAlign: '',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'b',
        pid: 'p1',
        tag: 'DIV',
        rect: { x: 105, y: 104, w: 300, h: 120 },
        text: '',
        attrs: { id: '', class: '', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'absolute',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: '',
          borderRadius: '0px',
          borderColor: 'rgba(0, 0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '',
          fontWeight: '',
          fontFamily: '',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textAlign: '',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'c',
        pid: 'p1',
        tag: 'DIV',
        rect: { x: 450, y: 110, w: 220, h: 120 },
        text: 'Keep',
        attrs: { id: '', class: '', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'absolute',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: '',
          borderRadius: '0px',
          borderColor: 'rgba(0, 0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '',
          fontWeight: '',
          fontFamily: '',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textAlign: '',
          boxShadow: 'none',
          opacity: '1',
        },
      },
    ],
  }

  const graph = convertWebpageLayoutToGraphData(snap, { maxNodes: 1200, minAreaPx: 9000 })
  const ids = new Set((graph.nodes || []).map(n => String(n.id)))
  if (ids.has('a') && ids.has('b')) throw new Error('expected overlap cleanup to drop one of the near-stacked glue boxes')
  if (!ids.has('c')) throw new Error('expected non-empty text element to remain')
}

export function testWebpageLayoutToGraphSectionSynthesisGridFourItems() {
  const snap: WebpageLayoutSnapshot = {
    meta: { kind: 'layout', title: 'Grid', href: 'https://astro.build/', viewport: { w: 1000, h: 800 }, scroll: { x: 0, y: 0, height: 2200 }, ts: 1 },
    elements: [
      {
        id: 'p1',
        pid: '',
        tag: 'DIV',
        rect: { x: 0, y: 360, w: 1000, h: 520 },
        text: '',
        attrs: { id: '', class: 'grid grid-cols-2 gap-8', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'grid',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: '',
          borderRadius: '0px',
          borderColor: 'rgba(0, 0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '32px',
          gridTemplateColumns: '1fr 1fr',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '',
          fontWeight: '',
          fontFamily: '',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textAlign: '',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'h2',
        pid: 'p1',
        tag: 'H2',
        rect: { x: 50, y: 380, w: 400, h: 36 },
        text: 'Features',
        attrs: { id: '', class: '', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: '',
          borderRadius: '0px',
          borderColor: 'rgba(0, 0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '24px',
          fontWeight: '700',
          fontFamily: '',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textAlign: '',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'c1',
        pid: 'p1',
        tag: 'DIV',
        rect: { x: 50, y: 440, w: 430, h: 160 },
        text: '',
        attrs: { id: '', class: 'card', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: '',
          borderRadius: '0px',
          borderColor: 'rgba(0, 0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '',
          fontWeight: '',
          fontFamily: '',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textAlign: '',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'c2',
        pid: 'p1',
        tag: 'DIV',
        rect: { x: 520, y: 440, w: 430, h: 160 },
        text: '',
        attrs: { id: '', class: 'card', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: '',
          borderRadius: '0px',
          borderColor: 'rgba(0, 0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '',
          fontWeight: '',
          fontFamily: '',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textAlign: '',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'c3',
        pid: 'p1',
        tag: 'DIV',
        rect: { x: 50, y: 640, w: 430, h: 160 },
        text: '',
        attrs: { id: '', class: 'card', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: '',
          borderRadius: '0px',
          borderColor: 'rgba(0, 0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '',
          fontWeight: '',
          fontFamily: '',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textAlign: '',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'c4',
        pid: 'p1',
        tag: 'DIV',
        rect: { x: 520, y: 640, w: 430, h: 160 },
        text: '',
        attrs: { id: '', class: 'card', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: '',
          borderRadius: '0px',
          borderColor: 'rgba(0, 0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '',
          fontWeight: '',
          fontFamily: '',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textAlign: '',
          boxShadow: 'none',
          opacity: '1',
        },
      },
    ],
  }

  const graph = convertWebpageLayoutToGraphData(snap, { maxNodes: 1200, minAreaPx: 9000 })
  const p1 = (graph.nodes || []).find(n => String(n.id) === 'p1') as GraphNode | undefined
  if (!p1) throw new Error('expected parent grid node to exist')
  const p1Props = (p1.properties || {}) as Record<string, JSONValue>
  if (p1Props['layout:kind'] !== 'grid') throw new Error('expected grid container to be tagged with layout:kind=grid')
  if (p1Props['css:gridTemplateColumns'] !== '1fr 1fr') throw new Error('expected css:gridTemplateColumns to be preserved')
  const synthSectionNodes = (graph.nodes || [])
    .map(n => n as GraphNode)
    .filter(n => {
      const props = (n.properties || {}) as Record<string, JSONValue>
      return props['dom:tag'] === 'SECTION' && props['dom:attrs:class'] === 'kg-synth-section' && props['dom:attrs:ariaLabel'] === 'Features'
    })
  if (synthSectionNodes.length === 0) throw new Error('expected section synthesis to create a Features container from 4-item grid')
  const sec = synthSectionNodes[0]!
  const secPid = String((sec.metadata as unknown as { domParentId?: unknown })?.domParentId || '')
  if (secPid !== 'p1') throw new Error('expected synthetic section to be nested under grid parent')
  const edgeIds = new Set((graph.edges || []).map(e => String(e.id)))
  const secId = String(sec.id)
  if (!edgeIds.has(`dom:${secId}->h2`) || !edgeIds.has(`dom:${secId}->c1`) || !edgeIds.has(`dom:${secId}->c4`)) {
    throw new Error('expected synthetic section to contain heading and all cards')
  }
}

export function testWebpageLayoutToGraphSectionSynthesisDoesNotTriggerOnFlexParent() {
  const snap: WebpageLayoutSnapshot = {
    meta: { kind: 'layout', title: 'FlexGrid', href: 'https://astro.build/', viewport: { w: 1000, h: 800 }, scroll: { x: 0, y: 0, height: 2200 }, ts: 1 },
    elements: [
      {
        id: 'p1',
        pid: '',
        tag: 'DIV',
        rect: { x: 0, y: 360, w: 1000, h: 520 },
        text: '',
        attrs: { id: '', class: 'flex flex-wrap gap-8', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'flex',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: '',
          borderRadius: '0px',
          borderColor: 'rgba(0, 0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '32px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'wrap',
          fontSize: '',
          fontWeight: '',
          fontFamily: '',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textAlign: '',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'c1',
        pid: 'p1',
        tag: 'DIV',
        rect: { x: 50, y: 440, w: 430, h: 160 },
        text: '',
        attrs: { id: '', class: '', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: '',
          borderRadius: '0px',
          borderColor: 'rgba(0, 0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '',
          fontWeight: '',
          fontFamily: '',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textAlign: '',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'c2',
        pid: 'p1',
        tag: 'DIV',
        rect: { x: 520, y: 440, w: 430, h: 160 },
        text: '',
        attrs: { id: '', class: '', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: '',
          borderRadius: '0px',
          borderColor: 'rgba(0, 0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '',
          fontWeight: '',
          fontFamily: '',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textAlign: '',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'c3',
        pid: 'p1',
        tag: 'DIV',
        rect: { x: 50, y: 640, w: 430, h: 160 },
        text: '',
        attrs: { id: '', class: '', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: '',
          borderRadius: '0px',
          borderColor: 'rgba(0, 0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '',
          fontWeight: '',
          fontFamily: '',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textAlign: '',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'c4',
        pid: 'p1',
        tag: 'DIV',
        rect: { x: 520, y: 640, w: 430, h: 160 },
        text: '',
        attrs: { id: '', class: '', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: '',
          borderRadius: '0px',
          borderColor: 'rgba(0, 0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '',
          fontWeight: '',
          fontFamily: '',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textAlign: '',
          boxShadow: 'none',
          opacity: '1',
        },
      },
    ],
  }

  const graph = convertWebpageLayoutToGraphData(snap, { maxNodes: 1200, minAreaPx: 9000 })
  const synthSectionNodes = (graph.nodes || [])
    .map(n => n as GraphNode)
    .filter(n => {
      const props = (n.properties || {}) as Record<string, JSONValue>
      return props['dom:tag'] === 'SECTION' && props['dom:attrs:class'] === 'kg-synth-section'
    })
  if (synthSectionNodes.length > 0) throw new Error('expected section synthesis to avoid creating extra SECTION boxes from flex layout')
}

export function testWebpageLayoutToGraphPrunesUtilityWrapperAtThreeKids() {
  const snap: WebpageLayoutSnapshot = {
    meta: { kind: 'layout', title: 'UtilityWrapper', href: 'https://example.invalid/', viewport: { w: 1000, h: 800 }, scroll: { x: 0, y: 0, height: 1200 }, ts: 1 },
    elements: [
      {
        id: 'p1',
        pid: '',
        tag: 'DIV',
        rect: { x: 0, y: 0, w: 1000, h: 800 },
        text: '',
        attrs: { id: '', class: '', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: '',
          borderRadius: '0px',
          borderColor: 'rgba(0, 0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '',
          fontWeight: '',
          fontFamily: '',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textAlign: '',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'w1',
        pid: 'p1',
        tag: 'DIV',
        rect: { x: 100, y: 40, w: 600, h: 80 },
        text: '',
        attrs: { id: '', class: 'flex items-center justify-between gap-4 px-4', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'flex',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: '',
          borderRadius: '0px',
          borderColor: 'rgba(0, 0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '16px',
          justifyContent: 'space-between',
          alignItems: 'center',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '',
          fontWeight: '',
          fontFamily: '',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textAlign: '',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'k1',
        pid: 'w1',
        tag: 'DIV',
        rect: { x: 100, y: 40, w: 180, h: 80 },
        text: '',
        attrs: { id: '', class: '', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: '',
          borderRadius: '0px',
          borderColor: 'rgba(0, 0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '',
          fontWeight: '',
          fontFamily: '',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textAlign: '',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'k2',
        pid: 'w1',
        tag: 'DIV',
        rect: { x: 320, y: 40, w: 180, h: 80 },
        text: '',
        attrs: { id: '', class: '', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: '',
          borderRadius: '0px',
          borderColor: 'rgba(0, 0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '',
          fontWeight: '',
          fontFamily: '',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textAlign: '',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'k3',
        pid: 'w1',
        tag: 'DIV',
        rect: { x: 520, y: 40, w: 180, h: 80 },
        text: '',
        attrs: { id: '', class: '', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: '',
          borderRadius: '0px',
          borderColor: 'rgba(0, 0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '',
          fontWeight: '',
          fontFamily: '',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textAlign: '',
          boxShadow: 'none',
          opacity: '1',
        },
      },
    ],
  }

  const graph = convertWebpageLayoutToGraphData(snap, { maxNodes: 1200, minAreaPx: 9000 })
  const ids = new Set((graph.nodes || []).map(n => String(n.id)))
  if (ids.has('w1')) throw new Error('expected 3-child utility wrapper to be pruned')
  if (!ids.has('k1') || !ids.has('k2') || !ids.has('k3')) throw new Error('expected children to remain')
  const edgeIds = new Set((graph.edges || []).map(e => String(e.id)))
  if (!edgeIds.has('dom:p1->k1') || !edgeIds.has('dom:p1->k2') || !edgeIds.has('dom:p1->k3')) {
    throw new Error('expected children to be reparented to wrapper parent')
  }
}

export function testWebpageLayoutToGraphDropsTinyDecorativeSvgIcon() {
  const snap: WebpageLayoutSnapshot = {
    meta: { kind: 'layout', title: 'SvgIcon', href: 'https://example.invalid/', viewport: { w: 1000, h: 800 }, scroll: { x: 0, y: 0, height: 1200 }, ts: 1 },
    elements: [
      {
        id: 'p1',
        pid: '',
        tag: 'DIV',
        rect: { x: 0, y: 0, w: 1000, h: 800 },
        text: '',
        attrs: { id: '', class: '', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: '',
          borderRadius: '0px',
          borderColor: 'rgba(0, 0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '',
          fontWeight: '',
          fontFamily: '',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textAlign: '',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'b1',
        pid: 'p1',
        tag: 'BUTTON',
        rect: { x: 100, y: 100, w: 240, h: 44 },
        text: 'Get Started',
        attrs: { id: '', class: 'btn', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'inline-block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgb(0, 0, 0)',
          color: 'rgb(255, 255, 255)',
          borderRadius: '8px',
          borderColor: 'rgb(0, 0, 0)',
          borderWidth: '1px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '14px',
          fontWeight: '600',
          fontFamily: '',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textAlign: '',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      {
        id: 'i1',
        pid: 'b1',
        tag: 'SVG',
        rect: { x: 112, y: 114, w: 16, h: 16 },
        text: '',
        attrs: { id: '', class: '', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: '',
          borderRadius: '0px',
          borderColor: 'rgba(0, 0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '',
          fontWeight: '',
          fontFamily: '',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textAlign: '',
          boxShadow: 'none',
          opacity: '1',
        },
      },
    ],
  }

  const graph = convertWebpageLayoutToGraphData(snap, { maxNodes: 1200, minAreaPx: 9000 })
  const ids = new Set((graph.nodes || []).map(n => String(n.id)))
  if (!ids.has('b1')) throw new Error('expected to keep button')
  if (ids.has('i1')) throw new Error('expected to drop tiny decorative svg icon')
}

export function testWebpageLayoutToGraphEffectiveOpacityAndStackKey() {
  const snap: WebpageLayoutSnapshot = {
    meta: { kind: 'layout', title: 'Opacity', href: 'https://example.invalid/', viewport: { w: 800, h: 600 }, scroll: { x: 0, y: 0, height: 600 }, ts: 1 },
    elements: [
      {
        id: 'p',
        pid: '',
        tag: 'DIV',
        rect: { x: 0, y: 0, w: 800, h: 600 },
        text: '',
        attrs: { id: '', class: '', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgb(255, 255, 255)',
          color: '',
          borderRadius: '0px',
          borderColor: 'rgba(0, 0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '',
          fontWeight: '',
          fontFamily: '',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textAlign: '',
          boxShadow: 'none',
          opacity: '0.5',
        },
      },
      {
        id: 'c',
        pid: 'p',
        tag: 'BUTTON',
        rect: { x: 100, y: 100, w: 200, h: 60 },
        text: 'Click',
        attrs: { id: '', class: 'btn', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'inline-block',
          position: 'relative',
          zIndex: '10',
          backgroundColor: 'rgb(0, 0, 0)',
          color: 'rgb(255, 255, 255)',
          borderRadius: '6px',
          borderColor: 'rgba(0, 0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '14px',
          fontWeight: '600',
          fontFamily: '',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textAlign: '',
          boxShadow: 'none',
          opacity: '0.5',
        },
      },
    ],
  }

  const graph = convertWebpageLayoutToGraphData(snap, { maxNodes: 1000, minAreaPx: 1 })
  const node = (graph.nodes || []).find(n => String(n.id) === 'c') as GraphNode | undefined
  if (!node) throw new Error('missing child node')
  const props = (node.properties || {}) as Record<string, JSONValue>
  const effOpacity = props['visual:opacity']
  if (typeof effOpacity !== 'number' || Math.abs(effOpacity - 0.25) > 1e-6) {
    throw new Error(`expected effective opacity 0.25 (got ${String(effOpacity)})`)
  }
  const stackKey = props['css:stackKey']
  if (typeof stackKey !== 'string' || !stackKey.trim()) throw new Error('expected css:stackKey')
}

export function testWebpageLayoutToGraphAssignsGridChildIndices() {
  const snap: WebpageLayoutSnapshot = {
    meta: { kind: 'layout', title: 'Grid', href: 'https://example.invalid/', viewport: { w: 1000, h: 800 }, scroll: { x: 0, y: 0, height: 800 }, ts: 1 },
    elements: [
      {
        id: 'g',
        pid: '',
        tag: 'DIV',
        rect: { x: 0, y: 0, w: 1000, h: 800 },
        text: '',
        attrs: { id: '', class: '', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'grid',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: '',
          borderRadius: '0px',
          borderColor: 'rgba(0, 0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '24px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '',
          fontWeight: '',
          fontFamily: '',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textAlign: '',
          boxShadow: 'none',
          opacity: '1',
        },
      },
      { id: 'a', pid: 'g', tag: 'BUTTON', rect: { x: 40, y: 40, w: 300, h: 80 }, text: 'A', attrs: { id: '', class: '', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' }, style: { display: 'inline-block', position: 'static', zIndex: 'auto', backgroundColor: 'rgb(0, 0, 0)', color: 'rgb(255, 255, 255)', borderRadius: '6px', borderColor: 'rgba(0, 0, 0, 0)', borderWidth: '0px', padding: '0px', margin: '0px', gap: '0px', justifyContent: 'normal', alignItems: 'normal', flexDirection: 'row', flexWrap: 'nowrap', fontSize: '14px', fontWeight: '600', fontFamily: '', lineHeight: '', letterSpacing: '', textTransform: '', textAlign: '', boxShadow: 'none', opacity: '1' } },
      { id: 'b', pid: 'g', tag: 'BUTTON', rect: { x: 520, y: 40, w: 300, h: 80 }, text: 'B', attrs: { id: '', class: '', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' }, style: { display: 'inline-block', position: 'static', zIndex: 'auto', backgroundColor: 'rgb(0, 0, 0)', color: 'rgb(255, 255, 255)', borderRadius: '6px', borderColor: 'rgba(0, 0, 0, 0)', borderWidth: '0px', padding: '0px', margin: '0px', gap: '0px', justifyContent: 'normal', alignItems: 'normal', flexDirection: 'row', flexWrap: 'nowrap', fontSize: '14px', fontWeight: '600', fontFamily: '', lineHeight: '', letterSpacing: '', textTransform: '', textAlign: '', boxShadow: 'none', opacity: '1' } },
      { id: 'c', pid: 'g', tag: 'BUTTON', rect: { x: 40, y: 180, w: 300, h: 80 }, text: 'C', attrs: { id: '', class: '', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' }, style: { display: 'inline-block', position: 'static', zIndex: 'auto', backgroundColor: 'rgb(0, 0, 0)', color: 'rgb(255, 255, 255)', borderRadius: '6px', borderColor: 'rgba(0, 0, 0, 0)', borderWidth: '0px', padding: '0px', margin: '0px', gap: '0px', justifyContent: 'normal', alignItems: 'normal', flexDirection: 'row', flexWrap: 'nowrap', fontSize: '14px', fontWeight: '600', fontFamily: '', lineHeight: '', letterSpacing: '', textTransform: '', textAlign: '', boxShadow: 'none', opacity: '1' } },
      { id: 'd', pid: 'g', tag: 'BUTTON', rect: { x: 520, y: 180, w: 300, h: 80 }, text: 'D', attrs: { id: '', class: '', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' }, style: { display: 'inline-block', position: 'static', zIndex: 'auto', backgroundColor: 'rgb(0, 0, 0)', color: 'rgb(255, 255, 255)', borderRadius: '6px', borderColor: 'rgba(0, 0, 0, 0)', borderWidth: '0px', padding: '0px', margin: '0px', gap: '0px', justifyContent: 'normal', alignItems: 'normal', flexDirection: 'row', flexWrap: 'nowrap', fontSize: '14px', fontWeight: '600', fontFamily: '', lineHeight: '', letterSpacing: '', textTransform: '', textAlign: '', boxShadow: 'none', opacity: '1' } },
    ],
  }

  const graph = convertWebpageLayoutToGraphData(snap, { maxNodes: 1000, minAreaPx: 1 })
  const byId = new Map((graph.nodes || []).map(n => [String(n.id), n as GraphNode]))
  const a = byId.get('a')
  const b = byId.get('b')
  const c = byId.get('c')
  const d = byId.get('d')
  if (!a || !b || !c || !d) throw new Error('missing grid children')
  const getIx = (n: GraphNode) => {
    const props = (n.properties || {}) as Record<string, JSONValue>
    return { x: props['visual:xIndex'], y: props['visual:yIndex'] }
  }
  const ia = getIx(a)
  const ib = getIx(b)
  const ic = getIx(c)
  const id = getIx(d)
  if (ia.y !== 0 || ia.x !== 0) throw new Error('expected A at (0,0)')
  if (ib.y !== 0 || ib.x !== 1) throw new Error('expected B at (1,0)')
  if (ic.y !== 1 || ic.x !== 0) throw new Error('expected C at (0,1)')
  if (id.y !== 1 || id.x !== 1) throw new Error('expected D at (1,1)')
}

export function testWebpageLayoutToGraphKeepsImportantHeadingUnderMaxNodesBudget() {
  const url = 'https://www.ycombinator.com/library/8d-how-to-build-a-great-series-a-pitch-and-deck'
  const snap: WebpageLayoutSnapshot = {
    meta: { kind: 'layout', title: 'YC', href: url, viewport: { w: 1200, h: 800 }, scroll: { x: 0, y: 0, height: 5200 }, ts: 1 },
    elements: (() => {
      const styleBase = {
        display: 'block',
        position: 'static',
        zIndex: 'auto',
        backgroundColor: 'rgba(0, 0, 0, 0)',
        color: '',
        borderRadius: '0px',
        borderColor: 'rgba(0, 0, 0, 0)',
        borderWidth: '0px',
        padding: '0px',
        margin: '0px',
        gap: '0px',
        justifyContent: 'normal',
        alignItems: 'normal',
        flexDirection: 'row',
        flexWrap: 'nowrap',
        fontSize: '',
        fontWeight: '',
        fontFamily: '',
        lineHeight: '',
        letterSpacing: '',
        textTransform: '',
        textAlign: '',
        boxShadow: 'none',
        opacity: '1',
      } as const
      const els: WebpageLayoutSnapshot['elements'] = []
      els.push({
        id: 'main',
        pid: '',
        tag: 'MAIN',
        rect: { x: 0, y: 0, w: 1200, h: 800 },
        text: '',
        attrs: { id: '', class: '', role: 'main', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: styleBase,
      })
      for (let i = 0; i < 64; i += 1) {
        els.push({
          id: `fill_${i}`,
          pid: 'main',
          tag: 'DIV',
          rect: { x: 20 + (i % 8) * 140, y: 40 + Math.floor(i / 8) * 110, w: 100, h: 100 },
          text: '',
          attrs: { id: '', class: '', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
          style: styleBase,
        })
      }
      els.push({
        id: 'h1',
        pid: 'main',
        tag: 'H1',
        rect: { x: 60, y: 1600, w: 980, h: 44 },
        text: 'How to build a great Series A pitch and deck',
        attrs: { id: '', class: 'prose', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: { ...styleBase, fontSize: '36px', fontWeight: '700' },
      })
      return els
    })(),
  }

  const graph = convertWebpageLayoutToGraphData(snap, { maxNodes: 18, minAreaPx: 9000 })
  const ids = new Set((graph.nodes || []).map(n => String(n.id)))
  if (!ids.has('h1')) throw new Error('expected important heading to be kept even when early DOM contains many candidates')
}

export function testWebpageLayoutToGraphPreservesSemanticWrapperSingleChildNearEq() {
  const url = 'https://www.ycombinator.com/library/8d-how-to-build-a-great-series-a-pitch-and-deck'
  const baseStyle = {
    display: 'block',
    position: 'static',
    zIndex: 'auto',
    backgroundColor: 'rgba(0, 0, 0, 0)',
    color: '',
    borderRadius: '0px',
    borderColor: 'rgba(0, 0, 0, 0)',
    borderWidth: '0px',
    padding: '0px',
    margin: '0px',
    gap: '0px',
    justifyContent: 'normal',
    alignItems: 'normal',
    flexDirection: 'row',
    flexWrap: 'nowrap',
    fontSize: '',
    fontWeight: '',
    fontFamily: '',
    lineHeight: '',
    letterSpacing: '',
    textTransform: '',
    textAlign: '',
    boxShadow: 'none',
    opacity: '1',
  } as const
  const snap: WebpageLayoutSnapshot = {
    meta: { kind: 'layout', title: 'YC', href: url, viewport: { w: 1200, h: 800 }, scroll: { x: 0, y: 0, height: 2400 }, ts: 1 },
    elements: [
      { id: 'main', pid: '', tag: 'MAIN', rect: { x: 0, y: 0, w: 1200, h: 800 }, text: '', attrs: { id: '', class: '', role: 'main', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' }, style: baseStyle },
      { id: 'article', pid: 'main', tag: 'ARTICLE', rect: { x: 0, y: 0, w: 1200, h: 800 }, text: '', attrs: { id: '', class: 'prose', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' }, style: baseStyle },
      { id: 'h2', pid: 'article', tag: 'H2', rect: { x: 60, y: 120, w: 980, h: 34 }, text: 'Problem', attrs: { id: '', class: '', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' }, style: { ...baseStyle, fontSize: '28px', fontWeight: '700' } },
      { id: 'p1', pid: 'article', tag: 'P', rect: { x: 60, y: 170, w: 980, h: 22 }, text: 'Outline the problem you’re solving from your customer’s perspective.', attrs: { id: '', class: '', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' }, style: { ...baseStyle, fontSize: '16px' } },
    ],
  }

  const graph = convertWebpageLayoutToGraphData(snap, { maxNodes: 1200, minAreaPx: 9000 })
  const ids = new Set((graph.nodes || []).map(n => String(n.id)))
  if (!ids.has('main')) throw new Error('expected MAIN to be preserved')
  if (!ids.has('article')) throw new Error('expected ARTICLE to be preserved even when single-child near-eq')
  const edgeIds = new Set((graph.edges || []).map(e => String(e.id)))
  if (!edgeIds.has('dom:main->article')) throw new Error('expected dom nesting to keep MAIN->ARTICLE')
}

export function testWebpageLayoutToGraphAddsTextPreviewAndNormalizesText() {
  const snap: WebpageLayoutSnapshot = {
    meta: { kind: 'layout', title: 'Text', href: 'https://example.invalid/', viewport: { w: 1000, h: 800 }, scroll: { x: 0, y: 0, height: 1200 }, ts: 1 },
    elements: [
      {
        id: 'p',
        pid: '',
        tag: 'P',
        rect: { x: 40, y: 40, w: 920, h: 80 },
        text: `Hello   world\n\nthis   is    a   test  ${'x'.repeat(420)}`,
        attrs: { id: '', class: '', role: '', ariaLabel: '', placeholder: '', href: '', src: '', alt: '' },
        style: {
          display: 'block',
          position: 'static',
          zIndex: 'auto',
          backgroundColor: 'rgba(0, 0, 0, 0)',
          color: '',
          borderRadius: '0px',
          borderColor: 'rgba(0, 0, 0, 0)',
          borderWidth: '0px',
          padding: '0px',
          margin: '0px',
          gap: '0px',
          justifyContent: 'normal',
          alignItems: 'normal',
          flexDirection: 'row',
          flexWrap: 'nowrap',
          fontSize: '16px',
          fontWeight: '400',
          fontFamily: '',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textAlign: '',
          boxShadow: 'none',
          opacity: '1',
        },
      },
    ],
  }

  const graph = convertWebpageLayoutToGraphData(snap, { maxNodes: 1200, minAreaPx: 9000 })
  const node = (graph.nodes || []).find(n => String(n.id) === 'p') as GraphNode | undefined
  if (!node) throw new Error('expected text node')
  const props = (node.properties || {}) as Record<string, JSONValue>
  const t = props['dom:text']
  if (typeof t !== 'string' || t.includes('\n') || /\s{2,}/.test(t)) throw new Error('expected dom:text normalized')
  const preview = props['dom:textPreview']
  if (typeof preview !== 'string' || !preview.endsWith('…')) throw new Error('expected dom:textPreview truncated with ellipsis')
}
