import type { FlowDetails, SettingMeta } from '@/features/settings/types'

export const BYTEPLUS_CHAT_API_DOC_AREA = 'BytePlus Chat API'

export type VirtualReadonlySettingsEntry = {
  meta: SettingMeta
  details: FlowDetails
  value: string | number | boolean
  typeLabel: string
  searchHints?: string[]
}

type BytePlusApiDocRow = {
  key: string
  typeLabel: string
  value: string
  responsibility: string
  notes?: string
  searchHints?: string[]
}

const BYTEPLUS_CHAT_API_DOC_ROWS: ReadonlyArray<BytePlusApiDocRow> = [
  {
    key: 'model',
    typeLabel: 'string',
    value: 'Required. Model ID or endpoint ID.',
    responsibility: 'Selects the text or visual-understanding model for the request.',
    searchHints: ['request body required model endpoint id'],
  },
  {
    key: 'messages',
    typeLabel: 'object[]',
    value: 'Required. Chat history and prompt messages.',
    responsibility: 'Carries system, user, assistant, and tool messages.',
    searchHints: ['messages system user assistant tool multimodal'],
  },
  {
    key: 'messages.role',
    typeLabel: 'string',
    value: 'Required. system | user | assistant | tool.',
    responsibility: 'Defines the sender role for each message object.',
  },
  {
    key: 'messages.content',
    typeLabel: 'string | object[]',
    value: 'Required for system and user messages; plaintext or multimodal content list.',
    responsibility: 'Carries text-only or multimodal content.',
  },
  {
    key: 'messages.content.text',
    typeLabel: 'string',
    value: 'Required for text content objects.',
    responsibility: 'Plain text inside a multimodal content item.',
  },
  {
    key: 'messages.content.type',
    typeLabel: 'string',
    value: 'Required. text | image_url | video_url.',
    responsibility: 'Identifies each multimodal content item type.',
  },
  {
    key: 'messages.content.image_url',
    typeLabel: 'object',
    value: 'Required for image content.',
    responsibility: 'Holds image input configuration.',
  },
  {
    key: 'messages.content.image_url.url',
    typeLabel: 'string',
    value: 'Required. Image URL or base64-encoded image.',
    responsibility: 'Supplies the image input source.',
  },
  {
    key: 'messages.content.image_url.detail',
    typeLabel: 'string | null',
    value: 'Optional. low | high | xhigh.',
    responsibility: 'Controls image understanding quality.',
  },
  {
    key: 'messages.content.image_url.image_pixel_limit',
    typeLabel: 'object | null',
    value: 'Optional. Default null.',
    responsibility: 'Constrains image resizing bounds by pixel count.',
  },
  {
    key: 'messages.content.image_url.image_pixel_limit.max_pixels',
    typeLabel: 'integer',
    value: 'Optional. Maximum allowed image pixels.',
    responsibility: 'Caps oversized images before inference.',
  },
  {
    key: 'messages.content.image_url.image_pixel_limit.min_pixels',
    typeLabel: 'integer',
    value: 'Optional. Minimum allowed image pixels.',
    responsibility: 'Upscales undersized images before inference.',
  },
  {
    key: 'messages.content.video_url',
    typeLabel: 'object',
    value: 'Required for video content.',
    responsibility: 'Holds video input configuration.',
  },
  {
    key: 'messages.content.video_url.url',
    typeLabel: 'string',
    value: 'Required. Video URL or base64-encoded video.',
    responsibility: 'Supplies the video input source.',
  },
  {
    key: 'messages.content.video_url.fps',
    typeLabel: 'float | null',
    value: 'Optional. Default 1. Range: 0.2 to 5.',
    responsibility: 'Controls how many frames per second are sampled for video understanding.',
  },
  {
    key: 'messages.reasoning_content',
    typeLabel: 'string',
    value: 'Optional. Deep-reasoning chain-of-thought content.',
    responsibility: 'Returns assistant reasoning when supported by the model.',
  },
  {
    key: 'messages.encrypted_content',
    typeLabel: 'string',
    value: 'Optional. Encrypted/compressed reasoning content.',
    responsibility: 'Round-trips encrypted reasoning payloads when supported.',
  },
  {
    key: 'messages.tool_calls',
    typeLabel: 'object[]',
    value: 'Optional assistant tool-call history.',
    responsibility: 'Carries tool call records generated by the model.',
  },
  {
    key: 'messages.tool_calls.function',
    typeLabel: 'object',
    value: 'Required inside each tool call.',
    responsibility: 'Describes the function invoked by the model.',
  },
  {
    key: 'messages.tool_calls.function.name',
    typeLabel: 'string',
    value: 'Required.',
    responsibility: 'Names the called tool function.',
  },
  {
    key: 'messages.tool_calls.function.arguments',
    typeLabel: 'string',
    value: 'Required. JSON string.',
    responsibility: 'Carries model-generated function arguments.',
  },
  {
    key: 'messages.tool_calls.id',
    typeLabel: 'string',
    value: 'Required.',
    responsibility: 'Identifies an assistant tool call.',
  },
  {
    key: 'messages.tool_calls.type',
    typeLabel: 'string',
    value: 'Required. function.',
    responsibility: 'Defines the tool call kind.',
  },
  {
    key: 'messages.tool_call_id',
    typeLabel: 'string',
    value: 'Required for tool role messages.',
    responsibility: 'Associates tool output with the originating tool call.',
  },
  {
    key: 'thinking',
    typeLabel: 'object',
    value: 'Optional. Default: {"type":"enabled"}.',
    responsibility: 'Controls deep-thinking mode.',
  },
  {
    key: 'thinking.type',
    typeLabel: 'string',
    value: 'Required inside thinking. enabled | disabled | auto.',
    responsibility: 'Defines deep-thinking behavior.',
  },
  {
    key: 'stream',
    typeLabel: 'boolean | null',
    value: 'Optional. Default false.',
    responsibility: 'Returns the response in SSE streaming mode when true.',
  },
  {
    key: 'stream_options',
    typeLabel: 'object | null',
    value: 'Optional. Default null.',
    responsibility: 'Configures streaming-specific behavior.',
  },
  {
    key: 'stream_options.include_usage',
    typeLabel: 'boolean | null',
    value: 'Optional. Default false.',
    responsibility: 'Returns usage before [DONE] in streaming mode.',
  },
  {
    key: 'max_tokens',
    typeLabel: 'integer | null',
    value: 'Optional. Default 4096.',
    responsibility: 'Caps response tokens, excluding chain-of-thought.',
  },
  {
    key: 'max_completion_tokens',
    typeLabel: 'integer | null',
    value: 'Optional. Range: 0 to 65536.',
    responsibility: 'Caps total output tokens, including reasoning content.',
  },
  {
    key: 'service_tier',
    typeLabel: 'string | null',
    value: 'Optional. Default auto.',
    responsibility: 'Chooses automatic or default TPM guarantee usage.',
  },
  {
    key: 'stop',
    typeLabel: 'string | string[] | null',
    value: 'Optional. Up to four stop strings.',
    responsibility: 'Stops generation when the model hits configured strings.',
  },
  {
    key: 'reasoning_effort',
    typeLabel: 'string | null',
    value: 'Optional. Default medium. minimal | low | medium | high.',
    responsibility: 'Controls deep-reasoning effort.',
  },
  {
    key: 'response_format',
    typeLabel: 'object',
    value: 'Optional. Default: {"type":"text"}.',
    responsibility: 'Controls text, JSON object, or JSON schema output.',
  },
  {
    key: 'response_format.type',
    typeLabel: 'string',
    value: 'Required inside response_format. text | json_object | json_schema.',
    responsibility: 'Selects the response serialization mode.',
  },
  {
    key: 'response_format.json_schema',
    typeLabel: 'object',
    value: 'Required when type=json_schema.',
    responsibility: 'Defines structured JSON schema output.',
  },
  {
    key: 'response_format.json_schema.name',
    typeLabel: 'string',
    value: 'Required.',
    responsibility: 'Names the user-defined JSON schema.',
  },
  {
    key: 'response_format.json_schema.description',
    typeLabel: 'string | null',
    value: 'Optional.',
    responsibility: 'Describes the structured response purpose.',
  },
  {
    key: 'response_format.json_schema.schema',
    typeLabel: 'object',
    value: 'Required.',
    responsibility: 'Carries the JSON Schema definition.',
  },
  {
    key: 'response_format.json_schema.strict',
    typeLabel: 'boolean | null',
    value: 'Optional. Default false.',
    responsibility: 'Enables strict schema adherence.',
  },
  {
    key: 'frequency_penalty',
    typeLabel: 'float | null',
    value: 'Optional. Default 0. Range: -2.0 to 2.0.',
    responsibility: 'Discourages repetition by token frequency.',
  },
  {
    key: 'presence_penalty',
    typeLabel: 'float | null',
    value: 'Optional. Default 0. Range: -2.0 to 2.0.',
    responsibility: 'Encourages topic novelty.',
  },
  {
    key: 'temperature',
    typeLabel: 'float | null',
    value: 'Optional. Default 1. Range: 0 to 2.',
    responsibility: 'Controls sampling randomness.',
  },
  {
    key: 'top_p',
    typeLabel: 'float | null',
    value: 'Optional. Default 0.7. Range: 0 to 1.',
    responsibility: 'Controls nucleus sampling.',
  },
  {
    key: 'logprobs',
    typeLabel: 'boolean | null',
    value: 'Optional. Default false.',
    responsibility: 'Returns token log probabilities when supported.',
  },
  {
    key: 'top_logprobs',
    typeLabel: 'integer | null',
    value: 'Optional. Default 0. Range: 0 to 20.',
    responsibility: 'Controls how many top token logprobs to return.',
  },
  {
    key: 'logit_bias',
    typeLabel: 'map | null',
    value: 'Optional. Default null. Token ID -> bias [-100, 100].',
    responsibility: 'Biases token selection toward or away from specific tokens.',
  },
  {
    key: 'tools',
    typeLabel: 'object[] | null',
    value: 'Optional. Default null.',
    responsibility: 'Declares callable tools for model tool use.',
  },
  {
    key: 'tools.type',
    typeLabel: 'string',
    value: 'Required inside each tool. function.',
    responsibility: 'Defines tool kind.',
  },
  {
    key: 'tools.function',
    typeLabel: 'object',
    value: 'Required inside each tool.',
    responsibility: 'Describes a callable function tool.',
  },
  {
    key: 'tools.function.name',
    typeLabel: 'string',
    value: 'Required.',
    responsibility: 'Names the callable function tool.',
  },
  {
    key: 'tools.function.description',
    typeLabel: 'string',
    value: 'Optional.',
    responsibility: 'Helps the model decide when to call the tool.',
  },
  {
    key: 'tools.function.parameters',
    typeLabel: 'object',
    value: 'Optional. JSON Schema object.',
    responsibility: 'Defines function parameters in JSON Schema.',
  },
  {
    key: 'parallel_tool_calls',
    typeLabel: 'boolean',
    value: 'Optional. Default true.',
    responsibility: 'Allows multiple tool calls in one model response.',
  },
  {
    key: 'tool_choice',
    typeLabel: 'string | object',
    value: 'Optional. none | required | auto | explicit function selector.',
    responsibility: 'Controls whether tools may or must be used.',
  },
  {
    key: 'tool_choice.type',
    typeLabel: 'string',
    value: 'Required when tool_choice is an object. function.',
    responsibility: 'Defines explicit tool-choice kind.',
  },
  {
    key: 'tool_choice.function',
    typeLabel: 'object',
    value: 'Required when tool_choice is an object.',
    responsibility: 'Selects a specific function tool.',
  },
  {
    key: 'tool_choice.function.name',
    typeLabel: 'string',
    value: 'Required.',
    responsibility: 'Names the explicitly selected function tool.',
  },
]

const toBaseType = (typeLabel: string): SettingMeta['type'] => {
  const normalized = String(typeLabel || '').trim().toLowerCase()
  if (normalized.includes('boolean')) return 'boolean'
  if (normalized.includes('integer') || normalized.includes('float') || normalized.includes('number')) return 'number'
  return 'string'
}

export const BYTEPLUS_CHAT_API_REQUEST_DOC_ENTRIES: ReadonlyArray<VirtualReadonlySettingsEntry> =
  BYTEPLUS_CHAT_API_DOC_ROWS.map(row => ({
    meta: {
      key: `byteplusApi.${row.key}`,
      type: toBaseType(row.typeLabel),
      source: 'backendEnv',
      read: () => row.value,
    },
    value: row.value,
    typeLabel: row.typeLabel,
    searchHints: [
      'byteplus modelark chat api request parameters',
      row.key,
      ...(row.searchHints || []),
    ],
    details: {
      area: BYTEPLUS_CHAT_API_DOC_AREA,
      responsibility: row.responsibility,
      notes: row.notes || '',
      modules: ['POST /api/v3/chat/completions'],
      classes: ['Request body'],
      functions: ['ModelArk Chat API'],
    },
  }))
