export {
  BYTEPLUS_VIDEO_GENERATION_API_DOC_AREA,
  BYTEPLUS_VIDEO_GENERATION_API_DOC_ENTRIES as BYTEPLUS_VIDEO_GENERATION_API_REQUEST_DOC_ENTRIES,
  BYTEPLUS_VIDEO_GENERATION_DOC_ROWS,
  BYTEPLUS_VIDEO_GENERATION_MAPPED_VALUE_KEYS,
  BYTEPLUS_VIDEO_KEY_ACTIONS_BY_VALUE_KEY,
  getBytePlusVideoGenerationApiRowAnchorId,
  resolveBytePlusVideoWidgetApiRowKey,
} from '@/features/integrations/byteplusVideoGenerationSsot'
