import type { TestCaseTuple } from '../runner/testRunnerTypes'

export const TEST_CASES_POST_PARSER_6: TestCaseTuple[] = [
  ["chat.responseContract.prompt.kgcComputingFlowKtvShape","@/__tests__/chatResponseKgcComputingFlowContract.test","testChatKgcResponseContractPromptEnforcesComputingFlowShape"],
  ["chat.responseContract.storage.kgcComputingFlowKtvBodyTokens","@/__tests__/chatResponseKgcComputingFlowContract.test","testKgcDeterministicFallbackGeneratesComputingFlowKtvBodyTokens"],
  ["chat.responseContract.storage.kgcPreservesAssistantAnswerResponseBody","@/__tests__/chatResponseKgcComputingFlowContract.test","testKgcDeterministicFallbackPreservesAssistantAnswerInResponseBody"],
  ["chat.responseContract.storage.kgcSubstantiveAnswerComputingFlowBodyOnly","@/__tests__/chatResponseKgcComputingFlowContract.test","testKgcSubstantiveAssistantAnswerUsesComputingFlowBodyOnly"],
  ["chat.responseContract.storage.kgcSubstantiveAnswerSeedsRichMediaOutputs","@/__tests__/chatResponseKgcComputingFlowContract.test","testKgcSubstantiveAssistantAnswerSeedsRichMediaOutputs"],
  ["chat.responseContract.storage.kgcTraceOnlyNoBackfillBody","@/__tests__/chatResponseKgcComputingFlowContract.test","testKgcDeterministicFallbackTraceOnlyKeepsHumanFacingNoBackfill"],
  ["chat.responseContract.storage.kgcComputingFlowStripsAppendedCanonicalSections","@/__tests__/chatResponseKgcComputingFlowContract.test","testKgcComputingFlowStripsAppendedCanonicalSections"],
  ["richMedia.panel.markdownScrollSurfaceCanPanCanvas","@/__tests__/richMediaPanelMarkdownScrollSurfacePan.test","testRichMediaPanelMarkdownScrollSurfaceCanPanCanvasWhenForwarded"],
  ["ui.floatingPanelChat.apiKeyPrompt.byokOnly","@/__tests__/floatingPanelChatFooterSelect.test","testFloatingPanelChatApiKeyPromptIsByokOnly"],
  ["ui.floatingPanelChat.apiKey.modelIconAlignment","@/__tests__/floatingPanelChatFooterSelect.test","testFloatingPanelChatFooterByokApiKeyToggleStaysAtModelIconAndAlignsInput"],
  ["ui.floatingPanelChat.newChat.workspaceFile","@/__tests__/floatingPanelChatFooterSelect.test","testFloatingPanelChatNewChatCreatesAndFollowsCanonicalWorkspaceFile"],
  ["ui.floatingPanelChat.durableResume.newChatIdle","@/__tests__/floatingPanelChatDurableResume.test","testFloatingPanelChatDurableResumeSettlesBeforeNewChat"],
  ["ui.floatingPanelChat.contextRail.quickActions","@/__tests__/floatingPanelChatFooterSelect.test","testFloatingPanelChatContextRailAndQuickActionsStayStateOwned"],
  ["ui.floatingPanelChat.workspaceContextCache.scopeAware","@/__tests__/floatingPanelChatFooterSelect.test","testFloatingPanelChatWorkspaceContextCacheKeyIsScopeAware"],
  ["ui.floatingPanelChat.pipeline.runtimeState","@/__tests__/floatingPanelChatPipeline.test","testFloatingPanelChatPipelineStagesDeriveFromRuntimeState"],
  ["ui.floatingPanelChat.pipeline.semanticActions","@/__tests__/floatingPanelChatPipeline.test","testFloatingPanelChatPipelineStagesAreSemanticAndActionable"],
  ["ui.floatingPanelChat.contextCache.exactText","@/__tests__/floatingPanelChatPipeline.test","testFloatingPanelChatContextKeysRejectSameLengthMiddleEditStaleness"],
  ["ui.floatingPanelChat.composer.triggerRanges","@/__tests__/floatingPanelChatComposerCommands.test","testFloatingPanelChatComposerTriggerRangesStayInlineAndNeutral"],
  ["ui.floatingPanelChat.composer.ingestCommandRegistry","@/__tests__/floatingPanelChatComposerCommands.test","testFloatingPanelChatIngestCommandUsesSharedRegistryParser"],
  ["ui.floatingPanelChat.composer.memoryInvocationRuntime","@/__tests__/floatingPanelChatComposerCommands.test","testFloatingPanelChatMemoryInvocationBuildsExternalRuntimeContract"],
  ["ui.floatingPanelChat.composer.slashVariableMenus","@/__tests__/floatingPanelChatComposerCommands.test","testFloatingPanelChatComposerReusesSlashAndVariableMenus"],
  ["ui.floatingPanelChat.relayStatus.visibleSeparateFromConnectivity","@/__tests__/floatingPanelChatFooterSelect.test","testFloatingPanelChatFooterShowsRelayStatusSeparatelyFromEndpointConnectivity"],
  ["ui.floatingPanelChat.relaySummary.workspacePolicyContext","@/__tests__/floatingPanelChatFooterSelect.test","testFloatingPanelChatFooterShowsRelayWorkspacePolicySummary"],
  ["ui.floatingPanelChat.relaySummary.openLogAction","@/__tests__/floatingPanelChatFooterSelect.test","testFloatingPanelChatFooterRelaySummaryActionOpensLogCallback"],
  ["ui.floatingPanelChat.relayDiagnostics.disabledAndLoadingSkipSharedLogRows","@/__tests__/floatingPanelChatRelayDiagnostics.test","testBuildStorageChatRelayLogDescriptorReturnsNullForDisabledAndLoadingStates"],
  ["ui.floatingPanelChat.relayDiagnostics.readyAndBlockedUseSharedLogRows","@/__tests__/floatingPanelChatRelayDiagnostics.test","testBuildStorageChatRelayLogDescriptorBuildsReadyAndBlockedEntries"],
  ["strybldr.markdown.workspaceParserSkipsEmptyMarkerOnlyFrontmatterFlow","@/__tests__/strybldrWorkspaceParserFallback.test","testStrybldrWorkspaceParserSkipsEmptyMarkerOnlyFrontmatterFlow"],
  ["strybldr.runAll.videoSourceWritesVideoAgentAnalysisPacket","@/__tests__/strybldrWorkspaceParserFallback.test","testStrybldrRunAllVideoSourceWritesVideoAgentAnalysisPacket"],
  ["strybldr.runAll.videoSourceUsesWorkspaceImportUrlBridge","@/__tests__/strybldrWorkspaceParserFallback.test","testStrybldrRunAllVideoSourceUsesWorkspaceImportUrlBridge"],
  ["strybldr.runAll.videoSourceFallsBackToLaunchImportUrl","@/__tests__/strybldrWorkspaceParserFallback.test","testStrybldrRunAllVideoSourceFallsBackToLaunchImportUrl"],
]
