import React from 'react'
import { RightAlignedValueCell as SharedRightAlignedValueCell } from 'grph-shared/react/keyTypeValueRow'
import {
  KTV_VALUE_CELL_ROW_SCROLL_CLASS_NAME as SHARED_KTV_VALUE_CELL_ROW_SCROLL_CLASS_NAME,
  KTV_VALUE_ROW_SCROLL_CLASS_NAME as SHARED_KTV_VALUE_ROW_SCROLL_CLASS_NAME,
  KTV_VALUE_ROW_SCROLL_SPACIOUS_CLASS_NAME as SHARED_KTV_VALUE_ROW_SCROLL_SPACIOUS_CLASS_NAME,
  KTV_VALUE_ROW_STATUS_SHELL_CLASS_NAME as SHARED_KTV_VALUE_ROW_STATUS_SHELL_CLASS_NAME,
} from 'grph-shared/ui/keyTypeValueRows'
import { UI_RESPONSIVE_COMPACT_PANEL_FLEX_INPUT_CLASSNAME } from '@/lib/ui/responsiveElementClasses'

export interface RightAlignedValueCellProps {
  children: React.ReactNode
  className?: string
}

export const KTV_VALUE_CELL_ROW_SCROLL_CLASS_NAME = SHARED_KTV_VALUE_CELL_ROW_SCROLL_CLASS_NAME
export const KTV_VALUE_ROW_SCROLL_CLASS_NAME = SHARED_KTV_VALUE_ROW_SCROLL_CLASS_NAME
export const KTV_VALUE_ROW_SCROLL_SPACIOUS_CLASS_NAME = SHARED_KTV_VALUE_ROW_SCROLL_SPACIOUS_CLASS_NAME
export const KTV_VALUE_ROW_INPUT_SHELL_CLASS_NAME = `${UI_RESPONSIVE_COMPACT_PANEL_FLEX_INPUT_CLASSNAME} overflow-hidden`
export const KTV_VALUE_ROW_STATUS_SHELL_CLASS_NAME = SHARED_KTV_VALUE_ROW_STATUS_SHELL_CLASS_NAME

export const RightAlignedValueCell = SharedRightAlignedValueCell
