export {
  buildFloatingPanelChatComposerDisplayText,
  buildFloatingPanelChatComposerMediaParts,
  buildFloatingPanelChatComposerOverlayParts,
  deleteFloatingPanelChatComposerProjectedTokenDisplayRange,
  FLOATING_PANEL_CHAT_COMPOSER_PROJECTED_LAYOUT_CLASS_NAME,
  FloatingPanelChatComposerMediaOverlay,
  isFloatingPanelChatComposerProjectedCaretInsideChip,
  mapFloatingPanelChatComposerDisplayIndexToRawIndex,
  mapFloatingPanelChatComposerRawIndexToDisplayIndex,
  resolveFloatingPanelChatComposerRawText,
} from '@/lib/ui/textareaInvocationProjection'
